"use client";
import {useEffect,useMemo,useState} from "react";import {useRouter} from "next/navigation";import MiddleNav from "@/app/general_components/componentes_recurrentes/MiddleNav";
type Payment={forma:string;day:string;month:string;year:string;importe:string};
const empty=():Payment=>({forma:"",day:"",month:"",year:"",importe:""});const date=(p:Payment)=>`${p.day.padStart(2,"0")}/${p.month.padStart(2,"0")}/${p.year}`;
export default function AgregarFacturaProveedor(){
 const router=useRouter();const [phase,setPhase]=useState(1),[providers,setProviders]=useState<any[]>([]),[provider,setProvider]=useState<any>(null),[search,setSearch]=useState(""),[file,setFile]=useState<File|null>(null),[payments,setPayments]=useState<Payment[]>([empty()]),[confirm,setConfirm]=useState<number|null>(null),[error,setError]=useState(""),[saving,setSaving]=useState(false);
 const now=new Date(),[form,setForm]=useState({number:"",day:String(now.getDate()),month:String(now.getMonth()+1),year:String(now.getFullYear()),base:"",total:"",comments:""});
 useEffect(()=>{fetch("/api/v1/admin/proveedores").then(r=>r.json()).then(setProviders)},[]);useEffect(()=>{const x=(e:KeyboardEvent)=>{if(e.key==="Escape")setConfirm(null)};addEventListener("keydown",x);return()=>removeEventListener("keydown",x)},[]);
 const sum=payments.reduce((s,p)=>s+Number(p.importe||0),0),diff=sum-Number(form.total||0),complete=payments.every(p=>p.forma&&p.day&&p.month&&p.year&&p.importe!=="");
 function next(){setError("");if(phase===1&&!provider)return setError("Selecciona un proveedor.");if(phase===2&&(!file||!form.number||!form.day||!form.month||!form.year||form.base===""||form.total===""))return setError("Completa todos los datos y adjunta el PDF.");if(phase===3&&(!complete||Math.abs(diff)>.005))return setError("Completa los pagos y haz que cuadren exactamente con el total.");setPhase(p=>p+1)}
 async function save(){setSaving(true);try{const pre=await fetch("/api/v1/mediateca/media/presign",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({filename:file!.name,contentType:file!.type||"application/pdf",prefix:"facturas_proveedores"})}).then(async r=>{if(!r.ok)throw new Error((await r.json()).message);return r.json()});const up=await fetch(pre.uploadUrl,{method:"PUT",headers:{"Content-Type":file!.type||"application/pdf"},body:file});if(!up.ok)throw new Error("Error al subir el PDF");const res=await fetch("/api/v1/admin/facturas-proveedores",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({id_proveedor:provider.id_proveedor,numero_factura_proveedor:form.number,fecha_factura:`${form.day.padStart(2,"0")}/${form.month.padStart(2,"0")}/${form.year}`,base_imponible:form.base,importe_total:form.total,documento_src:pre.cdnUrl,comentarios:form.comments,pagos:payments.map(p=>({forma:p.forma,fecha:date(p),importe:p.importe}))})});if(!res.ok)throw new Error((await res.json()).message);router.push("/dashboard/administracion/facturas-proveedores")}catch(e:any){setError(e.message);setSaving(false)}}
 const matches=useMemo(()=>providers.filter(p=>`${p.id_proveedor} ${p.nombre_proveedor}`.toLowerCase().includes(search.toLowerCase())),[providers,search]);
 return <div className="min-h-screen bg-gray-100"><MiddleNav tituloprincipal="Agregar factura de proveedor"/><main className="mx-auto max-w-4xl p-6 lg:p-12"><div className="mb-6 flex gap-2">{[1,2,3,4].map(n=><div key={n} className={`flex-1 rounded p-2 text-center text-sm ${phase===n?"bg-blue-950 text-white":"bg-white"}`}>Fase {n}</div>)}</div><section className="rounded-xl bg-white p-6 shadow">
 {phase===1&&<><h2 className="mb-4 text-xl font-semibold">Selecciona un proveedor</h2><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Buscar proveedor..." className="mb-3 w-full rounded border p-2"/><div className="max-h-80 space-y-2 overflow-auto">{matches.map(p=><button key={p.id_proveedor} type="button" onClick={()=>setProvider(p)} className={`block w-full cursor-pointer rounded border p-3 text-left transition hover:bg-blue-50 ${provider?.id_proveedor===p.id_proveedor?"border-blue-950 bg-blue-50":""}`}>{p.nombre_proveedor} · {p.id_proveedor}</button>)}</div></>}
 {phase===2&&<><h2 className="mb-4 text-xl font-semibold">Datos de la factura</h2><div className="grid gap-4 sm:grid-cols-2"><label>Número del proveedor<input value={form.number} onChange={e=>setForm({...form,number:e.target.value})} className="mt-1 w-full rounded border p-2"/></label><label>PDF<input type="file" accept="application/pdf" onChange={e=>setFile(e.target.files?.[0]||null)} className="mt-1 w-full cursor-pointer rounded border p-2 file:cursor-pointer"/></label><fieldset><legend>Fecha</legend><div className="flex gap-1">{[["day","dd",2],["month","mm",2],["year","yyyy",4]].map(([k,p,n])=><input key={k} maxLength={Number(n)} placeholder={p} value={(form as any)[k]} onChange={e=>setForm({...form,[k]:e.target.value.replace(/\D/g,"")})} className="min-w-0 flex-1 rounded border p-2"/>)}</div></fieldset><label>Base imponible<input type="number" step=".01" value={form.base} onChange={e=>setForm({...form,base:e.target.value})} className="mt-1 w-full rounded border p-2"/></label><label>Total<input type="number" step=".01" value={form.total} onChange={e=>setForm({...form,total:e.target.value})} className="mt-1 w-full rounded border p-2"/></label></div></>}
 {phase===3&&<><div className="mb-4 flex items-center justify-between"><div><h2 className="text-xl font-semibold">Pagos</h2><p className={`text-sm ${Math.abs(diff)<.005&&complete?"text-green-700":"text-red-700"}`}>{Math.abs(diff)<.005&&complete?"Los pagos cuadran con el total":`Descuadre ${diff>=0?"+":"-"} ${Math.abs(diff).toFixed(2)} €`}</p></div><button type="button" aria-label="Añadir pago" onClick={()=>setPayments([...payments,empty()])} className="h-10 w-10 cursor-pointer rounded-full bg-blue-950 text-2xl text-white transition hover:bg-blue-800">+</button></div><div className="space-y-3">{payments.map((p,i)=><div key={i} className="grid gap-2 rounded border p-4 sm:grid-cols-[1fr_2fr_1fr_auto]"><input placeholder="Forma" value={p.forma} onChange={e=>setPayments(payments.map((x,j)=>j===i?{...x,forma:e.target.value}:x))} className="rounded border p-2"/><div className="flex gap-1">{[["day","dd",2],["month","mm",2],["year","yyyy",4]].map(([k,ph,n])=><input key={k} maxLength={Number(n)} placeholder={ph} value={(p as any)[k]} onChange={e=>setPayments(payments.map((x,j)=>j===i?{...x,[k]:e.target.value.replace(/\D/g,"")}:x))} className="min-w-0 flex-1 rounded border p-2"/>)}</div><input type="number" step=".01" placeholder="Importe" value={p.importe} onChange={e=>setPayments(payments.map((x,j)=>j===i?{...x,importe:e.target.value}:x))} className="rounded border p-2"/><button type="button" onClick={()=>setConfirm(i)} className="cursor-pointer rounded px-3 text-red-700 transition hover:bg-red-50">Eliminar</button></div>)}</div></>}
 {phase===4&&<><h2 className="text-xl font-semibold">Revisión final</h2><div className="my-4 rounded bg-blue-50 p-4"><p><b>Proveedor:</b> {provider.nombre_proveedor}</p><p><b>Factura:</b> {form.number}</p><p><b>Total:</b> {Number(form.total).toFixed(2)} €</p><p><b>Pagos:</b> {payments.length}</p></div><label>Comentarios<textarea value={form.comments} onChange={e=>setForm({...form,comments:e.target.value})} rows={5} className="mt-1 w-full rounded border p-2"/></label></>}
 {error&&<p className="mt-4 rounded bg-red-50 p-3 text-red-700">{error}</p>}<div className="mt-6 flex justify-between"><button type="button" disabled={phase===1} onClick={()=>setPhase(p=>p-1)} className="cursor-pointer rounded border px-4 py-2 transition hover:bg-gray-100 disabled:cursor-not-allowed disabled:opacity-40">Anterior</button>{phase<4?<button type="button" onClick={next} className="cursor-pointer rounded bg-blue-950 px-5 py-2 text-white transition hover:bg-blue-800">Siguiente</button>:<button type="button" disabled={saving} onClick={save} className="cursor-pointer rounded bg-blue-950 px-5 py-2 text-white transition hover:bg-blue-800 disabled:cursor-not-allowed disabled:opacity-50">{saving?"Guardando...":"Crear factura"}</button>}</div></section></main>
 {confirm!==null&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-black/40 p-4"><div role="dialog" className="relative w-full max-w-sm rounded-xl bg-white p-6"><button type="button" aria-label="Cerrar" onClick={()=>setConfirm(null)} className="absolute right-3 top-2 cursor-pointer text-3xl hover:text-blue-700">×</button><h3 className="text-lg font-semibold">¿Eliminar este pago?</h3><div className="mt-5 flex justify-end gap-2"><button type="button" onClick={()=>setConfirm(null)} className="cursor-pointer rounded border px-4 py-2 hover:bg-gray-100">Cancelar</button><button type="button" onClick={()=>{setPayments(payments.filter((_,i)=>i!==confirm));setConfirm(null)}} className="cursor-pointer rounded bg-red-700 px-4 py-2 text-white hover:bg-red-800">Eliminar</button></div></div></div>}
 </div>
}
