'use client';
import {useEffect,useState} from 'react';
import Link from 'next/link';
import {useRouter} from 'next/navigation';
import apiClient from '@/app/apiClient';
import TableColumnFilter from '@/app/components/TableColumnFilter';
import {FacturaService} from '@/app/service/FacturaService';
const columns=[['id_contrato','Contrato'],['nombre_empresa','Cliente'],['fecha_firma_contrato','Fecha de firma'],['importe_contrato_con_iva','Importe total']] as const;
export default function UninvoicedContracts(){
 const [rows,setRows]=useState<any[]>([]),[filters,setFilters]=useState<Record<string,string>>({}),[loading,setLoading]=useState(true),[busy,setBusy]=useState(''),[error,setError]=useState('');const router=useRouter();
 useEffect(()=>{apiClient.get('/api/v1/admin/facturas-clientes/contratos?sin_facturar=true').then(r=>setRows(r.data)).catch(()=>setError('No se pudieron cargar los contratos sin facturar.')).finally(()=>setLoading(false));},[]);
 const create=async(id:string)=>{setBusy(id);setError('');try{const invoice=await FacturaService.createFacturaClienteDraft(id);router.push(`/dashboard/administracion/facturas-clientes/${encodeURIComponent(invoice.id_factura_cliente)}`);}catch(reason:any){setError(reason.response?.data?.detail||reason.message||'No se pudo crear la factura.');}finally{setBusy('');}};
 const visible=rows.filter(row=>columns.every(([key])=>String(row[key]??'').toLocaleLowerCase('es').includes((filters[key]||'').trim().toLocaleLowerCase('es'))));
 return <section>{error&&<p role="alert" className="mb-3 rounded bg-red-50 p-3 text-red-700">{error}</p>}<div className="overflow-x-auto rounded bg-white"><table className="w-full text-sm"><thead><tr>{columns.map(([key,label])=><th key={key} className="p-3 text-left"><TableColumnFilter label={label} value={filters[key]||''} onChange={value=>setFilters(previous=>({...previous,[key]:value}))}/></th>)}<th className="p-3 text-left">Crear factura</th></tr></thead><tbody>{visible.map(row=>{const incomplete=!row.id_cuenta_contrato||row.importe_total_bi_contrato==null||row.importe_contrato_con_iva==null;return <tr key={row.id_contrato} className="border-t"><td className="p-3"><Link className="cursor-pointer text-blue-900 hover:underline" href={`/dashboard/comercial/contratos/${encodeURIComponent(row.id_contrato)}`}>{row.id_contrato}</Link></td><td className="p-3">{row.nombre_empresa||'Cuenta pendiente'}</td><td className="p-3">{row.fecha_firma_contrato||'—'}</td><td className="p-3">{row.importe_contrato_con_iva==null?'Pendiente':Number(row.importe_contrato_con_iva).toLocaleString('es-ES',{style:'currency',currency:row.moneda||'EUR'})}</td><td className="p-3"><button type="button" disabled={Boolean(busy)||incomplete} onClick={()=>void create(row.id_contrato)} className="rounded bg-blue-950 px-3 py-2 text-white enabled:cursor-pointer enabled:hover:bg-blue-800 disabled:cursor-not-allowed disabled:opacity-50">{busy===row.id_contrato?'Creando…':'Crear factura'}</button>{incomplete&&<p className="mt-1 text-xs">Completa cuenta e importe en el contrato.</p>}</td></tr>;})}{(loading||!visible.length)&&<tr><td colSpan={5} className="p-5">{loading?'Cargando…':'No hay contratos sin facturar con estos filtros.'}</td></tr>}</tbody></table></div></section>;
}
