import {documentMoney,documentDate,type DocumentModel} from './businessDocumentPdf';
const labels={
 es:{title:'Contrato de servicios publicitarios',date:'Fecha de firma',end:'Fecha fin',service:'Servicio',description:'Descripción',quantity:'Unidades',price:'Precio unitario',amount:'Importe',base:'Base imponible',total:'Total',payment:'Forma de pago',bank:'Banco',due:'Vencimiento',pending:'Pendiente',included:'Incluido en el total'},
 en:{title:'Advertising services contract',date:'Signature date',end:'End date',service:'Service',description:'Description',quantity:'Units',price:'Unit price',amount:'Amount',base:'Tax base',total:'Total',payment:'Payment method',bank:'Bank',due:'Due date',pending:'Pending',included:'Included in total'},
 it:{title:'Contratto di servizi pubblicitari',date:'Data di firma',end:'Data di fine',service:'Servizio',description:'Descrizione',quantity:'Unità',price:'Prezzo unitario',amount:'Importo',base:'Base imponibile',total:'Totale',payment:'Metodo di pagamento',bank:'Banca',due:'Scadenza',pending:'Da definire',included:'Incluso nel totale'},
 pt:{title:'Contrato de serviços publicitários',date:'Data de assinatura',end:'Data de fim',service:'Serviço',description:'Descrição',quantity:'Unidades',price:'Preço unitário',amount:'Valor',base:'Base tributável',total:'Total',payment:'Forma de pagamento',bank:'Banco',due:'Vencimento',pending:'Pendente',included:'Incluído no total'}
};
export function contractDocumentModel(contract:any,gm=false):DocumentModel{
 const language=gm?'es':contract.idioma_contrato||contract.propuesta_snapshot?.idioma_propuesta||'es';
 const t=labels[language as keyof typeof labels]||labels.es,currency=contract.moneda||'EUR',unknown=contract.datos_importacion?.importe_desconocido;
 const exchangeLabels:Record<string,string>={es:'Valor ofrecido en intercambio',en:'Barter value',it:'Valore dello scambio',pt:'Valor da troca'};
 const notes=[gm?(contract.propuesta_snapshot?.comentarios_es||contract.comentarios_adicionales):contract.comentarios_adicionales,contract.es_intercambio?contract.condiciones_intercambio:''].filter(Boolean).join('\n');
 const amount=(value:any)=>unknown?t.pending:documentMoney(value,currency);
 return {title:t.title,reference:contract.id_contrato,customer:contract.nombre_empresa||contract.datos_facturacion?.nombre_fiscal||'—',details:[`${t.date}: ${documentDate(contract.fecha_firma_contrato)}`,`${t.end}: ${documentDate(contract.fecha_fin_contrato)}`,contract.nombre_contacto||''].filter(Boolean),head:[t.service,t.description,t.quantity,t.price,t.amount],body:(contract.lineas_contrato||[]).map((line:any)=>{
  const global=line.linea_snapshot?.importe_global;
  return [gm?(line.producto_documento_es||line.linea_snapshot?.producto_es||line.producto||'—'):(line.producto||'—'),[gm?(line.linea_snapshot?.descripcion_es||line.descripcion_linea):line.descripcion_linea,gm?(line.linea_snapshot?.especificaciones_es||line.especificaciones_linea):line.especificaciones_linea].filter(Boolean).join('\n'),line.precio_no_desglosado?'—':String(line.unidades??1),line.precio_no_desglosado?'—':documentMoney(line.precio_unitario??line.precio_producto,currency),line.precio_no_desglosado&&!global?t.included:line.linea_snapshot?.importe_desconocido?t.pending:documentMoney(line.precio_total_personalizado??Number(line.unidades||1)*Number(line.precio_unitario||line.precio_producto||0),currency)];
 }),totals:[...(contract.es_intercambio?[[exchangeLabels[language]||exchangeLabels.es,amount(contract.importe_intercambio)]]:[]),[t.base,amount(contract.importe_total_bi_contrato)],[t.total,amount(contract.importe_contrato_con_iva)]],paymentHead:[t.due,t.payment,t.bank,t.amount],payments:(contract.ordenes||[]).filter((o:any)=>!o.cancelada).map((o:any)=>[documentDate(o.fecha_teorica_cobro),o.forma_cobro||'—',o.banco_cobro||'—',documentMoney(o.cobro_total,currency)]),notes};
}
