import {getPgPool} from '../../database/pgClient.js';
import {ProveedorError,supplierTransaction} from './SupplierAdminRepository.js';
import {validDate,cents,nextPeriod,isoDate} from './CardSettlement.js';
import {cardData} from './CardSettlementRepository.js';
const fail=m=>{throw new ProveedorError(m,409);};
export async function getTicket(id,db=getPgPool()){
 const t=(await db.query(`SELECT t.*,to_char(p3_income_date(t.fecha_ticket),'YYYY-MM-DD') fecha,COALESCE(p.nombre_proveedor,t.nombre_personalizado_proveedor) proveedor FROM administracion_tickets t LEFT JOIN administracion_proveedores p USING(id_proveedor) WHERE t.id_ticket=$1`,[id])).rows[0];if(!t)throw new ProveedorError('Ticket no encontrado.',404);delete t.archivo_contenido;
 t.associations=(await db.query('SELECT l.id_liquidacion,s.estado,l.concepto,l.importe FROM tesoreria_tarjetas_lineas l JOIN tesoreria_tarjetas_liquidaciones s ON s.id=l.id_liquidacion WHERE l.id_ticket=$1',[id])).rows;return t;
}
export async function updateTicket(id,body){return supplierTransaction(async db=>{
 await db.query("SELECT pg_advisory_xact_lock(hashtext('laboral:pagos'))");const t=(await db.query('SELECT * FROM administracion_tickets WHERE id_ticket=$1 FOR UPDATE',[id])).rows[0];if(!t)fail('Ticket no encontrado.');
 if(!body.version||new Date(body.version).getTime()!==new Date(t.updated_at).getTime())fail('El ticket ha cambiado. Recarga antes de guardar.');
 if((await db.query("SELECT 1 FROM tesoreria_tarjetas_lineas l JOIN tesoreria_tarjetas_liquidaciones s ON s.id=l.id_liquidacion WHERE l.id_ticket=$1 AND s.estado='revisada'",[id])).rowCount)fail('Reabre la liquidación antes de editar este ticket.');
 if(!validDate(body.fecha)||!Number.isFinite(Number(body.importe_total))||Number(body.importe_total)<=0||Number(body.importe_total)>9999999999||!['pendiente','punteado','revisado'].includes(body.estado_revision)||!['asociable','no_asociable'].includes(body.clasificacion)||!['efectivo','tarjeta'].includes(body.forma_pago))fail('Revisa la fecha, el importe y los estados.');
 if(t.ambito==='P3'&&(!Number.isFinite(Number(body.base_imponible))||Number(body.base_imponible)<0||Number(body.base_imponible)>Number(body.importe_total)))fail('Revisa la base imponible.');
 if(body.estado_revision!=='pendiente'&&!t.documento_src)fail('El ticket no tiene justificante.');
 if(body.id_proveedor&&!(await db.query('SELECT 1 FROM administracion_proveedores WHERE id_proveedor=$1',[body.id_proveedor])).rowCount)fail('Proveedor no válido.');
 if(t.ambito==='P3'&&!body.id_proveedor&&!t.nombre_personalizado_proveedor?.trim())fail('Selecciona un proveedor para el ticket de empresa.');
 const card=body.forma_pago==='tarjeta'&&body.clasificacion==='asociable'?(await db.query("SELECT * FROM tesoreria_tarjetas WHERE id_tarjeta=$1 AND estado='activa'",[body.id_tarjeta])).rows[0]:null;
 if(body.forma_pago==='tarjeta'&&body.clasificacion==='asociable'&&!card)fail('Selecciona una tarjeta activa.');
 if(card&&!body.id_liquidacion_tarjeta&&(await db.query("SELECT 1 FROM tesoreria_tarjetas_liquidaciones WHERE id_tarjeta=$1 AND estado='revisada' AND $2::date BETWEEN inicio AND cierre",[card.id_tarjeta,body.fecha])).rowCount)fail('La liquidación de destino está revisada.');
 const target=card&&body.id_liquidacion_tarjeta?(await db.query("SELECT *,to_char(inicio,'YYYY-MM-DD') inicio,to_char(cierre,'YYYY-MM-DD') cierre FROM tesoreria_tarjetas_liquidaciones WHERE id=$1 AND id_tarjeta=$2 AND estado='pendiente'",[body.id_liquidacion_tarjeta,card.id_tarjeta])).rows[0]:null;
 if(card&&body.id_liquidacion_tarjeta&&!target)fail('Selecciona una liquidacion pendiente de la tarjeta de destino.');
 const moving=body.forma_pago!==t.forma_pago||(card?.id_tarjeta||null)!==(t.id_tarjeta||null)||body.clasificacion!==t.clasificacion||(target?.id||null)!==(t.id_liquidacion_tarjeta||null);
 if(moving&&t.estado_revision!=='pendiente')fail('Solo se puede cambiar de destino un ticket pendiente de revisar.');
 let due=null;if(body.id_vencimiento_tarjeta&&!moving){due=(await db.query("SELECT v.*,to_char(v.fecha,'YYYY-MM-DD') fecha FROM tesoreria_cargos_vencimientos v JOIN tesoreria_cargos_recurrentes c USING(id_cargo_recurrente) WHERE v.id=$1 AND c.id_tarjeta=$2 AND c.activo",[body.id_vencimiento_tarjeta,card?.id_tarjeta])).rows[0];if(!due||cents(due.importe)!==cents(body.importe_total))fail('El importe del ticket no coincide con la suscripción prevista.');const d=await cardData(card.id_tarjeta,db),periods=d.history.filter(h=>h.estado==='pendiente').map(h=>({inicio:h.inicio,cierre:h.cierre}));let calendar=d.card;for(let n=0;n<120&&calendar.inicio_periodo&&calendar.inicio_periodo<=[body.fecha,due.fecha].sort().at(-1);n++){periods.push({inicio:calendar.inicio_periodo,cierre:calendar.proximo_cierre});calendar=nextPeriod(calendar);}if(!(target?due.fecha>=target.inicio&&due.fecha<=target.cierre:periods.some(p=>body.fecha>=p.inicio&&body.fecha<=p.cierre&&isoDate(due.fecha)>=p.inicio&&isoDate(due.fecha)<=p.cierre)))fail('El ticket y la suscripción deben pertenecer a la misma liquidación.');}
 if(moving)await db.query("UPDATE tesoreria_tarjetas_lineas SET id_ticket=NULL,estado='pendiente',motivo='' WHERE id_ticket=$1",[id]);
 await db.query(`UPDATE administracion_tickets SET fecha_ticket=$2,importe_total=$3,base_imponible=$4,id_proveedor=$5,forma_pago=$6,id_tarjeta=$7,tarjeta_ultimos_digitos=$8,tarjeta_banco=$9,tarjeta_nombre=$10,tarjeta_tipo=$11,estado_revision=$12,clasificacion=$13,comentarios=$14,id_vencimiento_tarjeta=$15,id_liquidacion_tarjeta=$16,updated_at=now() WHERE id_ticket=$1`,[id,body.fecha.split('-').reverse().join('/'),Number(body.importe_total),t.ambito==='P3'?Number(body.base_imponible):null,body.id_proveedor||null,body.forma_pago,card?.id_tarjeta||null,card?.ultimos_digitos||'',card?.banco||'',card?.nombre||'',card?.tipo||'',body.estado_revision,body.clasificacion,String(body.comentarios||'').slice(0,10000),due?.id||null,target?.id||null]);return getTicket(id,db);
});}
