"use client";

import { use, useEffect, useState } from "react";
import Link from "next/link";
import MiddleNav from "@/app/general_components/componentes_recurrentes/MiddleNav";
import { FacturaService } from "@/app/service/FacturaService";

const field="w-full rounded border border-gray-300 p-2 outline-none focus:border-blue-950 disabled:bg-gray-100";
function FiscalDate({value,onChange}:{value:string;onChange:(value:string)=>void}){const [year="",month="",day=""]=String(value||"").split("-");const set=(key:string,next:string)=>{const data:{[key:string]:string}={day,month,year,[key]:next.replace(/\D/g,"").slice(0,key==="year"?4:2)};onChange(data.day&&data.month&&data.year?`${data.year}-${data.month}-${data.day}`:"");};return <div className="grid grid-cols-[65px_65px_90px] gap-2"><input aria-label="Fecha expedición: día" inputMode="numeric" placeholder="dd" value={day} onChange={e=>set("day",e.target.value)} className={field}/><input aria-label="Fecha expedición: mes" inputMode="numeric" placeholder="mm" value={month} onChange={e=>set("month",e.target.value)} className={field}/><input aria-label="Fecha expedición: año" inputMode="numeric" placeholder="yyyy" value={year} onChange={e=>set("year",e.target.value)} className={field}/></div>}
export default function FacturaClientePage({params}:{params:Promise<{id_factura:string}>}) {
  const {id_factura}=use(params); const [invoice,setInvoice]=useState<any>(null); const [error,setError]=useState(""); const [saving,setSaving]=useState(false);
  const [emitModal,setEmitModal]=useState(false);
  const [emitData,setEmitData]=useState({issuer_nif:"",issuer_name:"",serie:"",fecha_expedicion:"",invoice_type_aeat:"R4",tipo_cambio_eur:""});
  useEffect(()=>{FacturaService.getFacturaCliente(id_factura).then(setInvoice).catch(()=>setError("No se pudo cargar la factura."));},[id_factura]);
  useEffect(()=>{if(!emitModal)return;const close=(e:KeyboardEvent)=>e.key==="Escape"&&setEmitModal(false);window.addEventListener("keydown",close);return()=>window.removeEventListener("keydown",close);},[emitModal]);
  async function save(patch:any={}){setSaving(true);setError("");try{setInvoice(await FacturaService.updateFacturaCliente(id_factura,{...invoice,...patch,lineas:invoice.lineas}));}catch(e:any){setError(e?.message||"No se pudo guardar.");}finally{setSaving(false);}}
  async function emitInvoice(){setSaving(true);setError("");try{setInvoice(await FacturaService.emitirFacturaCliente(id_factura,emitData));setEmitModal(false);}catch(e:any){setError(e?.data?.detail||e?.message||"No se pudo emitir.");}finally{setSaving(false);}}
  if(!invoice)return <div className="min-h-screen bg-gray-100"><MiddleNav tituloprincipal="Factura"/><p className="p-12">{error||"Cargando..."}</p></div>;
  const emitted=invoice.verifactu_estado_envio==="factura emitida";
  const locked=Boolean(invoice.ya_contabilizada)||emitted;
  return <div className="min-h-screen bg-gray-100 text-gray-700"><MiddleNav tituloprincipal={`Factura ${invoice.numero_factura||id_factura}`}/><main className="space-y-5 p-6 lg:p-12">{error&&<p className="rounded bg-red-50 p-3 text-red-700">{error}</p>}<div className="flex justify-end gap-3"><span className={`rounded-full px-3 py-2 text-sm ${locked?"bg-green-100 text-green-800":"bg-amber-100 text-amber-800"}`}>{locked?"Contabilizada":"Editable"}</span>{!locked&&<button type="button" onClick={()=>save({ya_contabilizada:true})} className="cursor-pointer rounded bg-blue-950 px-4 py-2 text-sm text-white transition hover:bg-blue-900">Marcar como contabilizada</button>}<button type="button" disabled={locked||saving} onClick={()=>save()} className="cursor-pointer rounded border px-4 py-2 text-sm transition hover:bg-blue-50 disabled:cursor-not-allowed disabled:opacity-50">Guardar cambios</button></div>
  <section className="rounded-xl bg-white p-6 shadow"><div className="grid gap-4 md:grid-cols-2"><label className="text-sm font-medium">Estado VERI*FACTU<select value={invoice.verifactu_estado_envio||"borrador"} onChange={e=>e.target.value==="factura emitida"&&setEmitModal(true)} disabled={emitted} className={`${field} mt-1 cursor-pointer hover:border-blue-950 disabled:cursor-not-allowed`}><option value="borrador">Borrador</option><option value="factura emitida">Factura emitida</option></select></label><label className="text-sm font-medium">Comentarios internos<textarea value={invoice.comentarios_internos||""} onChange={e=>setInvoice({...invoice,comentarios_internos:e.target.value})} className={`${field} mt-1 min-h-20`}/></label></div>{emitted&&<div className="mt-5 rounded border border-amber-300 bg-amber-50 p-4 text-sm text-amber-900"><p className="font-semibold">Esta factura está emitida y no puede modificarse.</p><p className="mt-2">No se pueden cambiar: emisor; cliente fiscal; fecha de expedición; número o serie; bases imponibles; tipos y cuotas de IVA; retenciones; total; descripción fiscal de las operaciones.</p><p className="mt-2">Solo se permite modificar el estado de cobro y los comentarios internos.</p></div>}<div className="mt-4 flex justify-end"><button type="button" disabled={saving} onClick={()=>save({comentarios_internos:invoice.comentarios_internos})} className="cursor-pointer rounded border px-4 py-2 text-sm transition hover:bg-blue-50 disabled:cursor-not-allowed">Guardar comentarios internos</button></div></section>
  <section className="rounded-xl bg-white p-6 shadow"><h2 className="mb-4 text-lg font-semibold text-blue-950">Datos fiscales</h2><div className="grid gap-4 md:grid-cols-3">{Object.entries(invoice.datos_fiscales||{}).map(([key,value])=><label key={key} className="text-sm capitalize">{key.replaceAll("_"," ")}<input disabled={locked} value={String(value||"")} onChange={e=>setInvoice({...invoice,datos_fiscales:{...invoice.datos_fiscales,[key]:e.target.value}})} className={field}/></label>)}</div></section>
  <section className="rounded-xl bg-white p-6 shadow"><h2 className="mb-4 text-lg font-semibold text-blue-950">Servicios</h2><div className="space-y-3">{invoice.lineas.map((l:any,i:number)=><div key={l.id_linea_factura} className="grid gap-3 rounded border p-3 md:grid-cols-[60px_1fr_2fr_100px_120px]"><span className="p-2">{i+1}</span><input disabled={locked} value={l.concepto||""} onChange={e=>setInvoice({...invoice,lineas:invoice.lineas.map((x:any,j:number)=>j===i?{...x,concepto:e.target.value}:x)})} className={field}/><input disabled={locked} value={l.descripcion||""} onChange={e=>setInvoice({...invoice,lineas:invoice.lineas.map((x:any,j:number)=>j===i?{...x,descripcion:e.target.value}:x)})} className={field}/><input disabled={locked} type="number" value={l.cantidad} onChange={e=>setInvoice({...invoice,lineas:invoice.lineas.map((x:any,j:number)=>j===i?{...x,cantidad:e.target.value}:x)})} className={field}/><input disabled={locked} type="number" value={l.precio_unitario} onChange={e=>setInvoice({...invoice,lineas:invoice.lineas.map((x:any,j:number)=>j===i?{...x,precio_unitario:e.target.value}:x)})} className={field}/></div>)}</div></section>
  <section className="rounded-xl bg-white p-6 shadow"><h2 className="mb-4 text-lg font-semibold text-blue-950">Órdenes de pago</h2><p className="mb-4 rounded bg-blue-50 p-3">{invoice.cobrada?"Cobrada":"Pendiente de cobro"} · Cobrado: {Number(invoice.importe_cobrado || 0).toFixed(2)} {invoice.moneda || "EUR"} · Fecha: {invoice.fecha_real_cobro || "-"}</p><div className="grid gap-3">{invoice.ordenes.map((o:any)=><Link key={o.id_orden} href={`/dashboard/administracion/control-administrativo/${o.id_orden}`} className="cursor-pointer rounded border p-4 transition hover:border-blue-950 hover:bg-blue-50"><strong>{o.id_orden}</strong><span className="ml-4">{Number(o.cobro_total||0).toFixed(2)} {invoice.moneda||"EUR"}</span><span className="ml-4">{o.cobrada?"Cobrada":"Pendiente"}</span></Link>)}</div></section>
  </main>{emitModal&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 p-4" role="dialog" aria-modal="true" aria-labelledby="emit-title"><div className="max-h-[90vh] w-full max-w-xl overflow-y-auto rounded-xl bg-white shadow-2xl"><div className="flex items-center justify-between border-b p-5"><h2 id="emit-title" className="text-lg font-semibold text-red-800">¿Estás seguro?</h2><button type="button" onClick={()=>setEmitModal(false)} aria-label="Cerrar modal" className="cursor-pointer rounded px-2 text-2xl transition hover:bg-gray-100">×</button></div><div className="space-y-4 p-5"><p className="rounded bg-red-50 p-3 text-sm text-red-800">Al emitir se asignará el número fiscal y la factura quedará inalterable. Esta acción no se puede deshacer.</p><label className="block text-sm font-medium">NIF del emisor<input value={emitData.issuer_nif} onChange={e=>setEmitData({...emitData,issuer_nif:e.target.value})} className={`${field} mt-1`}/></label><label className="block text-sm font-medium">Nombre del emisor<input value={emitData.issuer_name} onChange={e=>setEmitData({...emitData,issuer_name:e.target.value})} className={`${field} mt-1`}/></label><label className="block text-sm font-medium">Serie<input value={emitData.serie} onChange={e=>setEmitData({...emitData,serie:e.target.value})} className={`${field} mt-1`}/></label>{invoice.factura_tipo!=="ordinaria"&&<label className="block text-sm font-medium">Tipo de factura AEAT<select value={emitData.invoice_type_aeat} onChange={e=>setEmitData({...emitData,invoice_type_aeat:e.target.value})} className={`${field} mt-1 cursor-pointer hover:border-blue-950`}><option value="R1">R1 · Art. 80.1, 80.2 o error fundado en derecho</option><option value="R2">R2 · Art. 80.3</option><option value="R3">R3 · Art. 80.4</option><option value="R4">R4 · Resto</option><option value="R5">R5 · Rectificativa de factura simplificada</option></select></label>}{String(invoice.moneda||"EUR").toUpperCase()!=="EUR"&&<label className="block text-sm font-medium">Tipo de cambio a EUR<input type="number" step="0.000001" value={emitData.tipo_cambio_eur} onChange={e=>setEmitData({...emitData,tipo_cambio_eur:e.target.value})} className={`${field} mt-1`}/></label>}<fieldset><legend className="mb-1 text-sm font-medium">Fecha de expedición</legend><FiscalDate value={emitData.fecha_expedicion} onChange={value=>setEmitData({...emitData,fecha_expedicion:value})}/></fieldset></div><div className="flex justify-end gap-3 border-t p-5"><button type="button" onClick={()=>setEmitModal(false)} className="cursor-pointer rounded border px-4 py-2 transition hover:bg-gray-50">Cancelar</button><button type="button" disabled={saving} onClick={emitInvoice} className="cursor-pointer rounded bg-red-700 px-4 py-2 text-white transition hover:bg-red-800 disabled:cursor-not-allowed">{saving?"Emitiendo...":"Sí, emitir factura"}</button></div></div></div>}</div>;
}
