'use client';
import SortableTable from '@/app/components/SortableTable';

import DateInputRow from "@/app/components/DateInputRow";
import {use,useEffect,useState} from 'react';
import Link from 'next/link';
import {useRouter} from 'next/navigation';
import MiddleNav from '@/app/general_components/componentes_recurrentes/MiddleNav';
import SearchableSelect from '@/app/components/SearchableSelect';
import {OrdenService} from '@/app/service/OrdenService';
import {AgenteService} from '@/app/service/AgenteService';
import CancelOrderModal from '../CancelOrderModal';
import CollectionClosureModal from '../CollectionClosureModal';
import apiClient from '@/app/apiClient';

const field='w-full rounded border border-gray-300 bg-white p-3 outline-none focus:border-blue-950 disabled:bg-gray-100 disabled:text-gray-500';
const select=field+' enabled:cursor-pointer enabled:hover:border-blue-950';
const link='cursor-pointer text-blue-900 hover:underline';
const section='rounded-xl bg-white p-6 shadow-sm';
const grid='grid gap-5 md:grid-cols-2';
const editableFields=['id_agente','id_contacto_cobro','comentarios','con_iva','cobro_total','forma_cobro','banco_cobro','fecha_teorica_cobro','fecha_real_cobro','cobrada'];
const changedFields=(order:any,original:any)=>editableFields.filter(key=>{
  const a=order[key]??'',b=original[key]??'';
  if(key==='cobro_total'&&a!==''&&b!=='')return Number(a)!==Number(b);
  return String(a)!==String(b);
});
const money=(value:any)=>Number(value||0).toLocaleString('es-ES',{style:'currency',currency:'EUR'});
const formatDate=(value:any)=>{const text=String(value||'');return /^\d{4}-\d{2}-\d{2}/.test(text)?text.slice(0,10).split('-').reverse().join('/'):text||'Sin indicar';};
function DateParts({label,value,onChange,disabled=false}:{label:string;value:string;onChange:(value:string)=>void;disabled?:boolean}){
  const raw=String(value||'').slice(0,10),parts=raw.includes('/')?raw.split('/'):raw.split('-').reverse();
  const set=(index:number,next:string)=>{const values=[parts[0]||'',parts[1]||'',parts[2]||''];values[index]=next.replace(/\D/g,'').slice(0,index===2?4:2);onChange(values.join('/'));};
  return <fieldset disabled={disabled}><legend className="mb-2">{label}</legend><DateInputRow className="grid grid-cols-[65px_65px_90px] gap-2">{['día','mes','año'].map((name,i)=><input key={name} aria-label={`${label}: ${name}`} inputMode="numeric" placeholder={['dd','mm','yyyy'][i]} value={parts[i]||''} onChange={e=>set(i,e.target.value)} className={field}/>)}</DateInputRow></fieldset>;
}
function Toggle({label,checked,off,on,onChange,disabled=false}:{label:string;checked:boolean;off:string;on:string;onChange:(value:boolean)=>void;disabled?:boolean}){
  return <div className="flex flex-wrap items-center gap-3"><span className={!checked?'font-medium text-blue-950':'text-gray-600'}>{off}</span><button type="button" role="switch" aria-label={label} aria-checked={checked} disabled={disabled} onClick={()=>onChange(!checked)} className={`relative h-7 w-12 rounded-full transition enabled:cursor-pointer enabled:hover:ring-2 enabled:hover:ring-blue-300 disabled:opacity-50 ${checked?'bg-blue-950':'bg-gray-400'}`}><span className={`absolute top-1 h-5 w-5 rounded-full bg-white transition ${checked?'left-6':'left-1'}`}/></button><span className={checked?'font-medium text-blue-950':'text-gray-600'}>{on}</span></div>;
}
export default function OrdenAdministrativaPage({params}:{params:Promise<{id_orden:string[]}>}){
  const routeParams=use(params),idOrden=routeParams.id_orden.map(decodeURIComponent).join('/'),router=useRouter();
  const [order,setOrder]=useState<any>(null),[original,setOriginal]=useState<any>(null),[agents,setAgents]=useState<any[]>([]);
  const [error,setError]=useState(''),[notice,setNotice]=useState(''),[saving,setSaving]=useState(false),[cancelOpen,setCancelOpen]=useState(false);
  const [closureOpen,setClosureOpen]=useState(false);
  const [invoiceModal,setInvoiceModal]=useState(false),[availableInvoices,setAvailableInvoices]=useState<any[]>([]);
  useEffect(()=>{if(!invoiceModal)return;const esc=(e:KeyboardEvent)=>{if(e.key==='Escape')setInvoiceModal(false)};window.addEventListener('keydown',esc);return()=>window.removeEventListener('keydown',esc)},[invoiceModal]);
  async function openInvoiceModal(){setInvoiceModal(true);try{const result=await apiClient.get('/api/v1/admin/facturas-clientes/ordenes/vincular',{params:{id_cuenta:order.id_cuenta}});setAvailableInvoices(result.data||[])}catch(e:any){setError(e?.message||'No se pudieron cargar las facturas disponibles.')}}
  async function linkInvoice(idFactura:string){setSaving(true);setError('');try{await apiClient.post('/api/v1/admin/facturas-clientes/ordenes/vincular',{id_orden:idOrden,id_factura:idFactura});const updated=await OrdenService.getOrdenAdministrativa(idOrden);setOrder(updated);setOriginal(updated);setInvoiceModal(false);setNotice('Factura vinculada.')}catch(e:any){setError(e?.response?.data?.detail||e?.message||'No se pudo vincular la factura.')}finally{setSaving(false)}}
  useEffect(()=>{let active=true;setOrder(null);setError('');setNotice('');Promise.all([OrdenService.getOrdenAdministrativa(idOrden),AgenteService.getAgentes()]).then(([row,agentRows])=>{if(active){setOrder(row);setOriginal(row);setAgents(agentRows);}}).catch((e:any)=>{if(active)setError(e?.message||'No se pudo cargar la orden.');});return()=>{active=false;};},[idOrden]);
  const change=(key:string,value:any)=>{setOrder((current:any)=>({...current,[key]:value}));setNotice('');};
  async function save(event:React.FormEvent){
    event.preventDefault();setError('');setNotice('');setSaving(true);
    try{
      const payload=Object.fromEntries(changedFields(order,original).map(k=>[k,order[k]]));
      const saved=await OrdenService.updateOrdenAdministrativa(idOrden,payload);setOrder(saved);setOriginal(saved);setNotice('Cambios guardados.');
    }catch(e:any){setError(e?.data?.detail||e?.message||'No se pudo guardar.');}finally{setSaving(false);}
  }
  if(!order)return <div><MiddleNav tituloprincipal="Orden"/><p role={error?'alert':'status'} className="p-12">{error||'Cargando…'}</p></div>;
  const cancelled=Boolean(order.cancelada),disabled=cancelled||saving||Boolean(order.cobro_cerrado),locked=disabled||Boolean(order.ya_contabilizada),bankLocked=disabled||Boolean(order.cobro_revision_bancaria);
  const invoice=order.factura,withVat=order.con_iva!==false;
  const dirty=changedFields(order,original).length>0;
  const agentOptions=agents.map(a=>({value:a.id_agente,label:a.nombre_completo_agente||`${a.nombre_agente||''} ${a.apellidos_agente||''}`.trim()||a.id_agente}));
  if(order.id_agente&&!agentOptions.some(a=>a.value===order.id_agente))agentOptions.push({value:order.id_agente,label:order.agente||order.id_agente});
  const contactOptions=(order.contactos_cuenta||[]).map((c:any)=>({value:c.id_contacto,label:c.nombre_completo_contacto||`${c.nombre_contacto||''} ${c.apellidos_contacto||''}`.trim()||c.email_contacto||c.id_contacto}));
  if(order.id_contacto_cobro&&!contactOptions.some((c:any)=>c.value===order.id_contacto_cobro))contactOptions.push({value:order.id_contacto_cobro,label:order.id_contacto_cobro});
  return <div className="min-h-screen bg-gray-100 text-gray-700"><MiddleNav tituloprincipal={`Orden ${idOrden}`}/><main className="mx-auto max-w-6xl p-5 pb-28 lg:p-8 lg:pb-28"><form onSubmit={save} className="space-y-6">
    <div className="flex flex-wrap items-center justify-between gap-3"><Link href="/dashboard/administracion/control-administrativo" className={link}>← Control administrativo</Link>{!cancelled&&<button type="button" disabled={saving} onClick={()=>setCancelOpen(true)} className="rounded border border-red-700 px-4 py-2 text-red-700 enabled:cursor-pointer enabled:hover:bg-red-50 disabled:opacity-50">Cancelar orden</button>}</div>
    {!cancelled&&dirty&&<button type="submit" disabled={saving} className="fixed bottom-6 right-6 z-40 rounded-full bg-blue-950 px-6 py-3 text-white shadow-xl transition enabled:cursor-pointer enabled:hover:bg-blue-800 enabled:hover:shadow-2xl disabled:opacity-50">{saving?'Guardando…':'Guardar'}</button>}
    {error&&<p role="alert" className="rounded bg-red-50 p-3 text-red-700">{error}</p>}{notice&&<p role="status" className="rounded bg-green-50 p-3 text-green-800">{notice}</p>}
    {cancelled&&<p className="rounded border border-amber-300 bg-amber-50 p-4 text-amber-900">Orden cancelada. Se conserva para consulta y no genera ingresos previstos.</p>}
    {!cancelled && <section className={section}><div className="flex flex-wrap items-center justify-between gap-3"><h2 className="text-xl font-semibold text-blue-950">Gestión del cobro</h2><button type="button" disabled={saving || dirty} onClick={()=>setClosureOpen(true)} className="rounded border px-4 py-2 enabled:cursor-pointer enabled:hover:bg-blue-50 disabled:cursor-not-allowed disabled:opacity-50">{order.cobro_cerrado?'Reabrir gestión del cobro':'Cerrar cobro por acuerdo'}</button></div>{dirty&&<p className="mt-2 text-sm">Guarda los cambios antes de cerrar o reabrir el cobro.</p>}{order.cobro_cerrado&&<p className="mt-3 rounded bg-blue-50 p-3">Cerrado: {order.cierre_cobro.motivo}. Diferencia asumida: {money(order.cierre_cobro.diferencia_asumida)}. Se conservan los cobros reales.</p>}</section>}
    <section className={section}><h2 className="mb-5 text-xl font-semibold text-blue-950">Datos de la orden</h2><div className={grid}>
      <div><p className="mb-2">Contrato</p><div className={field}>{order.id_contrato?<Link className={link} href={'/dashboard/comercial/contratos/'+encodeURIComponent(order.id_contrato)}>{order.id_contrato}</Link>:'Sin contrato'}</div></div>
      <div><p className="mb-2">Número de orden</p><p className={field}>{order.numero_orden}</p></div>
      <div><p className="mb-2">Cuenta</p><div className={field}>{order.id_cuenta?<Link className={link} href={'/dashboard/comercial/cuentas/'+encodeURIComponent(order.id_cuenta)}>{order.cliente||order.id_cuenta}</Link>:'Sin cuenta asociada'}</div></div>
      <div><p className="mb-2">Agente actual de la orden</p><SearchableSelect label="Agente actual de la orden" value={order.id_agente||''} options={agentOptions} onChange={value=>change('id_agente',value)} disabled={disabled} required={Boolean(original.id_agente)} inputClassName={field}/></div>
      <div><p className="mb-2">Estado</p><p className={field}>{order.cancelada?(order.cancelacion_detalle?.numero_abono?'Abonada ? '+order.cancelacion_detalle.numero_abono:'Cancelada'):order.cobro_cerrado?'Cerrada por acuerdo':order.cobrada?'Cobrada':'Pendiente de cobro'}</p></div>
      <div><p className="mb-2">Fecha de firma de la propuesta</p><p className={field}>{order.id_propuesta?formatDate(order.fecha_firma_propuesta):'Sin propuesta de origen'}</p></div>
    </div></section>
    <section className={section}><h2 className="mb-5 text-xl font-semibold text-blue-950">Factura asociada</h2>{invoice?<div className="space-y-5">
      {invoice.eliminada&&<p className="rounded bg-amber-50 p-3">Copia histórica de la factura eliminada al cancelar la orden.</p>}
      <div className={grid}><div><p className="mb-2">Factura completa</p>{invoice.eliminada?<p>{invoice.numero_factura||invoice.id_factura_cliente} · Eliminada</p>:<Link className={link} href={'/dashboard/administracion/facturas-clientes/'+encodeURIComponent(invoice.id_factura_cliente)}>{invoice.numero_factura||invoice.id_factura_cliente} · {order.tipo_factura}</Link>}</div><div><p className="mb-2">Fecha de factura</p><p>{formatDate(invoice.fecha_emision||invoice.fecha_factura)}</p></div></div>
      <div className="rounded border p-4"><div className="mb-3 flex flex-wrap justify-between gap-3"><span>{invoice.datos_fiscales?.nombre_fiscal||order.cliente||'Cuenta no disponible'}</span><span>{invoice.estado||'En proceso'}</span></div>{invoice.lineas?.length>0?<div className="overflow-x-auto"><SortableTable className="w-full text-sm"><thead className="border-b text-left"><tr><th className="p-2">Concepto</th><th className="p-2">Cantidad</th><th className="p-2">Base imponible</th><th className="p-2">IVA</th><th className="p-2">Total</th></tr></thead><tbody>{invoice.lineas.map((l:any)=><tr key={l.id_linea_factura} className="border-b"><td className="p-2">{l.concepto}{l.descripcion&&<p className="text-gray-500">{l.descripcion}</p>}</td><td className="p-2">{l.cantidad}</td><td className="p-2">{money(l.base_imponible)}</td><td className="p-2">{l.iva_porcentaje}%</td><td className="p-2">{money(l.importe_total)}</td></tr>)}</tbody></SortableTable></div>:<p className="text-sm text-gray-500">La factura no tiene líneas registradas.</p>}<div className="mt-4 flex flex-wrap justify-end gap-6"><span>Base imponible: {money(invoice.base_imponible)}</span><strong>Total: {money(invoice.importe_total)}</strong></div></div>
      <label className="block">Otras órdenes de la factura<select aria-label="Otras órdenes de la factura" className={select+' mt-2'} value="" disabled={!invoice.otras_ordenes?.length} onChange={e=>{if(e.target.value)router.push('/dashboard/administracion/control-administrativo/'+e.target.value.split('/').map(encodeURIComponent).join('/'));}}><option value="">{invoice.otras_ordenes?.length?'Selecciona una orden':'No hay otras órdenes'}</option>{invoice.otras_ordenes?.map((o:any)=><option key={o.id_orden} value={o.id_orden}>{o.id_orden} · {money(o.cobro_total)}{o.cancelada?' · Cancelada':''}</option>)}</select></label>
    </div>:<div className="flex flex-wrap items-center gap-3"><p>Sin factura asociada.</p>{!cancelled&&<><button type="button" onClick={()=>void openInvoiceModal()} className="cursor-pointer rounded border px-3 py-2 text-sm text-blue-950 hover:bg-blue-50">Vincular factura existente</button><Link href={`/dashboard/administracion/facturas-clientes/crear?origen=orden&id_orden=${encodeURIComponent(idOrden)}`} className="cursor-pointer rounded bg-blue-950 px-3 py-2 text-sm text-white hover:bg-blue-800">Crear factura previa para esta orden</Link></>}</div>}</section>
    <section className={section}><h2 className="mb-5 text-xl font-semibold text-blue-950">Cobro</h2><div className="space-y-5">
      {order.ya_contabilizada&&<p className="text-sm text-gray-500">Los importes están bloqueados porque la factura está contabilizada.</p>}
      <Toggle label="Importe con IVA" checked={withVat} off="Sin IVA" on="Con IVA" onChange={value=>change('con_iva',value)} disabled={locked}/>
      <div className={grid}><label>{withVat?'Importe con IVA':'Importe total'}<input aria-label={withVat?'Importe con IVA':'Importe total'} type="number" min="0" step="0.01" required value={order.cobro_total??''} disabled={locked} onChange={e=>change('cobro_total',e.target.value)} className={field+' mt-2'}/></label>{withVat&&<label>Base imponible<input aria-label="Base imponible" value={(Number(order.cobro_total||0)/1.21).toFixed(2)} readOnly className={field+' mt-2 bg-gray-50'}/></label>}</div>
      <div className={grid}><label>Forma de cobro<select className={select+' mt-2'} value={order.forma_cobro||''} disabled={locked} onChange={e=>change('forma_cobro',e.target.value)}>{[...new Set([order.forma_cobro||'','transferencia','recibo','tarjeta','efectivo','pagaré','PayPal'])].map(value=><option key={value} value={value}>{value||'Seleccionar'}</option>)}</select></label><label>Banco<select className={select+' mt-2'} value={order.banco_cobro||''} disabled={locked} onChange={e=>change('banco_cobro',e.target.value)}>{[...new Set([order.banco_cobro||'','Sabadell','Santander','PayPal'])].map(value=><option key={value} value={value}>{value||'Seleccionar'}</option>)}</select></label></div>
      <div className={grid}><DateParts label="Fecha teórica de cobro" value={order.fecha_teorica_cobro||''} disabled={disabled} onChange={value=>change('fecha_teorica_cobro',value)}/><div><p className="mb-2">Fecha real de cobro</p><Toggle label="Estado de cobro" checked={Boolean(order.cobrada)} off="Pendiente de cobro" on="Cobrada" disabled={bankLocked} onChange={value=>setOrder({...order,cobrada:value,fecha_real_cobro:value?order.fecha_real_cobro:''})}/>{order.cobrada&&<div className="mt-3"><DateParts label="Fecha real de cobro" value={order.fecha_real_cobro||''} disabled={bankLocked} onChange={value=>change('fecha_real_cobro',value)}/></div>}</div></div>
      {order.cobro_revision_bancaria&&<p className="rounded bg-blue-50 p-3 text-sm">El estado y la fecha real de cobro se gestionan desde la revisión bancaria.</p>}
    </div></section>
    <section className={section}><h2 className="mb-5 text-xl font-semibold text-blue-950">Otros datos de la orden</h2><div className={grid}>
      <div><p className="mb-2">Remesa</p><p className={field}>{(order.recibos||[]).map((r:any)=>r.id_remesa).filter(Boolean).join(', ')||order.id_remesa||(/recibo/i.test(order.forma_cobro)?'Sin remesa asignada aún':'No corresponde')}</p></div>
      <div><p className="mb-2">Propuesta de origen</p><div className={field}>{order.id_propuesta?<Link className={link} href={'/dashboard/comercial/propuestas/'+encodeURIComponent(order.id_propuesta)}>{order.nombre_propuesta||order.id_propuesta}</Link>:'Sin propuesta de origen'}</div></div>
      <div><p className="mb-2">Agente de la propuesta</p><p className={field}>{order.agente_propuesta||order.id_agente_propuesta||'Sin asignar'}</p></div>
      <div><p className="mb-2">Contacto de la propuesta</p><p className={field}>{order.contacto_propuesta||order.id_contacto_propuesta||'Sin contacto'}</p></div>
      <div className="md:col-span-2"><p className="mb-2">Contacto de seguimiento de cobro</p><SearchableSelect label="Contacto de seguimiento de cobro" value={order.id_contacto_cobro||''} options={contactOptions} onChange={value=>change('id_contacto_cobro',value)} disabled={disabled} placeholder="Selecciona un contacto de esta cuenta" inputClassName={field}/></div>
      <label className="md:col-span-2">Comentarios<textarea value={order.comentarios||''} disabled={disabled} onChange={e=>change('comentarios',e.target.value)} rows={4} className={field+' mt-2'}/></label>
    </div>{Object.keys(order.datos_importacion||{}).length>0&&<details className="mt-5 rounded border p-3"><summary className="cursor-pointer rounded p-2 hover:bg-blue-50">Datos originales del Excel</summary><dl className="mt-3 grid gap-3 md:grid-cols-2">{Object.entries(order.datos_importacion).map(([key,value])=><div key={key}><dt className="text-sm text-gray-500">{key}</dt><dd>{typeof value==='object'?JSON.stringify(value):String(value??'')}</dd></div>)}</dl></details>}</section>
  </form>{closureOpen&&<CollectionClosureModal order={order} onClose={()=>setClosureOpen(false)} onSaved={updated=>{setOrder(updated);setOriginal(updated);setClosureOpen(false);setNotice('Gestión del cobro actualizada.');}}/>}{invoiceModal&&<div role="dialog" aria-modal="true" aria-label="Vincular factura" className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 p-4"><div className="max-h-[80vh] w-full max-w-lg overflow-auto rounded-xl bg-white p-5"><div className="mb-4 flex items-center justify-between"><h2 className="font-semibold text-blue-950">Facturas sin asignar de la cuenta</h2><button type="button" aria-label="Cerrar" onClick={()=>setInvoiceModal(false)} className="cursor-pointer rounded px-2 text-2xl hover:bg-gray-100">×</button></div><p className="mb-4 text-sm text-gray-600">Solo se pueden vincular facturas con el mismo importe que la orden.</p>{availableInvoices.map(f=><button key={f.id_factura_cliente} type="button" disabled={saving||Math.abs(Number(f.importe_total)-Number(order.cobro_total))>0.01} onClick={()=>void linkInvoice(f.id_factura_cliente)} className="mb-2 block w-full cursor-pointer rounded border p-3 text-left text-sm hover:bg-blue-50 disabled:cursor-not-allowed disabled:opacity-50">{f.numero_factura||f.id_factura_cliente} · {money(f.importe_total)} · {f.estado}</button>)}{!availableInvoices.length&&<p className="text-sm text-gray-500">No hay facturas disponibles.</p>}</div></div>}{cancelOpen&&<CancelOrderModal idOrden={idOrden} onClose={()=>setCancelOpen(false)} onCancelled={saved=>{setOrder(saved);setOriginal(saved);setCancelOpen(false);setError('');setNotice('Orden cancelada.');}}/>}</main></div>;
}
