"use client";

import { use, useEffect, useState } from "react";
import MiddleNav from "@/app/general_components/componentes_recurrentes/MiddleNav";
import { OrdenService } from "@/app/service/OrdenService";

const field="w-full rounded border border-gray-300 p-3 outline-none focus:border-blue-950 disabled:bg-gray-100";
function DateParts({label,value,onChange}:{label:string;value:string;onChange:(value:string)=>void}) {
  const raw=String(value||"").slice(0,10); const parts=raw.includes("/")?raw.split("/"):raw.split("-").reverse();
  const set=(index:number,next:string)=>{const values=[parts[0]||"",parts[1]||"",parts[2]||""];values[index]=next.replace(/\D/g,"").slice(0,index===2?4:2);onChange(values.every(Boolean)?`${values[2]}-${values[1]}-${values[0]}`:"");};
  return <fieldset><legend>{label}</legend><div className="grid grid-cols-[65px_65px_90px] gap-2"><input aria-label={`${label}: día`} inputMode="numeric" placeholder="dd" value={parts[0]||""} onChange={e=>set(0,e.target.value)} className={field}/><input aria-label={`${label}: mes`} inputMode="numeric" placeholder="mm" value={parts[1]||""} onChange={e=>set(1,e.target.value)} className={field}/><input aria-label={`${label}: año`} inputMode="numeric" placeholder="yyyy" value={parts[2]||""} onChange={e=>set(2,e.target.value)} className={field}/></div></fieldset>;
}
export default function OrdenAdministrativaPage({params}:{params:Promise<{id_orden:string[]}>}) {
  const routeParams=use(params);const id_orden=routeParams.id_orden.map(decodeURIComponent).join("/");const [order,setOrder]=useState<any>(null);const [error,setError]=useState("");
  useEffect(()=>{OrdenService.getOrdenAdministrativa(id_orden).then(setOrder).catch(()=>setError("No se pudo cargar la orden."));},[id_orden]);
  async function save(){try{setOrder(await OrdenService.updateOrdenAdministrativa(id_orden,order));}catch(e:any){setError(e?.message||"No se pudo guardar.");}}
  if(!order)return <div><MiddleNav tituloprincipal="Orden"/><p className="p-12">{error||"Cargando..."}</p></div>;
  const locked=Boolean(order.ya_contabilizada);
  return <div className="min-h-screen bg-gray-100 text-gray-700"><MiddleNav tituloprincipal={`Orden ${id_orden}`}/><main className="p-6 lg:p-12"><section className="mx-auto max-w-4xl rounded-xl bg-white p-6 shadow"><div className="mb-5 flex items-center justify-between"><div><h2 className="text-xl font-semibold text-blue-950">Detalles de la orden</h2><p className="text-sm text-gray-500">{locked?"Los importes están bloqueados porque la factura está contabilizada.":"Los datos económicos todavía son editables."}</p></div><button type="button" onClick={save} className="cursor-pointer rounded bg-blue-950 px-4 py-2 text-white transition hover:bg-blue-900">Guardar</button></div>{error&&<p className="mb-4 bg-red-50 p-3 text-red-700">{error}</p>}<div className="grid gap-4 md:grid-cols-2"><label>Contrato<input disabled value={order.id_contrato||""} className={field}/></label><label>Factura<input disabled value={order.id_factura||""} className={field}/></label><label>Base imponible<input disabled={locked} type="number" value={order.base_imponible||0} onChange={e=>setOrder({...order,base_imponible:e.target.value})} className={field}/></label><label>Total<input disabled={locked} type="number" value={order.cobro_total||0} onChange={e=>setOrder({...order,cobro_total:e.target.value})} className={field}/></label><label>Forma de cobro<input disabled={locked} value={order.forma_cobro||""} onChange={e=>setOrder({...order,forma_cobro:e.target.value})} className={field}/></label><label>Banco<input disabled={locked} value={order.banco_cobro||""} onChange={e=>setOrder({...order,banco_cobro:e.target.value})} className={field}/></label><DateParts label="Fecha teórica" value={order.fecha_teorica_cobro||""} onChange={value=>setOrder({...order,fecha_teorica_cobro:value})}/><DateParts label="Fecha real" value={order.fecha_real_cobro||""} onChange={value=>setOrder({...order,fecha_real_cobro:value})}/><label className="flex cursor-pointer items-center gap-3 rounded border p-3 transition hover:bg-blue-50"><input type="checkbox" checked={Boolean(order.cobrada)} onChange={e=>setOrder({...order,cobrada:e.target.checked})}/> Cobrada</label></div></section></main></div>;
}
