'use client';
import IncomeReviewFields from '../IncomeReviewFields';
import ReviewRecipientTable from '../ReviewRecipientTable';
import { money, select, type ReviewPhaseContext } from './ReviewPhaseContext';

export default function ReviewRecipients({ context }: { context: ReviewPhaseContext }) {
  const { phase, mode, forced, common, simpleAssignment, saving, lines, drafts, data, entities, entityName, patch, conflict, previousOwners } = context;
  return <>{phase === 2 && <>
        {mode==='review' && !forced && lines.filter(l=>Number(l.importe)>0).map(l=><IncomeReviewFields key={l.id_linea_banco} line={l} draft={drafts[l.id_linea_banco]} orders={data.orders} remesas={data.remesas} onChange={value=>patch(l.id_linea_banco,value)} />)}
        {(common ? lines.slice(0,1) : lines).map(l => { const d = drafts[l.id_linea_banco]; if(mode==='review' && Number(l.importe)>0)return <div key={d.id} className="mb-4 rounded border p-4">Ingreso: {d.incomeType} · {d.incomeType==='remesa'?d.remesaIds.join(', '):d.orderIds?.length?d.orderIds.join(', '):d.orderId || 'Sin orden'} · {entityName(d) || 'Las cuentas se obtienen de las órdenes asociadas'}{(l.id_proveedor || l.id_agente || l.id_cuenta && d.incomeType!=='remesa' && l.id_cuenta!==d.entityId) && <label className="mt-3 block">Asignación anterior: {previousOwners(l)}<select className={select} value={d.resolution} onChange={e=>patch(d.id,{resolution:e.target.value})}><option value="">Selecciona cómo continuar</option><option value="skip">Omitir</option><option value="overwrite">Sobrescribir asignación</option></select></label>}</div>; return <div key={l.id_linea_banco} className="mb-4 space-y-3 rounded border p-4"><h3>{common ? `Asignación para los ${lines.length} registros` : `${l.id_linea_banco} · ${money(l.importe)} · ${l.concepto}`}</h3>
          {!simpleAssignment && <select aria-label={`Tipo ${l.id_linea_banco}`} disabled={mode === 'charge'} className={select} value={d.entityType} onChange={e => patch(d.id, { entityType:e.target.value, entityId:'', entityChosen:false, chargeId:'', resolution:'', create:false, increase:false })}><option value="proveedor">Proveedor</option><option value="cliente">Cliente / ingreso</option><option value="nomina">Nómina</option>{mode!=='assign'&&<option value="otro">Otro</option>}</select>}
          {d.entityType==='otro'?<p>Movimiento sin proveedor, cliente ni empleado asociado. Puedes añadir un comentario antes de confirmar.</p>:<ReviewRecipientTable key={d.entityType} type={d.entityType} rows={entities(d.entityType)} disabled={mode === 'charge'||saving} value={d.entityChosen?d.entityId:''} onSelect={value=>patch(d.id,{entityType:d.entityType,entityId:value,entityChosen:true,chargeId:value===d.entityId?d.chargeId:'',resolution:'',create:false,increase:false})}/>}
          {!common && (d.entityId || d.entityType==='otro') && (conflict(l,d) ? <div className="rounded bg-amber-50 p-3"><p>Este registro está asignado a {previousOwners(l)}. Se sustituirán también sus vínculos de pago incompatibles.</p><select aria-label={`Resolver ${d.id}`} className={select} value={d.resolution} onChange={e => patch(d.id, { resolution:e.target.value })}><option value="">Debes elegir</option><option value="skip">Desseleccionar esta reasignación</option><option value="overwrite">Sobrescribir con {entityName(d)}</option></select></div> : previousOwners(l) && <p className="rounded bg-blue-50 p-3">Aviso: {d.id} ya está asignado a {entityName(d)}. Puedes continuar.</p>)}
        </div>; })}
      </>}
      {phase === 2 && common && lines.some(l=>drafts[l.id_linea_banco].entityId && previousOwners(l) && !conflict(l,drafts[l.id_linea_banco])) && <p className="mb-3 rounded bg-blue-50 p-3">{lines.filter(l=>drafts[l.id_linea_banco].entityId && previousOwners(l) && !conflict(l,drafts[l.id_linea_banco])).length} registros ya tienen este destinatario. Puedes continuar.</p>}
      {phase === 2 && common && lines.map(l => { const d=drafts[l.id_linea_banco]; return (d.entityId || d.entityType==='otro') && conflict(l,d) ? <div key={d.id} className="mb-3 rounded bg-amber-50 p-3"><p>{d.id}: {previousOwners(l)}{!conflict(l,d) && ' (ya asignado al mismo destinatario)'}</p>{conflict(l,d) && <select aria-label={`Resolver ${d.id}`} className={select} value={d.resolution} onChange={e=>patch(d.id,{resolution:e.target.value})}><option value="">Debes elegir</option><option value="skip">Omitir esta reasignación</option><option value="overwrite">Sobrescribir con {entityName(d)}</option></select>}</div> : null; })}</>;
}
