'use client';
import SortableTable from '@/app/components/SortableTable';

import TableFilters from '@/app/components/TableFilters';
import {useEffect,useMemo,useRef,useState} from 'react';
import PublishFlatplan from './PublishFlatplan';
import apiClient from '@/app/apiClient';
import SearchableSelect from '@/app/components/SearchableSelect';
import {flatplanRows,mutateFlatplan,flatplanMagazinePageLabel} from '@/app/lib/preliminaryFlatplan';

type Block={id:string;contentId?:string;account:string;type:string;detail:string;pages:number;uncertain?:boolean;arrival?:string;sourceNote?:string;originalPages?:string;cover?:string};
type Plan={slots:(string|null)[];blocks:Block[];excluded:string[]};
type Book={plan:Plan;version:number;sources:Block[]};
type Operation={type:'move'|'remove'|'insert-empty'|'add'|'resize'|'remove-empty'|'swap'|'fill-hole';blockId?:string};
const button='rounded border px-3 py-2 text-sm transition enabled:cursor-pointer enabled:hover:bg-blue-100 disabled:cursor-not-allowed disabled:opacity-40';
const description=(row:any)=>row.block?`${row.block.account||row.block.type} · ${row.block.type} · parte ${row.part}/${row.total}`:'Página libre';
export default function PreliminaryFlatplan({magazineId}:{magazineId:string}) {
 const [book,setBook]=useState<Book|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[operation,setOperation]=useState<Operation|null>(null);
 const [target,setTarget]=useState(''),[sourceId,setSourceId]=useState(''),[count,setCount]=useState(1),[compact,setCompact]=useState(false),[selected,setSelected]=useState<number|null>(null);
 const [filters,setFilters]=useState<Record<string,string>>({});const dialog=useRef<HTMLDivElement>(null),returnFocus=useRef<HTMLElement|null>(null);
 const endpoint=`/api/v1/produccion/gestiones-produccion/${encodeURIComponent(magazineId)}/planillo-previo`;
 useEffect(()=>{let cancelled=false;setBook(null);setError('');apiClient.get(endpoint).then(r=>{if(!cancelled)setBook(r.data);}).catch(e=>{if(!cancelled)setError(e.response?.data?.message||e.message);});return()=>{cancelled=true;};},[endpoint]);
 useEffect(()=>{
  if(!operation)return;dialog.current?.focus();
  const key=(e:KeyboardEvent)=>{if(e.key==='Escape'){e.preventDefault();setOperation(null);returnFocus.current?.focus();}if(e.key==='Tab'){const nodes=dialog.current?.querySelectorAll<HTMLElement>('button:not(:disabled),input:not(:disabled),[tabindex="0"]');if(!nodes?.length)return;const first=nodes[0],last=nodes[nodes.length-1];if(e.shiftKey&&(document.activeElement===first||document.activeElement===dialog.current)){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}};
  document.addEventListener('keydown',key);return()=>document.removeEventListener('keydown',key);
 },[operation]);
 const rows=useMemo(()=>book?flatplanRows(book.plan):[],[book]);
 const open=(op:Operation,index?:number)=>{returnFocus.current=document.activeElement as HTMLElement;setOperation(op);setTarget(index===undefined?'':String(index));setSourceId('');setCount(op.blockId?rows.filter((r:any)=>r.block?.id===op.blockId).length:1);setCompact(false);setError('');};
 const close=()=>{setOperation(null);returnFocus.current?.focus();};
 const source=book?.sources.find(s=>s.id===sourceId),block=book?.plan.blocks.find(b=>b.id===operation?.blockId);
 const affected=rows.filter((r:any)=>r.block?.id===block?.id);
 const action=operation?{...operation,otherId:sourceId,blockId:operation.type==='fill-hole'?sourceId:operation.blockId,target:target===''?undefined:Number(target),sourceId,block:source?{...source,pages:count,uncertain:false}:undefined,count,compact}:null;
 let preview:Plan|null=null,previewError='';
 if(book&&action){try{preview=mutateFlatplan(book.plan,action);}catch(e:any){previewError=e.message;}}
 const destination=rows.find((r:any)=>r.index===Number(target));
 const changed=preview?flatplanRows(preview).filter((r:any)=>book?.plan.slots[r.index]!==preview!.slots[r.index]):[];
 const available=book?.sources.filter(s=>!s.cover&&!book.plan.slots.includes(s.id))||[];
 const commit=async()=>{if(!preview||!action||busy)return;setBusy(true);setError('');try{const response=await apiClient.patch(endpoint,{version:book?.version,action:{type:action.type,blockId:action.blockId,otherId:action.otherId,target:action.target,sourceId,count,compact}});setBook(response.data);close();}catch(e:any){setError(e.response?.data?.message||e.message);}finally{setBusy(false);}};
 const visible=rows.filter((r:any)=>Object.entries(filters).every(([field,text])=>String(field==='page'?r.label:field==='account'?r.block?.account||'Libre':field==='type'?r.block?.type||'Libre':description(r)+' '+(r.block?.detail||'')).toLocaleLowerCase('es').includes(text.toLocaleLowerCase('es'))));
 const pick=(index:number)=>{setSelected(index);document.getElementById(`flatplan-row-${index}`)?.scrollIntoView({block:'nearest',behavior:'smooth'});};
 if(!book)return <div className="mt-6" role={error?'alert':'status'}>{error||'Preparando planillo previo…'}</div>;
 return <section className="mt-6">
  <div className="flex flex-wrap items-center gap-3"><PublishFlatplan id={magazineId} version={book.version}/><h2 className="text-xl font-semibold">Planillo previo · {rows.length} páginas físicas</h2><button className={button} onClick={()=>open({type:'add'})} disabled={!available.length}>Añadir contenido ({available.length})</button><button className={button} onClick={()=>open({type:'insert-empty'})}>Añadir página</button></div>
  <p className="mt-3 text-sm text-slate-600">La numeración es Portada, Interior portada, 1, 2, 3… Los destinos también usan páginas de revista. La portada está a la derecha; la última página, a la izquierda. Rojo significa espacio libre. Los contenidos de varias páginas se gestionan completos.</p>
  <p className="mt-2 text-sm text-slate-600">Inicio por recepción de materiales; sin fecha, se usa el orden de la hoja importada. Sumario e índice se reservan inicialmente en las páginas 3 y 5 y pueden desplazarse al reorganizar contenidos. Este planillo previo no modifica la contratación ni borra contenidos.</p>
  {error&&<p role="alert" className="mt-3 rounded bg-red-50 p-3 text-red-800">{error}</p>}
  <div className="mt-5 flex flex-col items-start gap-6 lg:flex-row">
   <aside aria-label="Miniatura del planillo" className="w-64 shrink-0 rounded border bg-white p-3">
    {Array.from({length:Math.ceil((rows.length+1)/2)},(_,spread)=>{const left=spread*2-1,right=spread*2;return <div key={spread} className="mb-2 grid grid-cols-2 gap-1">{[left,right].map(index=>{const row=rows[index];return row?<button key={index} onClick={()=>pick(index)} title={`${row.label}: ${description(row)}`} aria-label={`${row.label}: ${description(row)}`} className={`h-28 cursor-pointer overflow-hidden rounded border p-2 text-left text-[10px] transition hover:ring-2 hover:ring-blue-400 ${selected===index?'ring-2 ring-blue-800':''} ${!row.block?'border-red-300 bg-red-100':row.block.type==='Artículo'?'bg-emerald-50':row.block.type==='Anuncio'?'bg-blue-50':'bg-slate-100'}`}><strong className="block">{row.label}</strong><span className="mt-2 block">{description(row)}</span></button>:<span key={index} aria-hidden="true" className="invisible h-28"/>;})}</div>;})}
   </aside>
   <div className="min-w-0 flex-1 overflow-x-auto rounded border bg-white"><TableFilters>{[['page','Página'],['account','Cuenta'],['type','Tipo'],['detail','Detalle']].map(([field,label])=><div key={field}><label className="block text-xs font-extralight text-gray-600"><span className="mb-1 block">{label}</span><input aria-label={`Filtrar ${label}`} value={filters[field]||''} onChange={e=>setFilters({...filters,[field]:e.target.value})} className="mt-2 w-full min-w-24 rounded border p-2"/></label></div>)}</TableFilters><SortableTable className="w-full text-left text-sm"><thead><tr>{[['page','Página'],['account','Cuenta'],['type','Tipo'],['detail','Detalle']].map(([field,label])=><th key={field} className="border-b p-3 align-top">{label}</th>)}<th className="border-b p-3">Desplazar / gestionar</th></tr></thead><tbody>{visible.map((row:any)=><tr id={`flatplan-row-${row.index}`} key={row.index} className={`${selected===row.index?'bg-blue-100':row.block?'':'bg-red-50'} border-b`}><td className="whitespace-nowrap p-3">{row.label}</td><td className="p-3">{row.block?.account||'—'}</td><td className="p-3">{row.block?.type||'Libre'}</td><td className="min-w-64 p-3"><strong className="block font-medium">{description(row)}</strong><span className="block text-slate-600">{row.block?.detail}</span>{row.block?.uncertain&&<span className="block text-amber-800">Extensión por confirmar: {row.total} página(s) provisional(es).</span>}{row.block?.sourceNote&&<span className="block text-xs text-slate-500">{row.block.sourceNote}{row.block.arrival?` · ${new Date(row.block.arrival).toLocaleString('es-ES')}`:''}</span>}</td><td className="p-3"><div className="flex flex-wrap gap-2">{row.block&&row.block.id!=='cover'?<><button className={button} onClick={()=>open({type:'move',blockId:row.block.id})}>Mover bloque</button>{row.total===1&&['Anuncio','Artículo'].includes(row.block.type)&&<button className={button} onClick={()=>open({type:'swap',blockId:row.block.id})}>Intercambiar por</button>}<button className={button} onClick={()=>open({type:'remove',blockId:row.block.id})}>Quitar bloque</button>{row.block.contentId&&<button className={button} onClick={()=>open({type:'resize',blockId:row.block.id})}>Páginas</button>}</>:!row.block?<><button className={button} onClick={()=>open({type:'fill-hole'},row.index)}>Asignar contenido</button><button className={button} onClick={()=>open({type:'remove-empty'},row.index)}>Retirar página libre</button></>:<span className="text-xs text-slate-500">Cubierta fija</span>}</div></td></tr>)}{!visible.length&&<tr><td colSpan={5} className="p-5">Sin páginas que coincidan con los filtros.</td></tr>}</tbody></SortableTable></div>
  </div>
  {operation&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 p-4"><div ref={dialog} tabIndex={-1} role="dialog" aria-modal="true" aria-labelledby="flatplan-dialog-title" className="max-h-[90vh] w-full max-w-2xl overflow-y-auto rounded bg-white p-6 shadow-xl"><div className="flex items-center justify-between gap-4"><h3 id="flatplan-dialog-title" className="text-xl font-semibold">{operation.type==='swap'?'Intercambiar por':operation.type==='fill-hole'?'Asignar contenido a la página libre':operation.type==='move'?'Desplazar contenido':operation.type==='remove'?'Quitar contenido del planillo':operation.type==='add'?'Añadir contenido':operation.type==='resize'?'Extensión del contenido':operation.type==='remove-empty'?'Retirar página libre':'Insertar página libre'}</h3><button aria-label="Cerrar modal" className={button} onClick={close}>×</button></div>
   {block&&<div className="mt-4 rounded bg-slate-100 p-3"><strong>{block.account} · {block.type}</strong><p>{block.detail}</p><p className="mt-2">{affected.length===1?'Es una sola página.':`Es un bloque indivisible de ${affected.length} páginas; la operación afecta a todas.`}</p><p>Páginas: {affected.map((r:any)=>r.label).join(', ')}.</p></div>}
   {operation.type==='add'&&<div className="mt-4"><label className="mb-1 block text-sm">Contenido de la hoja / redacción</label><SearchableSelect label="Contenido a añadir" options={available.map(s=>({value:s.id,label:`${s.account} · ${s.type} · ${s.detail}`}))} value={sourceId} onChange={value=>{setSourceId(value);setCount(book.sources.find(s=>s.id===value)?.pages||1);}} required/></div>}
   {['swap','fill-hole'].includes(operation.type)&&<div className="mt-4"><label className="mb-1 block text-sm">{operation.type==='swap'?'Contenido de una página con el que intercambiar':'Contenido ya colocado que quieres traer a este hueco'}</label><SearchableSelect label="Contenido de la misma revista" value={sourceId} onChange={setSourceId} required options={rows.filter((r:any)=>r.part===1&&r.block.id!=='cover'&&r.block.id!==operation.blockId&&['Anuncio','Artículo'].includes(r.block.type)&&(operation.type!=='swap'||r.total===1)).map((r:any)=>({value:r.block.id,label:`${r.block.account} · ${r.block.type} · pág. ${r.label} · ${r.total} página(s) · ${r.block.detail}`,disabled:operation.type==='fill-hole'&&(book.plan.slots.slice(Number(target),Number(target)+r.total).length!==r.total||book.plan.slots.slice(Number(target),Number(target)+r.total).some(Boolean)||(r.total===2&&(Number(target)+1)%2!==0))}))}/>
    {operation.type==='swap'?<p className="mt-3 text-sm">Se intercambian únicamente las dos posiciones. El resto de la revista permanece igual.</p>:<fieldset className="mt-3 space-y-2"><legend className="font-medium">Qué hacer con el origen del contenido:</legend><label className="block cursor-pointer rounded p-2 hover:bg-slate-50"><input type="radio" checked={!compact} onChange={()=>setCompact(false)}/> Dejar su origen vacío en rojo; no mover el resto.</label><label className="block cursor-pointer rounded p-2 hover:bg-slate-50"><input type="radio" checked={compact} onChange={()=>setCompact(true)}/> Cubrir su origen en cascada con contenidos posteriores de una página.</label><p className="text-sm text-slate-600">Los bloques de varias páginas se mantienen completos y en su posición. Si no queda contenido de una página que pueda avanzar, el hueco debe permanecer.</p><button className={button} onClick={()=>open({type:'remove-empty'},Number(target))}>Cerrar este hueco en cascada sin asignar contenido</button></fieldset>}
   </div>}
   {['add','resize'].includes(operation.type)&&<label className="mt-4 block">Páginas del bloque<input type="number" min={1} max={100} value={count} onChange={e=>setCount(Number(e.target.value))} className="ml-3 w-24 rounded border p-2"/></label>}
   {['move','add','insert-empty'].includes(operation.type)&&<div className="mt-4"><label className="mb-1 block text-sm">Primera página de revista de destino{operation.type==='insert-empty'?' (se inserta antes)':''}</label><SearchableSelect label="Primera página de revista de destino" options={rows.filter((r:any)=>r.index>0).map((r:any)=>({value:String(r.index),label:`${r.index===1?'Interior portada':'Pág. revista '+flatplanMagazinePageLabel(r.index)} · ${description(r)}`,disabled:(!!r.block&&r.part!==1)||((operation.type==='move'?['Anuncio','Artículo'].includes(block?.type||'')&&affected.length===2:operation.type==='add'?['Anuncio','Artículo'].includes(source?.type||'')&&count===2:false)&&(r.index+1)%2!==0)}))} value={target} onChange={setTarget} required/>{target!==''&&destination&&<p className="mt-3 rounded bg-blue-50 p-3">{description(destination)}. {destination.total>1?`Este bloque empieza en ${rows[destination.index-destination.part+1].label} y acaba en ${rows[destination.index-destination.part+destination.total].label}. `:''}{operation.type==='insert-empty'?'Se inserta una página libre y se desplaza lo posterior hacia adelante.':preview&&book.plan.slots.slice(Number(target),Number(target)+(operation.type==='move'?affected.length:count)).every(id=>!id)?'Hay espacio libre suficiente: lo posterior conserva su posición.':'Se inserta el bloque y se desplaza lo posterior hacia adelante, sin partir contenidos.'}{operation.type==='move'?' El origen queda libre.':''}</p>}</div>}
   {operation.type==='remove-empty'&&<p className="mt-4">Se cubre el hueco de la página {destination?.label} con el siguiente contenido completo de una página, y se repite desde su origen. Los bloques de varias páginas conservan su posición. Los huecos finales se retiran hasta donde permiten las parejas de páginas.</p>}
   {operation.type==='remove'&&<fieldset className="mt-4 space-y-2"><legend className="font-medium">Al quitar todas estas páginas del contenido:</legend><label className="block cursor-pointer rounded p-2 hover:bg-slate-50"><input type="radio" checked={!compact} onChange={()=>setCompact(false)}/> Dejar los espacios vacíos, marcados en rojo.</label><label className="block cursor-pointer rounded p-2 hover:bg-slate-50"><input type="radio" checked={compact} onChange={()=>setCompact(true)}/> Adelantar lo posterior {affected.length} página(s).</label><p className="text-sm text-slate-600">El contenido seguirá existiendo y podrás volver a añadirlo.</p></fieldset>}
   {preview&&<div className="mt-4 rounded border p-3"><p>Revista: {book.plan.slots.length} → {preview.slots.length} páginas físicas.</p>{preview.slots.length%2===0&&Math.abs(preview.slots.length-book.plan.slots.length)%2===0&&<p className="text-sm text-slate-600">Los anuncios y artículos de dos páginas conservan la pareja par/impar consecutiva. Si un desplazamiento cambia esa orientación, se intercala un hueco antes del contenido. Se mantiene también un total par.</p>}<details className="mt-2"><summary className="cursor-pointer rounded hover:bg-blue-50">Ver páginas afectadas ({changed.length})</summary><ul className="mt-2 space-y-1 text-sm">{changed.map((r:any)=><li key={r.index}>{r.label}: {description(rows[r.index]||{index:r.index})} → {description(r)}</li>)}{preview.slots.length<book.plan.slots.length&&<li>Se retiran {book.plan.slots.length-preview.slots.length} posiciones finales del planillo.</li>}</ul></details></div>}
   {previewError&&<p className="mt-3 text-sm text-amber-800">{previewError}</p>}{error&&<p role="alert" className="mt-3 text-red-800">{error}</p>}
   <div className="mt-5 flex justify-end gap-3"><button className={button} onClick={close}>Cancelar</button><button className={`${button} bg-blue-950 text-white enabled:hover:bg-blue-800`} disabled={!preview||busy} onClick={commit}>{busy?'Guardando…':'Confirmar cambio'}</button></div>
  </div></div>}
 </section>;
}
