'use client';
import {useEffect,useState} from 'react';
import apiClient from '@/app/apiClient';
export default function PublishFlatplan({id,version}:{id:string;version:number}){
  const [preview,setPreview]=useState<any>(null),[busy,setBusy]=useState(false),[error,setError]=useState('');
  useEffect(()=>{const close=(event:KeyboardEvent)=>{if(event.key==='Escape')setPreview(null);};window.addEventListener('keydown',close);return()=>window.removeEventListener('keydown',close);},[]);
  async function send(confirm=false){setBusy(true);setError('');try{const r=await apiClient.post(`/api/v1/produccion/gestiones-produccion/${encodeURIComponent(id)}/publicar-planillo`,{version,confirm});setPreview(r.data);if(confirm)window.dispatchEvent(new Event('p3:flatplan-published'));}catch(e:any){setError(e.message);}finally{setBusy(false);}}
  return <><button type="button" disabled={busy} onClick={()=>void send()} className="cursor-pointer rounded border px-4 py-2 hover:bg-blue-50 disabled:cursor-not-allowed disabled:opacity-50">Publicar asignaciones definitivas</button>{error&&<p role="alert" className="text-red-700">{error}</p>}{preview&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-black/60 p-4"><section role="dialog" aria-modal="true" aria-label="Publicar planillo" className="max-h-[90vh] w-full max-w-xl overflow-auto rounded bg-white p-6"><header className="flex justify-between"><h3 className="font-semibold">Publicar planillo · versión {version}</h3><button type="button" onClick={()=>setPreview(null)} className="cursor-pointer rounded px-3 text-2xl hover:bg-blue-50" aria-label="Cerrar">×</button></header><p className="my-4">Se sustituirán {preview.before.length} asignaciones definitivas por {preview.after.length} páginas con contenido. Quedan {preview.emptyPages} páginas libres. La contratación y los contenidos se conservan. Esta versión queda archivada.</p><table className="my-3 w-full border-collapse text-sm"><thead><tr><th className="p-2 text-left">Pagina</th><th className="p-2 text-left">Antes</th><th className="p-2 text-left">Despues</th></tr></thead><tbody>{[...new Set<number>([...preview.before,...preview.after].map((row:any)=>Number(row.numero_pagina)))].sort((a,b)=>a-b).map(page=>{const before=preview.before.find((row:any)=>Number(row.numero_pagina)===page),after=preview.after.find((row:any)=>Number(row.numero_pagina)===page),changed=before?.contenido_id!==after?.contenido_id||before?.pagina_del_contenido!==after?.pagina_del_contenido;return <tr key={page} className={changed?'border-t bg-amber-50':'border-t'}><th className="p-2 text-left">{page===-1?'Portada':page===0?'Interior portada':page}</th><td className="p-2">{before?before.contenido_id+' / '+before.pagina_del_contenido:'Libre'}</td><td className="p-2">{after?(after.label||after.contenido_id)+' / '+after.pagina_del_contenido:'Libre'}</td></tr>;})}</tbody></table>{preview.published?<p role="status" className="text-green-800">Asignaciones definitivas publicadas.</p>:<button disabled={busy} type="button" onClick={()=>void send(true)} className="cursor-pointer rounded bg-blue-950 px-4 py-2 text-white hover:bg-blue-800 disabled:cursor-not-allowed disabled:opacity-50">Confirmar publicación</button>}</section></div>}</>;
}
