'use client';
import {useEffect,useState} from 'react';
import SearchableSelect from '@/app/components/SearchableSelect';
import {api,button,date,ForecastItems,input,money} from '@/app/dashboard/administracion/tarjetas/CardComponents';
export default function CardSettlementModal({lines,close,done}:{lines:any[];close:()=>void;done:()=>void}){
  const [cards,setCards]=useState<any[]>([]),[card,setCard]=useState(''),[preview,setPreview]=useState<any>(null),[comment,setComment]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);
  useEffect(()=>{api('/api/v1/admin/tarjetas').then(setCards).catch(e=>setError(e.message));},[]);
  useEffect(()=>{const fn=(e:KeyboardEvent)=>{if(e.key==='Escape')close();};window.addEventListener('keydown',fn);return()=>window.removeEventListener('keydown',fn);},[close]);
  const submit=async(confirm=false)=>{if(busy)return;setBusy(true);setError('');try{const d=await api('/api/v1/direccion/bancos/liquidacion-tarjeta',{id_tarjeta:card,ids:lines.map(l=>l.id_linea_banco),action:confirm?'confirm':'preview',token:preview?.token,comentario:comment});if(confirm)done();else setPreview(d);}catch(e:any){setPreview(null);setError(e.message);}finally{setBusy(false);}};
  return <div className="fixed inset-0 z-50 overflow-y-auto bg-black/60 p-4"><section role="dialog" aria-modal="true" aria-label="Liquidación tarjeta" className="mx-auto my-6 max-w-4xl space-y-4 rounded bg-white p-6 text-slate-900"><header className="flex justify-between"><h2 className="text-xl font-semibold">Liquidación tarjeta</h2><button className={`${button} text-xl`} aria-label="Cerrar" onClick={close}>×</button></header><p>Los {lines.length} movimientos seleccionados se aplicarán a una misma liquidación. Importe: {money(lines.reduce((n,l)=>n+Math.abs(Number(l.importe)),0))}.</p><SearchableSelect label="Tarjeta a liquidar" disabled={busy} value={card} onChange={v=>{setCard(v);setPreview(null);setComment('');}} options={cards.filter(c=>c.estado==='activa'&&c.proxima_liquidacion&&lines.every(l=>l.banco===c.banco&&Number(l.importe)<0)).map(c=>({value:c.id_tarjeta,label:`${c.codigo} · ${c.nombre} · ${c.banco} · ${date(c.proxima_liquidacion)}`}))}/><button className={button} disabled={busy||!card} onClick={()=>submit()}>Revisar previsión actual</button>{error&&<p role="alert" className="text-red-700">{error}</p>}{preview&&<><h3 className="font-semibold">Liquidación del {date(preview.fecha)}</h3><p>Período: {date(preview.inicio)} — {date(preview.cierre)}.</p><ForecastItems items={preview.items}/><div className="rounded bg-blue-50 p-4">Previsto: {money(preview.total)} · Banco: {money(preview.real)} · Diferencia: {money(preview.diferencia)}</div><label className="block">{preview.diferencia?'Motivo de la diferencia (obligatorio)':'Comentario'}<textarea className={input} maxLength={10000} disabled={busy} value={comment} onChange={e=>setComment(e.target.value)}/></label><p>Al confirmar se guardará este desglose, se marcarán los movimientos como revisados y la tarjeta avanzará al siguiente período según su periodicidad.</p><button className={button} disabled={busy||preview.diferencia!==0&&!comment.trim()} onClick={()=>submit(true)}>{busy?'Guardando…':'Confirmar liquidación'}</button></>}</section></div>;
}
