'use client';
import {useEffect,useState} from 'react';
import Link from 'next/link';
import {api,button,date,ForecastItems,money} from '@/app/dashboard/administracion/tarjetas/CardComponents';
export default function CardBankReview({id,done}:{id:string;done:()=>void}){
  const [data,setData]=useState<any>(null),[confirm,setConfirm]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('');
  useEffect(()=>{api(`/api/v1/direccion/bancos/liquidacion-tarjeta?id=${encodeURIComponent(id)}`).then(setData).catch(e=>setError(e.message));},[id]);
  useEffect(()=>{const fn=(e:KeyboardEvent)=>{if(e.key==='Escape')setConfirm(false);};window.addEventListener('keydown',fn);return()=>window.removeEventListener('keydown',fn);},[]);
  const reopen=async()=>{if(busy)return;setBusy(true);setError('');try{await api('/api/v1/direccion/bancos/revision',{action:'unreview',ids:data.movimientos},'PUT');done();}catch(e:any){setConfirm(false);setError(e.message);}finally{setBusy(false);}};
  return <section className="space-y-4 rounded bg-white p-6 text-slate-900"><h1 className="text-xl font-semibold">Liquidación de tarjeta revisada</h1>{error&&<p role="alert" className="text-red-700">{error}</p>}{data?<><Link className="cursor-pointer text-blue-900 underline hover:text-blue-600" href={`/dashboard/administracion/tarjetas/${encodeURIComponent(data.id_tarjeta)}`}>{data.detalle.card.codigo} · {data.detalle.card.nombre}</Link><p>Liquidación: {date(data.fecha)}. Previsto: {money(data.previsto)}. Cargo bancario: {money(data.real)}.</p><p>{data.comentario}</p><ForecastItems items={data.detalle.items}/><button className={button} onClick={()=>setConfirm(true)}>Reabrir liquidación</button></>:!error&&<p>Cargando liquidación…</p>}{confirm&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-black/60 p-4"><section role="dialog" aria-modal="true" aria-label="Reabrir liquidación" className="max-w-xl space-y-4 rounded bg-white p-6"><header className="flex justify-between"><h2 className="font-semibold">Reabrir liquidación</h2><button className={`${button} text-xl`} aria-label="Cerrar" onClick={()=>setConfirm(false)}>×</button></header><p>Se marcarán como pendientes sus {data.movimientos.length} movimientos. Este período volverá a ser la próxima liquidación de la tarjeta. Solo se permite reabrir la última liquidación.</p><button className={button} disabled={busy} onClick={reopen}>{busy?'Guardando…':'Confirmar reapertura'}</button></section></div>}</section>;
}
