'use client';
import {useEffect,useState} from 'react';
import JuanProviderSteps from './JuanProviderSteps';
import JuanAddRow from './JuanAddRow';
import Link from 'next/link';
export type JuanAssociation={bank:string;row_id:string;status:string;provider_id?:string|null;provider_name:string|null;employee_name:string|null;charge_ids:string[];evidence:{reason:string;conflicts:{type:string;month?:number;juan:number|string;erp:number|string}[];candidates:{id:string;name:string}[]}};
export type JuanCharge={id_cargo_recurrente:string;tipo_cargo:string;tipo_programacion?:string;id_proveedor?:string;id_tarjeta?:string;banco_pago?:string;nombre_proveedor:string;nombre_agente:string;vencimientos?:{id:string;fecha:string;importe:number;descripcion:string}[];programacion:{total_iva:number;descripcion?:string;mes?:number|string;dia?:number|string;anio?:number|string;cada?:number|string;unidad?:string;inicio_dia?:number|string;inicio_mes?:number|string;inicio_anio?:number|string;importes_por_fecha?:Record<string,number>}[]};
type Order={id_orden:string;banco_cobro:string;cobro_total:string;pending_amount?:string;fecha_teorica_cobro:string;forma_cobro:string;datos_importacion?:{cliente?:string}};
const money=(value:number)=>(value/100).toLocaleString('es-ES',{style:'currency',currency:'EUR'});
const button='rounded border px-3 py-2 enabled:cursor-pointer enabled:hover:bg-blue-100 disabled:cursor-default disabled:opacity-50';
export default function JuanRowDetails({year=2026,bank,rowId,label,section,budgets,associations,charges,orders,version,onSaved,onClose,day,recurring}:{year?:number;bank:string;rowId:string;label:string;section:'income'|'payments';budgets:(number|null)[];associations:JuanAssociation[];charges:JuanCharge[];orders:Order[];version:number;onSaved:()=>Promise<void>;onClose:()=>void;day?:number|null;recurring?:{total_iva:number;cada:number;unidad:string;inicio_dia:number;inicio_mes:number;inicio_anio:number}}) {
 const [phase,setPhase]=useState<'details'|'provider'|'remove'|'charge'>('details'),[busy,setBusy]=useState(false),[error,setError]=useState('');
 useEffect(()=>{const close=(event:KeyboardEvent)=>{if(event.key==='Escape'&&!event.defaultPrevented)onClose();};window.addEventListener('keydown',close);return()=>window.removeEventListener('keydown',close);},[onClose]);
 const association=associations.find(a=>a.bank===bank&&a.row_id===rowId);
 const linked=charges.filter(c=>association?.charge_ids.includes(String(c.id_cargo_recurrente))||label.includes('· SUSCRIPCIONES')&&c.id_tarjeta&&c.banco_pago===bank);
 const payroll=Boolean(association?.employee_name)||linked.some(c=>c.tipo_cargo==='nomina'),grouped=/^(?:VISAS?\b|TARJETAS?\b|TRASPASOS?\b)|\bEFECTIVO\b/i.test(label);
 const incomeOrders=section==='income'&&/PREVISTAS DE COBRO/.test(label)?orders.filter(o=>o.banco_cobro===bank&&(/REMESAS/.test(label)?/recibo|remesa/i.test(o.forma_cobro||''):/TRANSFERENCIAS/.test(label)?/transfer|transf/i.test(o.forma_cobro||''):!/recibo|remesa|transfer|transf/i.test(o.forma_cobro||''))):[];
 const remove=async()=>{setBusy(true);setError('');try{const r=await fetch('/api/v1/direccion/prevision-liquidez/vista-juan/fila',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'remove-row',year,version,bank,rowId,section})});const body=await r.json();if(!r.ok)throw Error(body.message);await onSaved();onClose();}catch(e){setError(e instanceof Error?e.message:'No se pudo retirar.');}finally{setBusy(false);}};
 return <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/40 p-4"><section role="dialog" aria-modal="true" aria-label={`Desglose de ${label}`} className="relative max-h-[90vh] w-full max-w-3xl overflow-auto rounded-xl bg-white p-6 text-slate-900 shadow-xl">
  <button type="button" disabled={busy} onClick={onClose} aria-label="Cerrar desglose" className="absolute right-3 top-2 rounded px-3 py-1 text-2xl enabled:cursor-pointer enabled:hover:bg-slate-100 disabled:cursor-default">×</button>
  <h2 className="pr-8 text-lg font-semibold">{bank} · {label}</h2>
  {error&&<p role="alert" className="my-3 text-red-800">{error}</p>}
  {phase==='provider'&&<JuanProviderSteps year={year} bank={bank} rowId={rowId} version={version} providerId={association?.provider_id||linked[0]?.id_proveedor} onBack={()=>setPhase('details')} onSaved={onSaved}/>}
  {phase==='charge'&&<><JuanAddRow embedded year={year} bank={bank} section={section} rowId={rowId} initialLabel={label} initialDay={day} initialAmount={budgets.find(v=>(v||0)>0)} initialMonth={budgets.findIndex(v=>(v||0)>0)>=0?budgets.findIndex(v=>(v||0)>0)+1:year===2026?10:1} initialProvider={association?.provider_id?{id_proveedor:association.provider_id,nombre_proveedor:association.provider_name||''}:null} version={version} charges={charges} onSaved={onSaved} onClose={()=>setPhase('details')}/><button className={`${button} mt-3`} onClick={()=>setPhase('details')}>Volver al desglose</button></>}
  {phase==='remove'&&<div className="mt-4 rounded border p-4"><h3 className="font-semibold">Retirar las previsiones de esta fila en {year}</h3><p className="my-3 text-sm">Se quitarán los importes previstos de los meses abiertos de este año, también de sus vencimientos asociados en el ERP. Se conservan los realizados, los meses cerrados y la ficha del cargo. Para quitar solo un mes, borra su importe en la hoja.</p><div className="flex gap-2"><button className={button} disabled={busy} onClick={()=>{void remove();}}>Retirar previsiones de {year}</button><button className={button} disabled={busy} onClick={()=>setPhase('details')}>Volver al desglose</button></div></div>}
  {phase==='details'&&<>
   <div className="my-4 flex flex-wrap items-center gap-3"><p className="text-sm">{payroll?'Empleado:':'Proveedor:'} <strong>{association?.employee_name||association?.provider_name||linked[0]?.nombre_proveedor||'Pendiente de identificar'}</strong></p>{section==='payments'&&!payroll&&!grouped&&<button className={button} onClick={()=>setPhase('provider')}>{association?.provider_id?'Buscar o modificar proveedor':'Añadir proveedor'}</button>}</div>
   {association?.status==='projected'&&<p className="my-3 text-sm text-amber-800">Base del año anterior: falta revisar y confirmar los cargos de este año.</p>}
   <h3 className="mb-3 font-semibold">{section==='payments'?'Cargos recurrentes asociados':'Previsiones de ingreso asociadas'}</h3>
   {linked.map(charge=><article key={charge.id_cargo_recurrente} className="mb-3 rounded border border-slate-300 p-4">
    <h4 className="font-semibold">{charge.programacion[0]?.descripcion||charge.nombre_proveedor||charge.nombre_agente||`Cargo ${charge.id_cargo_recurrente}`}</h4>
    <p className="mt-1 text-sm">{charge.tipo_cargo==='nomina'?'Nómina':'Proveedor'}: {charge.nombre_agente||charge.nombre_proveedor} · Banco: {charge.banco_pago||'pendiente'}</p>
    {charge.programacion.map((rule,index)=><div key={index} className="mt-3 text-sm"><p><strong>{money(Math.round(Number(rule.total_iva)*100))}</strong>{rule.descripcion?` · ${rule.descripcion}`:''}</p><p>{charge.tipo_programacion==='fechas'?`Vencimiento: ${rule.dia}/${rule.mes}/${rule.anio||year}`:`Frecuencia: cada ${rule.cada||1} ${rule.unidad||'meses'} · primer vencimiento: ${rule.inicio_dia||'—'}/${rule.inicio_mes||'—'}/${rule.inicio_anio||'—'}`}</p>{rule.importes_por_fecha&&<p className="mt-1 text-slate-600">Ajustes de vencimientos: {Object.entries(rule.importes_por_fecha).map(([date,amount])=>`${date.split('-').reverse().join('/')}: ${amount===0?'retirado':money(Math.round(amount*100))}`).join(' · ')}</p>}</div>)}
    <details className="mt-3 text-sm"><summary className="cursor-pointer rounded p-1 hover:bg-blue-50">Ver vencimientos de {year}</summary>{charge.vencimientos?.length?<ul className="mt-2 space-y-1">{charge.vencimientos.map(d=><li key={d.id}>{d.fecha.split('-').reverse().join('/')} · {money(Math.round(Number(d.importe)*100))} · {d.descripcion}</li>)}</ul>:<p className="mt-2">{charge.tipo_cargo==='nomina'?'La previsión mensual se calcula desde la programación de nómina.':'No hay vencimientos previstos de este cargo en el periodo de la pestaña.'}</p>}</details>
    <Link target="_blank" rel="noopener noreferrer" href={`/dashboard/direccion/tesoreria/prevision-liquidez/${charge.id_cargo_recurrente}`} className="mt-3 inline-block cursor-pointer rounded px-2 py-1 text-sm text-blue-900 hover:bg-blue-100 hover:underline">Abrir ficha del cargo para revisar su programación</Link>
   </article>)}
   {!linked.length&&<p className="my-3 rounded bg-slate-50 p-3 text-sm">{section==='income'?'Presupuesto de cobros. Las órdenes del Control administrativo aportan los ingresos concretos.':grouped?'Presupuesto agrupado. Los servicios identificados aparecerán aquí como cargos; el gasto variable se edita en la hoja.':'Todavía no hay cargo recurrente asociado. Puedes identificar su proveedor; el presupuesto se conserva hasta vincular el cargo.'}</p>}
   {incomeOrders.length>0&&<ul className="my-3 space-y-2 text-sm">{incomeOrders.map(o=><li key={o.id_orden}>{o.datos_importacion?.cliente||o.id_orden} · {o.fecha_teorica_cobro} · {money(Math.round(Number(o.pending_amount??o.cobro_total)*100))}</li>)}</ul>}
   {section==='income'&&<div className="my-3 text-sm"><p>Órdenes pendientes: {money(incomeOrders.reduce((n,o)=>n+Math.round(Number(o.pending_amount??o.cobro_total)*100),0))}.</p><p>Parte del presupuesto todavía sin órdenes: {money(Math.max(0,budgets.reduce<number>((n,v)=>n+(v||0),0)-incomeOrders.reduce((n,o)=>n+Math.round(Number(o.pending_amount??o.cobro_total)*100),0)))}.</p><p className="mt-2 font-semibold">Total previsto: {money(budgets.reduce<number>((n,v)=>n+(v||0),0))}.</p></div>}
   {recurring&&<p className="my-3 text-sm">Ingreso recurrente: {money(Math.round(recurring.total_iva*100))} cada {recurring.cada} {recurring.unidad}, desde {recurring.inicio_dia}/{recurring.inicio_mes}/{recurring.inicio_anio}.</p>}
   {section==='payments'&&!linked.length&&!grouped&&<button className={button} onClick={()=>setPhase('charge')}>Vincular o preparar cargo recurrente</button>}
   {association?.evidence?.reason&&<p className="my-3 text-sm text-slate-600">{association.evidence.reason}</p>}
   {association&&!association.charge_ids.length&&association.status!=='group'&&<p className="my-2 text-sm text-amber-800">El importe pertenece al presupuesto del ERP. Su proveedor, contrato o desglose fiscal puede completarse sin crear otra previsión.</p>}
   <p className="my-3 text-sm">Los importes de cada mes se editan directamente en la hoja. Cambiar un mes ajusta ese vencimiento; la frecuencia y los demás meses se conservan.</p>
   {!grouped&&!/^SALDO/.test(label)&&<button className={button} onClick={()=>setPhase('remove')}>Retirar previsiones de esta fila</button>}
  </>}
 </section></div>;
}
