'use client';
import {useEffect,useState} from 'react';
import SearchableSelect from '@/app/components/SearchableSelect';
import JuanProviderSteps from './JuanProviderSteps';
import {type JuanCharge} from './JuanRowDetails';
import ForecastVatFields from './ForecastVatFields';
import {forecastVat} from '@/app/lib/forecastVat';
const button='rounded border px-3 py-2 enabled:cursor-pointer enabled:hover:bg-blue-100 disabled:cursor-default disabled:opacity-50';
export default function JuanAddRow({year,bank,section,version,charges,onSaved,onClose,rowId,initialLabel='',initialProvider=null,initialAmount,initialDay,initialMonth,embedded=false}:{year:number;bank:string;section:'income'|'payments';version:number;charges:JuanCharge[];onSaved:()=>Promise<void>;onClose:()=>void;rowId?:string;initialLabel?:string;initialProvider?:{id_proveedor:string;nombre_proveedor:string}|null;initialAmount?:number|null;initialDay?:number|null;initialMonth?:number;embedded?:boolean}) {
 const [step,setStep]=useState(1),[label,setLabel]=useState(initialLabel),[mode,setMode]=useState('new'),[chargeId,setChargeId]=useState(''),[provider,setProvider]=useState<{id_proveedor:string;nombre_proveedor:string}|null>(initialProvider),[employeeId,setEmployeeId]=useState(''),[employees,setEmployees]=useState<{id_agente:string;nombre:string}[]>([]),[providerStep,setProviderStep]=useState(false),[amount,setAmount]=useState(initialAmount?String(initialAmount/100).replace('.',','):''),[every,setEvery]=useState('1'),[dd,setDd]=useState(initialDay?String(initialDay):''),[mm,setMm]=useState(String(initialMonth||(year===2026?10:1)).padStart(2,'0')),[yyyy,setYyyy]=useState(String(year)),[busy,setBusy]=useState(false),[error,setError]=useState('');
 useEffect(()=>{const close=(e:KeyboardEvent)=>{if(e.key==='Escape'&&!e.defaultPrevented)onClose();};window.addEventListener('keydown',close);const controller=new AbortController();if(section==='payments')void fetch('/api/v1/direccion/prevision-liquidez/vista-juan/fila',{signal:controller.signal}).then(async r=>{const b=await r.json();if(!r.ok)throw Error(b.message);setEmployees(b);}).catch(e=>{if(e.name!=='AbortError')setError(e.message);});return()=>{window.removeEventListener('keydown',close);controller.abort();};},[onClose,section]);
 const chosen=charges.find(c=>String(c.id_cargo_recurrente)===chargeId);
 const next=()=>{setError('');if(!label.trim()){setError('Indica el concepto.');return;}if(section==='payments'&&mode==='existing'&&!chosen){setError('Selecciona un cargo existente.');return;}if(section==='payments'&&mode==='new'&&!provider){setError('Busca o crea el proveedor.');return;}if(section==='payments'&&mode==='payroll'&&!employeeId){setError('Selecciona el empleado.');return;}setStep(mode==='existing'?3:2);};
 const [vatChoice,setVatChoice]=useState(''),[vatRate,setVatRate]=useState('');
 let vat:null|ReturnType<typeof forecastVat>=null;try{vat=mode==='payroll'?{total_iva:Number(amount.replace(',','.')),base_imponible:0,importe_iva:0,contains_iva:false,tipo_iva:0}:forecastVat(Number(amount.replace(',','.')),vatChoice===''?undefined:vatChoice==='yes',vatRate.replace(',','.'));}catch{}
 const rule={...vat,total_iva:Number(amount.replace(',','.')),cada:Number(every),unidad:'meses',inicio_dia:Number(dd),inicio_mes:Number(mm),inicio_anio:Number(yyyy)};
 const review=()=>{if(!vat){try{forecastVat(Number(amount.replace(',','.')),vatChoice===''?undefined:vatChoice==='yes',vatRate.replace(',','.'));}catch(e){setError(e instanceof Error?e.message:String(e));return;}}const date=new Date(Date.UTC(Number(yyyy),Number(mm)-1,Number(dd)));if(!Number.isFinite(rule.total_iva)||rule.total_iva<=0||!Number.isInteger(rule.cada)||rule.cada<1||rule.cada>120||date.getUTCFullYear()!==Number(yyyy)||date.getUTCMonth()!==Number(mm)-1||date.getUTCDate()!==Number(dd)){setError('Revisa el importe, la frecuencia y los tres campos de fecha.');return;}setError('');setStep(3);};
 const save=async()=>{setBusy(true);setError('');try{const r=await fetch('/api/v1/direccion/prevision-liquidez/vista-juan/fila',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({year,bank,section,version,label,rowId,existingChargeId:mode==='existing'?chargeId:null,tipo_cargo:mode==='payroll'?'nomina':'proveedor',providerId:provider?.id_proveedor,employeeId,rule})});const b=await r.json();if(!r.ok)throw Error(b.message);await onSaved();onClose();}catch(e){setError(e instanceof Error?e.message:'No se pudo guardar.');}finally{setBusy(false);}};
 return <div className={embedded?'':'fixed inset-0 z-50 flex items-center justify-center bg-black/40 p-4'}><section role={embedded?undefined:'dialog'} aria-modal={embedded?undefined:true} aria-label={`Añadir ${section==='payments'?'gasto':'ingreso'} recurrente`} className={embedded?'mt-4 rounded border p-4':'relative max-h-[90vh] w-full max-w-3xl overflow-auto rounded-xl bg-white p-6 text-slate-900 shadow-xl'}>
  {!embedded&&<button disabled={busy} onClick={onClose} aria-label="Cerrar" className="absolute right-3 top-2 rounded px-3 py-1 text-2xl enabled:cursor-pointer enabled:hover:bg-slate-100 disabled:cursor-default">×</button>}<h2 className="pr-8 text-lg font-semibold">{rowId?'Vincular o preparar':'Añadir'} {section==='payments'?'gasto':'ingreso'} recurrente · {bank} {year}</h2>
  <p className="my-3 text-sm">{step===1?'1. Concepto y destinatario':step===2?'2. Importe y frecuencia':'3. Revisar y guardar'}</p>
  {error&&<p role="alert" className="my-3 text-sm text-red-800">{error}</p>}
  {step===1&&<><label className="block text-sm">Concepto<input maxLength={300} className="mt-1 w-full rounded border p-2" value={label} onChange={e=>setLabel(e.target.value)}/></label>
   {section==='payments'&&<><div className="my-3 flex flex-wrap gap-2">{[['existing','Vincular cargo existente'],['new','Nuevo cargo con proveedor'],['payroll','Nómina de empleado']].map(([value,text])=><button key={value} className={`${button} ${mode===value?'bg-blue-100 font-semibold':''}`} onClick={()=>{setMode(value);setProviderStep(false);}}>{text}</button>)}</div>
    {mode==='existing'&&<SearchableSelect label="Cargo recurrente" value={chargeId} onChange={setChargeId} options={charges.filter(c=>c.banco_pago===bank).map(c=>({value:String(c.id_cargo_recurrente),label:`${c.nombre_proveedor||c.nombre_agente||'Cargo'} · ${c.programacion.map(r=>r.descripcion||Number(r.total_iva).toLocaleString('es-ES')+' €').join(' / ')}`}))}/>}
    {mode==='payroll'&&<SearchableSelect label="Empleado" value={employeeId} onChange={setEmployeeId} options={employees.map(e=>({value:e.id_agente,label:e.nombre}))}/>}
    {mode==='new'&&<><p className="my-3 text-sm">Proveedor: <strong>{provider?.nombre_proveedor||'sin seleccionar'}</strong></p>{providerStep?<JuanProviderSteps year={year} bank={bank} rowId="" version={version} providerId={provider?.id_proveedor} onSaved={onSaved} onBack={()=>setProviderStep(false)} onSelected={p=>{setProvider(p);setProviderStep(false);}}/>:<button className={button} onClick={()=>setProviderStep(true)}>Buscar, crear o modificar proveedor</button>}</>}
   </>}
   {section==='income'&&<p className="my-3 text-sm">Se añadirá un presupuesto recurrente de ingresos. Las órdenes del Control administrativo siguen aportando los cobros concretos; no se crean órdenes ficticias.</p>}
   {!providerStep&&<button className={`${button} mt-4`} onClick={next}>Continuar</button>}
  </>}
  {step===2&&<><div className="grid gap-3 sm:grid-cols-2"><label className="text-sm">Importe total (€)<input inputMode="decimal" className="mt-1 w-full rounded border p-2" value={amount} onChange={e=>setAmount(e.target.value)}/></label><div className="text-sm">Frecuencia<SearchableSelect label="Frecuencia" value={every} onChange={setEvery} options={[{value:'1',label:'Mensual'},{value:'2',label:'Cada dos meses'},{value:'3',label:'Trimestral'},{value:'6',label:'Semestral'},{value:'12',label:'Anual'}]}/></div></div>{mode!=='payroll'&&<ForecastVatFields amount={Number(amount.replace(',','.'))} choice={vatChoice} rate={vatRate} onChoice={setVatChoice} onRate={setVatRate}/>}<fieldset className="my-4"><legend className="mb-2 text-sm">Primer vencimiento</legend><div className="flex gap-2">{[['Día',dd,setDd,2],['Mes',mm,setMm,2],['Año',yyyy,setYyyy,4]].map(([name,value,set,max])=><label key={String(name)} className="text-sm">{String(name)}<input aria-label={`Primer vencimiento ${name}`} inputMode="numeric" maxLength={Number(max)} className="ml-2 w-20 rounded border p-2" value={String(value)} onChange={e=>(set as (s:string)=>void)(e.target.value.replace(/\D/g,''))}/></label>)}</div></fieldset><p className="my-3 text-sm">El día 31 se ajusta al último día en los meses más cortos. </p><div className="flex gap-2"><button className={button} onClick={review}>Revisar</button><button className={button} onClick={()=>setStep(1)}>Volver</button></div></>}
  {step===3&&<><p className="my-3"><strong>{label}</strong> · {bank} {year}</p><p className="my-3 text-sm">{mode==='existing'?`Se reutilizará el cargo de ${chosen?.nombre_proveedor||chosen?.nombre_agente||'ERP'}, con su programación vigente.`:`${section==='payments'?mode==='payroll'?employees.find(e=>e.id_agente===employeeId)?.nombre:provider?.nombre_proveedor:'Ingreso previsto'} · ${amount} € cada ${every} mes(es), desde ${dd}/${mm}/${yyyy}.`}</p><p className="mb-3 text-sm">{rowId?'La fila actual usará estos vencimientos, conservando sus realizados. No se añadirá una segunda fila.':'Se añadirá una fila con los vencimientos de los meses abiertos de esta pestaña.'} Los totales se actualizarán al guardar.</p><div className="flex gap-2"><button disabled={busy} className={button} onClick={()=>{void save();}}>{rowId?'Guardar vínculo y programación':'Guardar y añadir a la hoja'}</button><button disabled={busy} className={button} onClick={()=>setStep(mode==='existing'?1:2)}>Volver</button></div></>}
 </section></div>;
}
