"use client";
import {useEffect,useState} from 'react';
type Part={id:string;label:string;detail?:string;date?:string;amount:number;editable:boolean;href?:string};
const money=(n:number)=>(n/100).toLocaleString('es-ES',{minimumFractionDigits:2,maximumFractionDigits:2})+' €';
export default function JuanCellModal({label,parts,disabled,onClose,onSave}:{label:string;parts:Part[];disabled:boolean;onClose:()=>void;onSave:(value:number,components:{id:string;amount:number}[])=>Promise<void>}) {
 const [draft,setDraft]=useState(parts.map(p=>(p.amount/100).toFixed(2).replace('.',','))),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 useEffect(()=>{const handler=(e:KeyboardEvent)=>{if(e.key==='Escape'&&!busy)onClose();};window.addEventListener('keydown',handler);return()=>window.removeEventListener('keydown',handler);},[onClose,busy]);
 const values=draft.map(s=>{const v=s.trim().includes(',')?s.trim().replace(/\./g,'').replace(',','.'):s.trim();return /^-?\d+(\.\d{1,2})?$/.test(v)?Math.round(Number(v)*100):NaN;});
 const valid=values.every(Number.isSafeInteger),total=values.reduce((n,v)=>n+v,0);
 return <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/40 p-4"><section role="dialog" aria-modal="true" aria-label={label} className="max-h-[90vh] w-full max-w-2xl overflow-auto rounded-xl bg-white p-6 shadow-xl"><div className="flex items-start justify-between gap-4"><h2 className="text-lg font-semibold">{label}</h2><button aria-label="Cerrar desglose" className="cursor-pointer rounded px-3 py-1 text-2xl hover:bg-gray-100 disabled:cursor-default" disabled={busy} onClick={onClose}>×</button></div><p className="my-4 rounded bg-blue-50 p-3 font-semibold">{parts.length===1?'Un solo cargo: ':''}{valid?values.map(money).join(' + '):'Revisa los importes'} = {valid?money(total):'—'}</p><p className="mb-3 text-sm text-gray-600">El total se calcula sumando los cargos individuales.</p><div className="space-y-3">{parts.map((part,index)=><label key={part.id} className="block rounded border p-3"><span className="block font-medium">{part.href?<a href={part.href} target="_blank" rel="noreferrer" className="cursor-pointer text-blue-900 underline hover:text-blue-600">{part.label}</a>:part.label}</span><span className="block text-sm text-gray-500">{part.date} {part.detail}{!part.editable?' · Importe de documento o extracto registrado':''}</span><input aria-label={`Importe ${part.label}`} inputMode="decimal" value={draft[index]} disabled={disabled||busy||!part.editable} className="mt-2 w-full rounded border p-2 disabled:bg-gray-100" onChange={e=>setDraft(d=>d.map((s,i)=>i===index?e.target.value:s))}/></label>)}</div>{error&&<p role="alert" className="mt-3 text-red-700">{error}</p>}<button className="mt-5 cursor-pointer rounded bg-blue-600 px-4 py-2 text-white hover:bg-blue-700 disabled:cursor-default disabled:bg-gray-300" disabled={disabled||busy||!valid||parts.every(p=>!p.editable)} onClick={async()=>{setBusy(true);setError('');try{await onSave(total,parts.map((p,i)=>({id:p.id,amount:values[i]})));onClose();}catch(e){setError(e instanceof Error?e.message:'No se pudo guardar.');}finally{setBusy(false);}}}>{busy?'Guardando…':'Guardar cargos'}</button></section></div>;
}
