'use client';
import { matchesTableFilter } from "@/app/lib/dateFilters";
import TableFilterInput from "@/app/components/TableFilterInput";
import TableFilters from '@/app/components/TableFilters';
import {request} from '@/app/lib/request';
import {useCallback,useEffect,useState} from 'react';
import SearchableSelect from '@/app/components/SearchableSelect';
import JuanAddRow from './JuanAddRow';
import InvoicePaymentsModal from './InvoicePaymentsModal';
import UnassignedInvoicePayments,{type UnassignedPayment} from './UnassignedInvoicePayments';
import JuanRowDetails,{type JuanAssociation,type JuanCharge} from './JuanRowDetails';
type Item={key:string;rowId:string;bank:string;section:'income'|'payments';label:string;month:number;date:string;estimatedDate:boolean;amount:number;applied:number;pending:number};
type Row={id:string;label:string;day:number|null;values:(number|null)[];cardPart?:string;invoicePaymentId?:string};
type Book={unassignedPayments:UnassignedPayment[];version:number;planned:Item[];associations:JuanAssociation[];charges:JuanCharge[];orders:{id_orden:string;banco_cobro:string;cobro_total:string;fecha_teorica_cobro:string;forma_cobro:string}[];sheets:{bank:string;columns:{month:number;kind:string}[];income:Row[];payments:Row[];closedMonths?:number[]}[]};
const money=(value:number)=>(value/100).toLocaleString('es-ES',{style:'currency',currency:'EUR'});
const columns=[['bank','Banco'],['label','Concepto'],['date','Fecha prevista'],['amount','Previsto'],['applied','Realizado'],['pending','Pendiente']] as const;
export default function JuanPlannedList({section,revision,year=new Date().getFullYear()}:{section:'income'|'payments';revision:number;year?:number}) {
 const [book,setBook]=useState<Book|null>(null),[error,setError]=useState(''),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[filters,setFilters]=useState<Record<string,string>>({}),[bank,setBank]=useState(''),[adding,setAdding]=useState(false),[detail,setDetail]=useState<Item|null>(null);
 const load=useCallback(async(signal?:AbortSignal)=>{setLoading(true);setError('');try{const r=await request(`/api/v1/direccion/prevision-liquidez/vista-juan?year=${year}`,{signal,cache:'no-store'});const b=await r.json();if(!r.ok)throw Error(b.message);if(!signal?.aborted)setBook(b);}catch(e){if(!(e instanceof Error&&e.name==='AbortError'))setError(e instanceof Error?e.message:'No se pudo cargar la previsión.');}finally{if(!signal?.aborted)setLoading(false);}},[year]);
 useEffect(()=>{const c=new AbortController();void load(c.signal);return()=>c.abort();},[load,revision]);
 const changed=async()=>{await load();window.dispatchEvent(new Event('p3:forecast-changed'));};
 const text=(item:Item,key:string)=>['amount','applied','pending'].includes(key)?money(item[key as 'amount'|'applied'|'pending']):String(item[key as 'bank'|'label'|'date']);
 const shown=book?.planned.filter(item=>item.section===section&&columns.every(([key])=>matchesTableFilter(text(item,key).toLocaleLowerCase('es'), (filters[key]||'').toLocaleLowerCase('es'))))||[];
 const save=async(item:Item,draft:string)=>{if(!book||busy)return;let value:null|number=null;const clean=draft.trim().replace(/\s|€/g,'');if(clean){const number=Number(clean.includes(',')?clean.replace(/\./g,'').replace(',','.'):clean);if(!Number.isFinite(number)||number<0){setError('Indica un importe válido.');return;}value=Math.round(number*100);}if(value===item.amount)return;const sheet=book.sheets.find(s=>s.bank===item.bank),column=sheet?.columns.findIndex(c=>c.kind==='forecast'&&c.month===item.month);setBusy(true);setError('');try{const r=await request('/api/v1/direccion/prevision-liquidez/vista-juan',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({year,version:book.version,bank:item.bank,section:item.section,rowId:item.rowId,column,value})});const b=await r.json();if(!r.ok)throw Error(b.message);setBook(b);window.dispatchEvent(new Event('p3:forecast-changed'));}catch(e){setError(e instanceof Error?e.message:'No se pudo guardar.');}finally{setBusy(false);}};
 const closeInvoice=useCallback(()=>setDetail(null),[]);
 const detailSheet=book?.sheets.find(s=>s.bank===detail?.bank),detailRow=detail&&detailSheet?.[detail.section].find(r=>r.id===detail.rowId);
 return <section className="mt-4 rounded-xl bg-white p-6 shadow"><h2 className="text-lg font-semibold">{section==='income'?'Ingresos':'Gastos'} previstos · {year}</h2><p className="my-3 text-sm">Edita el importe de un mes o abre su concepto para ver cargos, gestionar el proveedor y retirar previsiones. Son los mismos datos que en Vista Juan.</p>
  <div className="mb-4 flex flex-wrap items-center gap-3"><SearchableSelect className="w-60" label="Banco de la nueva previsión" value={bank} onChange={setBank} disabled={busy} options={[{value:'Sabadell',label:'Banco Sabadell'},{value:'Santander',label:'Banco Santander'}]}/><button disabled={!bank||busy||!book} onClick={()=>setAdding(true)} className="rounded border px-4 py-2 enabled:cursor-pointer enabled:hover:bg-blue-100 disabled:cursor-default disabled:opacity-50">+ Añadir {section==='income'?'ingreso':'gasto'} recurrente</button></div>
  {error&&<p role="alert" className="my-3 text-red-700">{error}</p>}{loading?<p>Cargando previsiones…</p>:book&&<div className="overflow-x-auto"><TableFilters>{columns.map(([key,label])=><div key={key}><label className="block text-xs font-extralight text-gray-600"><span className="mb-1 block">{label}</span><TableFilterInput label={label} field={key} value={filters[key]||''} className="mt-2 w-full rounded border bg-white p-2" onChange={nextValue => setFilters({...filters,[key]:nextValue})} /></label></div>)}</TableFilters><table className="w-full text-sm"><thead className="bg-blue-50"><tr>{columns.map(([key,label])=><th key={key} className="p-3 text-left">{label}</th>)}</tr></thead><tbody>{shown.map(item=>{const sheet=book.sheets.find(s=>s.bank===item.bank),row=sheet?.[item.section].find(r=>r.id===item.rowId),disabled=busy||Boolean(sheet?.closedMonths?.includes(item.month))||Boolean(row?.invoicePaymentId)||row?.cardPart==='subscriptions';return <tr key={`${item.key}:${item.amount}`} className="border-t"><td className="p-3">{item.bank}</td><td className="p-3"><button disabled={busy} onClick={()=>setDetail(item)} className="rounded px-1 py-1 text-left enabled:cursor-pointer enabled:hover:bg-blue-100 disabled:cursor-default">{item.label}</button></td><td className="p-3">{item.date}{item.estimatedDate?' · estimada':''}</td><td className="p-3"><input aria-label={`Importe ${item.label} ${item.date}`} inputMode="decimal" defaultValue={(item.amount/100).toFixed(2).replace('.',',')} disabled={disabled} onBlur={e=>{void save(item,e.target.value);}} onKeyDown={e=>{if(e.key==='Enter')e.currentTarget.blur();if(e.key==='Escape'){e.currentTarget.value=(item.amount/100).toFixed(2).replace('.',',');e.currentTarget.blur();}}} className="w-28 rounded border p-2 enabled:hover:border-blue-800 disabled:bg-gray-100"/></td><td className="p-3">{money(item.applied)}</td><td className="p-3">{money(item.pending)}</td></tr>;})}</tbody><tfoot><tr className="border-t font-semibold"><th colSpan={3} className="p-3 text-left">TOTAL VISIBLE</th>{(['amount','applied','pending'] as const).map(key=><td key={key} className="p-3">{money(shown.reduce((n,item)=>n+item[key],0))}</td>)}</tr></tfoot></table></div>}
  {section==='payments'&&book&&<UnassignedInvoicePayments payments={book.unassignedPayments||[]} onSaved={()=>void changed()}/>}
  {adding&&book&&<JuanAddRow key={`${section}:${bank}:${year}`} year={year} bank={bank} section={section} version={book.version} charges={book.charges} onSaved={changed} onClose={()=>setAdding(false)}/>}
  {detailRow?.invoicePaymentId&&<InvoicePaymentsModal id={detailRow.invoicePaymentId} onClose={closeInvoice} onSaved={()=>{setDetail(null);void changed();}}/>}
  {detail&&detailRow&&!detailRow.invoicePaymentId&&detailSheet&&book&&<JuanRowDetails year={year} bank={detail.bank} rowId={detail.rowId} label={detailRow.label} section={detail.section} day={detailRow.day} version={book.version} budgets={Array.from({length:12},(_,i)=>detailRow.values[detailSheet.columns.findIndex(c=>c.kind==='forecast'&&c.month===i+1)]??null)} associations={book.associations} charges={book.charges} orders={book.orders} onSaved={changed} onClose={()=>setDetail(null)}/>}
 </section>;
}
