'use client';
import SearchableSelect from "@/app/components/SearchableSelect";
import { useEffect, useState } from 'react';
import RecurringChargeForm, { newCharge, reviewButton as button } from './RecurringChargeForm';
export default function RecurringChargeModal({ providers, employees = [], supplierId = '', initialKind = 'proveedor', close, done }: { providers:any[]; employees?:any[]; supplierId?:string; initialKind?:string; close:()=>void; done:()=>void }) {
  const [kind,setKind]=useState(initialKind), [entity,setEntity]=useState(supplierId), [search,setSearch]=useState(''), [value,setValue]=useState<any>(newCharge), [vat,setVat]=useState(true), [saving,setSaving]=useState(false), [error,setError]=useState('');
  useEffect(()=>{const fn=(e:KeyboardEvent)=>{if(e.key==='Escape')close();};window.addEventListener('keydown',fn);return()=>window.removeEventListener('keydown',fn);},[close]);
  const save=async()=>{setSaving(true);setError('');try{const r=await fetch('/api/v1/direccion/cargos-recurrentes',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...value,tipo_cargo:kind,id_proveedor:kind==='proveedor'?entity||null:null,id_agente:kind==='nomina'?entity:null,programacion:value.programacion.map((r:any)=>({...r,base_imponible:kind==='nomina'?0:Math.round(Number(r.total_iva)/(vat?1.21:1)*100)/100}))})});const d=await r.json();if(!r.ok)throw new Error(d.message);done();}catch(e:any){setError(e.message);}finally{setSaving(false);}};
  return <div className="fixed inset-0 z-50 overflow-y-auto bg-black/65 p-4"><section role="dialog" aria-modal="true" aria-label="Agregar cargo previsto" className="mx-auto my-6 max-w-5xl space-y-4 rounded-xl bg-white p-6 text-slate-900"><header className="flex justify-between"><h2 className="text-xl font-semibold">Agregar cargo previsto</h2><button type="button" aria-label="Cerrar" onClick={close} className="cursor-pointer rounded px-3 text-2xl hover:bg-blue-50">×</button></header>
    {!supplierId&&initialKind!=='nomina'&&<><label>Tipo<select value={kind} onChange={e=>{setKind(e.target.value);setEntity('');}} className="ml-3 cursor-pointer rounded border p-2 hover:bg-blue-50"><option value="proveedor">Proveedor</option><option value="nomina">Nómina</option></select></label></>}
    <SearchableSelect label="Proveedor o empleado" disabled={!!supplierId} value={entity} onChange={setEntity} required={kind==='nomina'} options={[...(kind==='proveedor'?[{value:'',label:'Sin asignar proveedor'}]:[]),...(kind==='proveedor'?providers:employees).map(r=>({value:r.id_proveedor||r.id_agente,label:r.nombre_proveedor||r.nombre||r.nombre_completo_agente||r.id_agente}))]} />
    <RecurringChargeForm value={value} onChange={setValue} payroll={kind==='nomina'} vat={vat} onVatChange={setVat} />{error&&<p role="alert" className="text-red-700">{error}</p>}<footer className="flex justify-end"><button type="button" disabled={saving||kind==='nomina'&&!entity} className={button} onClick={save}>{saving?'Guardando…':'Guardar cargo previsto'}</button></footer>
  </section></div>;
}
