"use client";

import { useEffect, useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import MiddleNav from "@/app/general_components/componentes_recurrentes/MiddleNav";

type Tab = "registrados" | "pendientes";
const emptyExpense = { id_proveedor: "", id_factura_proveedor: "", day: "", month: "", year: "", bi_pago: "", total_pago: "", forma_pago: "recibo", cuenta_pago: "Sabadell", nombre_planificacion: "", descripcion_planificacion: "", comentarios: "" };

export default function PrevisionGastosPage() {
  const router = useRouter();
  const [rows, setRows] = useState<any[]>([]);
  const [providers, setProviders] = useState<any[]>([]);
  const [filter, setFilter] = useState("");
  const [tab, setTab] = useState<Tab>("registrados");
  const [showModal, setShowModal] = useState(false);
  const [reloadKey, setReloadKey] = useState(0);
  useEffect(() => { Promise.all([fetch("/api/v1/direccion/prevision-gastos").then((r) => r.json()), fetch("/api/v1/admin/proveedores").then((r) => r.json())]).then(([payments, providerRows]) => { setRows(Array.isArray(payments) ? payments : []); setProviders(Array.isArray(providerRows) ? providerRows : []); }); }, [reloadKey]);
  const shown = useMemo(() => rows.filter((row) => tab === "registrados" ? Boolean(row.id_proveedor) : !row.id_proveedor).filter((row) => !filter.trim() || Object.values(row).join(" ").toLowerCase().includes(filter.trim().toLowerCase())), [filter, rows, tab]);
  return <div className="min-h-screen bg-gray-100"><MiddleNav tituloprincipal="Previsión gastos"/><main className="p-6 lg:p-12">
    <div className="mb-4 flex flex-col gap-3 xl:flex-row xl:items-end xl:justify-between"><div><div className="flex gap-2">{([{ key: "registrados", label: "Gastos previstos registrados" }, { key: "pendientes", label: "Gastos pendientes de asociar" }] as const).map((item) => <button key={item.key} type="button" onClick={() => setTab(item.key)} className={`cursor-pointer rounded px-4 py-2 text-sm transition hover:shadow-sm ${tab === item.key ? "bg-blue-950 text-white" : "bg-white hover:bg-gray-200"}`}>{item.label}</button>)}</div><p className="mt-2 text-sm text-gray-500">Cada vencimiento o pago se registra como un gasto independiente.</p></div><div className="flex flex-col gap-2 sm:flex-row"><label className="text-sm font-medium">Filtrar gastos<input type="search" placeholder="Proveedor, factura, fecha, banco..." value={filter} onChange={(event) => setFilter(event.target.value)} className="mt-1 block w-full rounded border border-gray-300 bg-white px-3 py-2 outline-none transition focus:border-blue-950 sm:w-96"/></label>{tab === "registrados" && <button type="button" onClick={() => setShowModal(true)} className="mt-auto cursor-pointer rounded bg-blue-950 px-4 py-2 text-sm font-semibold text-white transition hover:bg-blue-900 hover:shadow-md">Agregar gasto previsto</button>}</div></div>
    <div className="overflow-x-auto bg-white shadow-sm"><table className="min-w-full text-sm"><thead className="bg-blue-950 text-white"><tr>{["Pago","Proveedor","Fecha","Forma","Banco","Base imponible","Importe","Descripción"].map((label) => <th key={label} className="p-3 text-left font-medium">{label}</th>)}</tr></thead><tbody>{shown.map((row) => <tr key={row.id_pago} onClick={() => router.push(`/dashboard/direccion/previsiones/prevision-gastos/${encodeURIComponent(row.id_pago)}`)} className="cursor-pointer border-b transition hover:bg-blue-50"><td className="p-3 font-medium text-blue-950">{row.id_pago}</td><td className="p-3">{row.nombre_proveedor || row.id_proveedor || <span className="text-amber-700">Pendiente de asociar</span>}</td><td className="p-3">{row.fecha_pago || "-"}</td><td className="p-3 capitalize">{row.forma_pago || "-"}</td><td className="p-3">{row.cuenta_pago || "-"}</td><td className="p-3">{Number(row.bi_pago || 0).toFixed(2)} €</td><td className="p-3">{Number(row.total_pago || 0).toFixed(2)} €</td><td className="p-3">{row.descripcion_planificacion || "—"}</td></tr>)}{!shown.length && <tr><td colSpan={8} className="p-8 text-center text-gray-500">No hay gastos en esta pestaña.</td></tr>}</tbody></table></div>
    {showModal && (
      <ExpenseModal providers={providers} onClose={() => setShowModal(false)} onCreated={() => { setShowModal(false); setReloadKey((current) => current + 1); }} />
    )}
  </main></div>;
}

function ExpenseModal({ providers, onClose, onCreated }: { providers: any[]; onClose: () => void; onCreated: () => void }) {
  const [form, setForm] = useState(emptyExpense);
  const [providerFilter, setProviderFilter] = useState("");
  const [saving, setSaving] = useState(false);
  const [error, setError] = useState("");
  useEffect(() => { const close = (event: KeyboardEvent) => { if (event.key === "Escape" && !saving) onClose(); }; window.addEventListener("keydown", close); return () => window.removeEventListener("keydown", close); }, [onClose, saving]);
  const date = `${form.day}/${form.month}/${form.year}`;
  const valid = Boolean(form.id_proveedor && /^\d{2}\/\d{2}\/\d{4}$/.test(date) && Number(form.total_pago) > 0);
  const save = async () => { try { setSaving(true); setError(""); const response = await fetch("/api/v1/direccion/prevision-gastos", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ...form, fecha_pago: date }) }); const data = await response.json(); if (!response.ok) throw new Error(data.message); onCreated(); } catch (requestError: any) { setError(requestError.message || "No se ha podido crear el gasto"); setSaving(false); } };
  const shownProviders = providers.filter((provider) => !providerFilter.trim() || [provider.id_proveedor, provider.nombre_proveedor, provider.nombre_fiscal_proveedor, provider.vat_code].join(" ").toLowerCase().includes(providerFilter.trim().toLowerCase())).slice(0, 10);
  return <div role="dialog" aria-modal="true" aria-labelledby="expense-modal-title" className="fixed inset-0 z-[70] flex items-center justify-center bg-slate-950/60 p-4" onMouseDown={(event) => { if (event.target === event.currentTarget && !saving) onClose(); }}><section className="max-h-[92vh] w-full max-w-3xl overflow-y-auto rounded-xl bg-white shadow-2xl"><header className="flex justify-between border-b px-6 py-4"><div><h2 id="expense-modal-title" className="text-xl font-semibold text-blue-950">Agregar gasto previsto</h2><p className="text-sm text-gray-500">Registra un pago. Si hay varios vencimientos, crea un registro para cada uno.</p></div><button type="button" onClick={onClose} disabled={saving} aria-label="Cerrar" className="flex h-9 w-9 cursor-pointer items-center justify-center rounded-full border text-2xl transition hover:bg-gray-100 disabled:cursor-not-allowed">×</button></header><div className="space-y-4 p-6">
    <div><label className="text-sm font-medium">Buscar proveedor<input type="search" value={providerFilter} onChange={(e) => setProviderFilter(e.target.value)} className="mt-1 w-full rounded border px-3 py-2" placeholder="Nombre, CIF o código..."/></label><div className="mt-2 max-h-40 overflow-y-auto border">{shownProviders.map((provider) => <button key={provider.id_proveedor} type="button" onClick={() => setForm({ ...form, id_proveedor: provider.id_proveedor })} className={`flex w-full cursor-pointer justify-between border-b p-2 text-left text-sm transition hover:bg-blue-50 ${form.id_proveedor === provider.id_proveedor ? "bg-blue-100" : ""}`}><span>{provider.nombre_proveedor || provider.nombre_fiscal_proveedor}</span><span>{provider.id_proveedor}</span></button>)}</div></div>
    <div className="grid gap-4 sm:grid-cols-2"><label className="text-sm font-medium">Nombre o concepto<input value={form.nombre_planificacion} onChange={(e) => setForm({ ...form, nombre_planificacion: e.target.value })} className="mt-1 w-full rounded border px-3 py-2"/></label><label className="text-sm font-medium">Nº factura de proveedor (opcional)<input value={form.id_factura_proveedor} onChange={(e) => setForm({ ...form, id_factura_proveedor: e.target.value })} className="mt-1 w-full rounded border px-3 py-2"/></label></div>
    <fieldset><legend className="mb-1 text-sm font-medium">Fecha prevista del pago</legend><div className="flex gap-2"><input aria-label="Día" value={form.day} onChange={(e) => setForm({ ...form, day: e.target.value.replace(/\D/g, "").slice(0,2) })} placeholder="dd" className="w-20 rounded border px-3 py-2"/><input aria-label="Mes" value={form.month} onChange={(e) => setForm({ ...form, month: e.target.value.replace(/\D/g, "").slice(0,2) })} placeholder="mm" className="w-20 rounded border px-3 py-2"/><input aria-label="Año" value={form.year} onChange={(e) => setForm({ ...form, year: e.target.value.replace(/\D/g, "").slice(0,4) })} placeholder="yyyy" className="w-28 rounded border px-3 py-2"/></div></fieldset>
    <div className="grid gap-4 sm:grid-cols-2"><label className="text-sm font-medium">Forma<select value={form.forma_pago} onChange={(e) => setForm({ ...form, forma_pago: e.target.value })} className="mt-1 w-full cursor-pointer rounded border bg-white px-3 py-2"><option value="recibo">Recibo</option><option value="transferencia">Transferencia</option><option value="pagaré">Pagaré</option></select></label><label className="text-sm font-medium">Banco<select value={form.cuenta_pago} onChange={(e) => setForm({ ...form, cuenta_pago: e.target.value })} className="mt-1 w-full cursor-pointer rounded border bg-white px-3 py-2"><option>Sabadell</option><option>Santander</option></select></label></div>
    <div className="grid gap-4 sm:grid-cols-2"><label className="text-sm font-medium">Base imponible (€)<input type="number" min="0" step="0.01" value={form.bi_pago} onChange={(e) => setForm({ ...form, bi_pago: e.target.value })} className="mt-1 w-full rounded border px-3 py-2"/></label><label className="text-sm font-medium">Importe del pago (€)<input type="number" min="0.01" step="0.01" value={form.total_pago} onChange={(e) => setForm({ ...form, total_pago: e.target.value })} className="mt-1 w-full rounded border px-3 py-2"/></label></div>
    <label className="block text-sm font-medium">Descripción<textarea value={form.descripcion_planificacion} onChange={(e) => setForm({ ...form, descripcion_planificacion: e.target.value })} className="mt-1 min-h-20 w-full rounded border px-3 py-2"/></label>{error && <p className="rounded border border-red-200 bg-red-50 p-3 text-sm text-red-700">{error}</p>}<div className="flex justify-end gap-3 border-t pt-4"><button type="button" onClick={onClose} disabled={saving} className="cursor-pointer rounded border px-4 py-2 transition hover:bg-gray-50 disabled:cursor-not-allowed">Cancelar</button><button type="button" onClick={() => void save()} disabled={!valid || saving} className="cursor-pointer rounded bg-blue-950 px-4 py-2 font-semibold text-white transition hover:bg-blue-900 disabled:cursor-not-allowed disabled:bg-gray-300">{saving ? "Guardando…" : "Crear gasto previsto"}</button></div>
  </div></section></div>;
}
