'use client';
import LiquidacionesFrame from './LiquidacionesFrame';
import {useCallback,useEffect,useState} from 'react';import Link from 'next/link';
import SearchableSelect from '@/app/components/SearchableSelect';import DatePartsInput from '@/app/components/DatePartsInput';
import {api,button,input,date,iso,money,CardTable} from '../tarjetas/CardComponents';import ImportSettlementModal from './ImportSettlementModal';
export default function SettlementView({id,cardId}:{id:string;cardId:string}){
 const [data,setData]=useState<any>(null),[lines,setLines]=useState<any[]>([]),[bankIds,setBankIds]=useState<string[]>([]),[otros,setOtros]=useState<any[]>([]),[omitidos,setOmitidos]=useState<string[]>([]),[comment,setComment]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[dirty,setDirty]=useState(false),[open,setOpen]=useState(false),[notice,setNotice]=useState('');
 const accept=(d:any)=>{setData(d);setLines(d.lines);setBankIds(d.bankLines.map((b:any)=>b.id_linea_banco));setOtros(d.settlement.detalle.otros||[]);setOmitidos(d.settlement.detalle.omitidos||[]);setComment(d.settlement.comentario);setDirty(false);};
 const load=useCallback(async()=>accept(await api(`/api/v1/admin/liquidaciones/${encodeURIComponent(id)}`)),[id]);useEffect(()=>{load().catch(e=>setError(e.message));},[load]);
 useEffect(()=>{const fn=(e:BeforeUnloadEvent)=>{if(dirty){e.preventDefault();e.returnValue='';}};window.addEventListener('beforeunload',fn);return()=>window.removeEventListener('beforeunload',fn);},[dirty]);
 const change=(line:string,fields:any)=>{setLines(rows=>rows.map(r=>r.id===line?{...r,...fields}:r));setDirty(true);setNotice('');};
 const save=async(review=false)=>{setBusy(true);setError('');try{accept(await api(`/api/v1/admin/liquidaciones/${encodeURIComponent(id)}`,{version:data.settlement.version,lines,bankIds,otros:otros.map(o=>({...o,fecha:iso(o.fecha),importe:Number(o.importe)})),omitidos,comentario:comment,action:review?'review':'save'},'PUT'));setNotice(review?'Liquidación revisada.':'Cambios guardados. Puedes continuar más adelante.');}catch(e:any){setError(e.message);}finally{setBusy(false);}};
 if(!data)return <LiquidacionesFrame title="Liquidaciones" className="p-8">{error||'Cargando liquidación…'}</LiquidacionesFrame>;if(data.card.id_tarjeta!==cardId)return <LiquidacionesFrame title="Liquidaciones" className="p-8">La liquidación no pertenece a esta tarjeta.</LiquidacionesFrame>;const l=data.settlement,readonly=l.estado!=='pendiente';
 const options=[...data.forecast.items.filter((i:any)=>i.tipo!=='otro'),...otros.map(o=>({...o,tipo:'otro'}))].filter((i:any)=>!omitidos.includes(`${i.tipo}:${i.id}`)).map((i:any)=>({value:`${i.tipo}:${i.id}`,label:`${i.tipo} · ${i.descripcion} · ${money(i.importe)}`}));
 const used=new Set(lines.flatMap(r=>[r.id_ticket?`ticket:${r.id_ticket}`:'',r.id_vencimiento?`suscripcion:${r.id_vencimiento}`:'',r.id_otro?`otro:${r.id_otro}`:'']));const bankRows=[...data.bankLines,...data.candidates];
 return <LiquidacionesFrame title="Liquidaciones" ><Link className="cursor-pointer text-blue-900 hover:underline" href={`/dashboard/administracion/liquidaciones/tarjetas/${encodeURIComponent(cardId)}`}>← {data.card.nombre}</Link><header className="flex flex-wrap justify-between gap-4"><div><h1 className="text-2xl font-semibold">Liquidación · {date(l.fecha).slice(3)}</h1><p>{date(l.inicio)} — {date(l.cierre)} · {readonly?l.estado:'Pendiente de puntear'}</p></div>{!readonly&&!data.document&&<button className={button} disabled={dirty} onClick={()=>setOpen(true)}>Importar liquidación</button>}{data.document&&<a className={button} target="_blank" rel="noreferrer" href={`/api/v1/admin/liquidaciones/${id}/archivo`}>Ver PDF bancario</a>}</header>{notice&&<p role="status" className="rounded bg-green-50 p-3">{notice}</p>}{error&&<p role="alert" className="whitespace-pre-wrap text-red-700">{error}</p>}<section className="rounded bg-white p-5"><p>Previsto inicial: {money(l.previsto)} · Previsto actual: {money(data.forecast.total)} · PDF: {l.real===null?'Sin importar':money(l.real)} · Extracto bancario: {money(data.checks.banco)} · Diferencia entre documentos: {money(data.checks.diferencia)}</p></section>
 <section className="space-y-3 rounded bg-white p-5"><h2 className="text-lg font-semibold">Cargo total en Tesorería</h2>{!bankRows.length&&<p>No hay cargos disponibles cerca de esta fecha.</p>}{bankRows.map((b:any)=><label key={b.id_linea_banco} className={`flex items-start gap-3 rounded p-3 ${readonly?'':'cursor-pointer hover:bg-blue-50'}`}><input type="checkbox" disabled={readonly||busy} className="enabled:cursor-pointer" checked={bankIds.includes(b.id_linea_banco)} onChange={e=>{setBankIds(ids=>e.target.checked?[...ids,b.id_linea_banco]:ids.filter(x=>x!==b.id_linea_banco));setDirty(true);}}/><span>{b.fecha_operativa||b.fecha_valor} · {money(b.importe)} · {b.concepto}</span></label>)}</section>
 <section className="space-y-4 rounded bg-white p-5"><h2 className="text-lg font-semibold">Movimientos reales y asociaciones</h2>{!lines.length&&<p>Importa el PDF para comenzar.</p>}{lines.map(r=><article key={r.id} className="space-y-3 rounded border p-4"><header className="flex justify-between gap-4"><p>{r.posicion}. {r.concepto}<span className="block text-sm text-gray-600">Operación {date(r.fecha)} · Anotación {date(r.fecha_valor)}</span></p><strong>{money(r.importe)}</strong></header><div className="grid gap-4 md:grid-cols-2"><SearchableSelect label="Ticket, suscripción u otro gasto" disabled={readonly||busy} value={r.id_ticket?`ticket:${r.id_ticket}`:r.id_vencimiento?`suscripcion:${r.id_vencimiento}`:r.id_otro?`otro:${r.id_otro}`:''} onChange={value=>{const [type,...parts]=value.split(':');const ref=parts.join(':');change(r.id,{id_ticket:type==='ticket'?ref:null,id_vencimiento:type==='suscripcion'?ref:null,id_otro:type==='otro'?ref:null});}} options={[{value:'',label:'Sin asociación'},...options]}/><label className="block">Estado<select disabled={readonly||busy} className={`${input} enabled:cursor-pointer enabled:hover:border-blue-950`} value={r.estado} onChange={e=>change(r.id,{estado:e.target.value,...(e.target.value==='sin_ticket'?{id_ticket:null}:{})})}><option value="pendiente">Pendiente de clasificar</option><option value="conciliado">Conciliado</option><option value="pendiente_ticket">Pendiente de recibir ticket</option><option value="sin_ticket">No hay ticket (ausencia justificada)</option></select></label></div><label className="block">Motivo / observaciones<textarea disabled={readonly||busy} maxLength={3000} className={input} value={r.motivo} onChange={e=>change(r.id,{motivo:e.target.value})}/></label>{!readonly&&r.estado==='sin_ticket'&&!r.id_ticket&&!r.id_vencimiento&&!r.id_otro&&<button className={button} onClick={()=>{const ref=crypto.randomUUID();setOtros(rows=>[...rows,{id:ref,descripcion:r.concepto,importe:r.importe,fecha:r.fecha_valor>=l.inicio&&r.fecha_valor<=l.cierre?r.fecha_valor:l.inicio}]);change(r.id,{id_otro:ref});}}>Incorporar este gasto a la previsión</button>}{r.id_ticket&&<Link className="cursor-pointer text-blue-900 underline hover:text-blue-600" target="_blank" href={`/dashboard/administracion/liquidaciones/tickets/${r.id_ticket}`}>Revisar ticket {r.id_ticket}</Link>}</article>)}</section>
 <section className="space-y-4 rounded bg-white p-5"><h2 className="text-lg font-semibold">Previsiones todavía sin asociar</h2><p>Un ticket puede pasar a efectivo, cambiar de tarjeta o quedar no asociable desde su detalle mientras esté pendiente de revisión.</p><CardTable rows={data.forecast.items.filter((i:any)=>!used.has(`${i.tipo}:${i.id}`)).map((i:any)=>({...i,total:money(i.importe)}))} columns={[{key:'tipo',label:'Tipo'},{key:'descripcion',label:'Concepto'},{key:'total',label:'Importe'},{key:'acciones',label:'Resolver',render:i=>i.tipo==='ticket'?<Link className="cursor-pointer text-blue-900 underline hover:text-blue-600" target="_blank" href={`/dashboard/administracion/liquidaciones/tickets/${i.id}`}>Gestionar ticket</Link>:i.tipo==='suscripcion'?<label className="flex gap-2 rounded p-2 enabled:cursor-pointer hover:bg-blue-50"><input disabled={readonly||busy} type="checkbox" className="enabled:cursor-pointer" checked={omitidos.includes(`suscripcion:${i.id}`)} onChange={e=>{setOmitidos(ids=>e.target.checked?[...ids,`suscripcion:${i.id}`]:ids.filter(x=>x!==`suscripcion:${i.id}`));setDirty(true);}}/>No se ha cargado en este período (explicar abajo)</label>:null}]}/>{omitidos.map(ref=><button key={ref} className={button} disabled={readonly||busy} onClick={()=>{setOmitidos(rows=>rows.filter(r=>r!==ref));setDirty(true);}}>Restaurar vencimiento {ref}</button>)}<button className={button} disabled={readonly||busy||dirty} onClick={()=>load().catch(e=>setError(e.message))}>Actualizar comprobaciones</button></section>
 <section className="space-y-4 rounded bg-white p-5"><h2 className="text-lg font-semibold">Otros gastos previstos</h2>{otros.map((o,i)=><div key={o.id} className="grid gap-3 rounded border p-3 md:grid-cols-4"><label>Concepto<input disabled={readonly||busy} className={input} value={o.descripcion} onChange={e=>{setOtros(rows=>rows.map((r,n)=>n===i?{...r,descripcion:e.target.value}:r));setDirty(true);}}/></label><label>Importe<input disabled={readonly||busy} type="number" step="0.01" className={input} value={o.importe} onChange={e=>{setOtros(rows=>rows.map((r,n)=>n===i?{...r,importe:e.target.value}:r));setDirty(true);}}/></label><DatePartsInput label="Fecha prevista" disabled={readonly||busy} value={o.fecha} onChange={v=>{setOtros(rows=>rows.map((r,n)=>n===i?{...r,fecha:v}:r));setDirty(true);}}/><button disabled={readonly||busy} className={button} onClick={()=>{setOtros(rows=>rows.filter((_,n)=>n!==i));setDirty(true);}}>Retirar previsión</button></div>)}<button className={button} disabled={readonly||busy} onClick={()=>{setOtros(rows=>[...rows,{id:crypto.randomUUID(),descripcion:'',importe:'',fecha:l.inicio}]);setDirty(true);}}>Añadir otro gasto</button></section>
 <section className="space-y-4 rounded bg-white p-5"><label className="block">Explicación de desviaciones y previsiones que no se han cargado<textarea disabled={readonly||busy} maxLength={10000} className={input} value={comment} onChange={e=>{setComment(e.target.value);setDirty(true);}}/></label>{!readonly&&<><p className="text-sm">Guardar conserva el trabajo aunque falten documentos o existan diferencias. Para revisar, guarda primero y resuelve las comprobaciones.</p>{data.checks.issues.length>0&&<ul className="list-disc space-y-1 pl-5 text-red-700">{data.checks.issues.map((s:string)=><li key={s}>{s}</li>)}</ul>}<div className="flex gap-3"><button className={button} disabled={busy} onClick={()=>save()}>Guardar cambios</button><button className={button} disabled={busy||dirty||data.checks.issues.length>0} onClick={()=>save(true)}>Marcar liquidación como revisada</button></div></>}</section>{open&&<ImportSettlementModal id={id} version={l.version} bank={data.card.banco} close={()=>setOpen(false)} done={()=>{setOpen(false);load().catch(e=>setError(e.message));}}/>}</LiquidacionesFrame>;
}
