'use client';
import {useCallback,useEffect,useState} from 'react';
import SearchableSelect from '@/app/components/SearchableSelect';
import RecurringChargeForm,{newCharge} from '@/app/dashboard/direccion/tesoreria/RecurringChargeForm';
import RecurringChargeManageModal from '@/app/dashboard/direccion/tesoreria/RecurringChargeManageModal';
import {api,button,CardTable,money} from '../tarjetas/CardComponents';
export function Modal({title,close,children}:{title:string;close:()=>void;children:React.ReactNode}){useEffect(()=>{const fn=(e:KeyboardEvent)=>{if(e.key==='Escape')close();};window.addEventListener('keydown',fn);return()=>window.removeEventListener('keydown',fn);},[close]);return <div className="fixed inset-0 z-50 overflow-y-auto bg-black/60 p-4"><section role="dialog" aria-modal="true" aria-label={title} className="mx-auto my-6 max-w-4xl space-y-5 rounded bg-white p-6 text-slate-900"><header className="flex justify-between"><h2 className="text-xl font-semibold">{title}</h2><button className={button} aria-label="Cerrar" onClick={close}>×</button></header>{children}</section></div>;}
export function SubscriptionCreate({cardId='',close,done}:{cardId?:string;close:()=>void;done:()=>void}){
 const [cards,setCards]=useState<any[]>([]),[providers,setProviders]=useState<any[]>([]),[card,setCard]=useState(cardId),[provider,setProvider]=useState(''),[schedule,setSchedule]=useState<any>(newCharge),[busy,setBusy]=useState(false),[error,setError]=useState('');
 useEffect(()=>{Promise.all([api('/api/v1/admin/tarjetas'),api('/api/v1/admin/proveedores')]).then(([c,p])=>{setCards(c);setProviders(p);}).catch(e=>setError(e.message));},[]);const selected=cards.find(c=>c.id_tarjeta===card);
 const save=async()=>{setBusy(true);setError('');try{await api(`/api/v1/admin/tarjetas/${encodeURIComponent(card)}/cargos`,{...schedule,action:'create',tipo_cargo:provider?'proveedor':'otro',id_proveedor:provider||null,banco_pago:selected.banco});done();}catch(e:any){setError(e.message);}finally{setBusy(false);}};
 return <Modal title="Nueva suscripción de tarjeta" close={close}><SearchableSelect label="Tarjeta" value={card} onChange={setCard} disabled={!!cardId||busy} options={cards.filter(c=>c.estado==='activa'&&c.proxima_liquidacion).map(c=>({value:c.id_tarjeta,label:`${c.nombre} · ${c.banco} · ${c.ultimos_digitos}`}))}/><SearchableSelect label="Proveedor (opcional)" value={provider} onChange={setProvider} options={[{value:'',label:'Otro (sin proveedor)'},...providers.map(p=>({value:p.id_proveedor,label:p.nombre_proveedor}))]}/><RecurringChargeForm value={schedule} onChange={setSchedule} fixedBank={selected?.banco}/>{error&&<p role="alert" className="text-red-700">{error}</p>}<button className={button} disabled={busy||!selected} onClick={save}>Guardar suscripción</button></Modal>;
}
export default function Subscriptions({cardId=''}:{cardId?:string}){
 const [rows,setRows]=useState<any[]>([]),[all,setAll]=useState<any[]>([]),[existing,setExisting]=useState(''),[create,setCreate]=useState(false),[editing,setEditing]=useState<any>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const load=useCallback(async()=>{setRows(await api('/api/v1/admin/liquidaciones/suscripciones'));if(cardId)setAll(await api(`/api/v1/admin/tarjetas/${encodeURIComponent(cardId)}/cargos`));},[cardId]);useEffect(()=>{load().catch(e=>setError(e.message));},[load]);
 const associate=async()=>{setBusy(true);try{await api(`/api/v1/admin/tarjetas/${encodeURIComponent(cardId)}/cargos`,{id_cargo_recurrente:existing});setExisting('');await load();}catch(e:any){setError(e.message);}finally{setBusy(false);}};
 const toggle=async(r:any)=>{setBusy(true);try{await api('/api/v1/admin/liquidaciones/suscripciones',{id:r.id_cargo_recurrente,card:r.id_tarjeta,version:r.updated_at,activo:!r.activo},'PUT');await load();}catch(e:any){setError(e.message);}finally{setBusy(false);}};
 return <section className="space-y-5"><div className="flex justify-between"><h2 className="text-xl font-semibold">{cardId?'Suscripciones asociadas':'Suscripciones de tarjeta'}</h2><button className={button} onClick={()=>setCreate(true)}>Nueva suscripción</button></div>{cardId&&<div className="flex items-end gap-3"><div className="flex-1"><SearchableSelect label="Asociar cargo recurrente existente" value={existing} onChange={setExisting} options={all.filter(c=>!c.id_tarjeta).map(c=>({value:String(c.id_cargo_recurrente),label:c.programacion.map((r:any)=>r.descripcion).join(', ')}))}/></div><button className={button} disabled={busy||!existing} onClick={associate}>Asociar</button></div>}{error&&<p role="alert" className="text-red-700">{error}</p>}<CardTable filterFields={{estado:['Activa','Inactiva']}} rows={rows.filter(r=>!cardId||r.id_tarjeta===cardId).map(r=>({...r,concepto:r.programacion.map((p:any)=>p.descripcion).join(', '),importe:money(r.programacion.reduce((n:number,p:any)=>n+Number(p.total_iva),0)),periodicidad:r.programacion.map((p:any)=>r.tipo_programacion==='periodicidad'?`Cada ${p.cada} ${p.unidad}`:'Fechas programadas').join(', '),cargo:r.programacion.map((p:any)=>`${p.inicio_dia||p.dia||''}/${p.inicio_mes||p.mes||''}/${p.inicio_anio||p.anio||''}`).join(', '),estado:r.activo?'Activa':'Inactiva'}))} columns={[{key:'concepto',label:'Concepto'},{key:'tarjeta',label:'Tarjeta'},{key:'importe',label:'Importe previsto'},{key:'periodicidad',label:'Periodicidad'},{key:'cargo',label:'Fecha prevista'},{key:'estado',label:'Estado'},{key:'acciones',label:'Acciones',render:r=><div className="flex gap-2"><button className={button} onClick={()=>setEditing(r)}>Editar</button><button className={button} disabled={busy} onClick={()=>toggle(r)}>{r.activo?'Desactivar':'Activar'}</button></div>}]}/>{create&&<SubscriptionCreate cardId={cardId} close={()=>setCreate(false)} done={()=>{setCreate(false);load().catch(e=>setError(e.message));}}/>}{editing&&<RecurringChargeManageModal id={String(editing.id_cargo_recurrente)} endpoint={`/api/v1/admin/tarjetas/${encodeURIComponent(editing.id_tarjeta)}/cargos/${editing.id_cargo_recurrente}`} fixedBank={editing.banco} action="edit" onClose={()=>setEditing(null)} onSaved={()=>{setEditing(null);load().catch(e=>setError(e.message));}}/>}</section>;
}
