"use client";

import { useEffect, useState } from "react";
import MiddleNav from "@/app/general_components/componentes_recurrentes/MiddleNav";

export default function InformacionLegalPage(){
  const [info,setInfo]=useState<any>(null);const [error,setError]=useState("");
  useEffect(()=>{fetch("/api/v1/admin/facturas-clientes/verifactu-installation").then(r=>r.ok?r.json():Promise.reject()).then(setInfo).catch(()=>setError("No se pudo cargar la declaración responsable."));},[]);
  return <div className="min-h-screen bg-gray-100 text-gray-700"><MiddleNav tituloprincipal="Información legal del sistema"/><main className="p-6 lg:p-12"><section className="mx-auto max-w-4xl rounded-xl bg-white p-6 shadow"><h1 className="text-2xl font-semibold text-blue-950">Declaración responsable VERI*FACTU</h1>{error&&<p className="mt-4 rounded bg-red-50 p-3 text-red-700">{error}</p>}{!info&&!error&&<p className="mt-4">Cargando...</p>}{info&&<><dl className="mt-6 grid gap-4 md:grid-cols-2"><div><dt className="text-xs font-semibold uppercase text-gray-400">Producto</dt><dd>{info.software_name}</dd></div><div><dt className="text-xs font-semibold uppercase text-gray-400">ID sistema</dt><dd>{info.software_id}</dd></div><div><dt className="text-xs font-semibold uppercase text-gray-400">Versión</dt><dd>{info.software_version}</dd></div><div><dt className="text-xs font-semibold uppercase text-gray-400">Productor</dt><dd>{info.producer_name}{info.producer_nif?` · ${info.producer_nif}`:""}</dd></div><div><dt className="text-xs font-semibold uppercase text-gray-400">Instalación</dt><dd>{info.installation_id}</dd></div><div><dt className="text-xs font-semibold uppercase text-gray-400">Fecha de emisión</dt><dd>{String(info.declaration_issued_at||"").slice(0,10)}</dd></div><div><dt className="text-xs font-semibold uppercase text-gray-400">Uso exclusivo VERI*FACTU</dt><dd>{info.exclusive_use?"Sí":"No"}</dd></div><div><dt className="text-xs font-semibold uppercase text-gray-400">Uso multiempresa</dt><dd>{info.multi_entity?"Sí":"No"}</dd></div></dl><div className="mt-6 rounded border border-blue-200 bg-blue-50 p-5"><h2 className="font-semibold text-blue-950">Declaración responsable</h2><p className="mt-2 whitespace-pre-wrap text-sm leading-6">{info.declaration_text}</p></div></>}</section></main></div>;
}
