'use client';
import {useEffect,useMemo,useState} from 'react';

const pageSize=30;
type Account={id_cuenta:string;nombre_empresa?:string;pais_cuenta?:string;correo_principal?:string};
export default function AccountSearchModal({accounts,onSelect,onClose}:{accounts:Account[];onSelect:(id:string)=>void;onClose:()=>void}){
  const [filters,setFilters]=useState({nombre_empresa:'',id_cuenta:'',pais_cuenta:'',correo_principal:''});
  const [selected,setSelected]=useState(''),[page,setPage]=useState(1);
  useEffect(()=>{const close=(event:KeyboardEvent)=>{if(event.key==='Escape')onClose();};window.addEventListener('keydown',close);return()=>window.removeEventListener('keydown',close);},[onClose]);
  const rows=useMemo(()=>accounts.filter(account=>Object.entries(filters).every(([field,value])=>String(account[field as keyof Account]||'').toLocaleLowerCase('es').includes(value.trim().toLocaleLowerCase('es')))),[accounts,filters]);
  const pages=Math.max(1,Math.ceil(rows.length/pageSize));
  const current=Math.min(page,pages);
  const visible=rows.slice((current-1)*pageSize,current*pageSize);
  const filter=(field:keyof typeof filters,value:string)=>{setFilters(prev=>({...prev,[field]:value}));setPage(1);setSelected('');};
  return <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/40 p-3"><section role="dialog" aria-modal="true" aria-label="Buscar cuenta" className="flex max-h-[94vh] w-full max-w-5xl flex-col rounded-lg bg-white p-5 text-xs shadow-xl"><header className="flex items-center justify-between"><h2 className="text-lg font-semibold text-blue-950">Buscar cuenta</h2><button type="button" aria-label="Cerrar búsqueda de cuentas" onClick={onClose} className="cursor-pointer rounded px-2 text-2xl hover:bg-gray-100">×</button></header><p className="mt-1 text-slate-500">Filtra la tabla y selecciona una cuenta.</p>
    <div className="mt-3 grid gap-2 md:grid-cols-4">{([['nombre_empresa','Empresa'],['id_cuenta','Código CRM'],['pais_cuenta','País'],['correo_principal','Correo']] as const).map(([field,label])=><label key={field} className="text-xs font-medium">{label}<input type="search" value={filters[field]} onChange={event=>filter(field,event.target.value)} className="mt-1 w-full rounded border px-2 py-1.5 text-xs" /></label>)}</div>
    <div className="mt-3 min-h-0 flex-1 overflow-auto rounded border"><table className="w-full text-left text-xs"><thead className="sticky top-0 bg-blue-950 text-white"><tr>{['','Empresa','Código CRM','País','Correo'].map(label=><th key={label} className="px-2 py-2 font-medium">{label}</th>)}</tr></thead><tbody>{visible.map(account=><tr key={account.id_cuenta} onClick={()=>setSelected(account.id_cuenta)} onDoubleClick={()=>onSelect(account.id_cuenta)} className={`cursor-pointer border-t hover:bg-blue-50 ${selected===account.id_cuenta?'bg-blue-100':''}`}><td className="px-2 py-1.5"><input type="radio" aria-label={`Seleccionar ${account.nombre_empresa||account.id_cuenta}`} checked={selected===account.id_cuenta} onChange={()=>setSelected(account.id_cuenta)} className="cursor-pointer" /></td><td className="px-2 py-1.5">{account.nombre_empresa||'—'}</td><td className="px-2 py-1.5">{account.id_cuenta}</td><td className="px-2 py-1.5">{account.pais_cuenta||'—'}</td><td className="px-2 py-1.5">{account.correo_principal||'—'}</td></tr>)}</tbody></table>{!visible.length&&<p className="p-4 text-center text-slate-500">No hay cuentas con esos filtros.</p>}</div>
    <footer className="mt-3 flex flex-wrap items-center justify-between gap-2"><span className="text-slate-500">{rows.length} cuentas · Página {current} de {pages} · 30 por página</span><div className="flex items-center gap-1"><button type="button" disabled={current===1} onClick={()=>setPage(1)} className="rounded border px-2 py-1 enabled:cursor-pointer enabled:hover:bg-blue-50 disabled:opacity-40">«</button><button type="button" disabled={current===1} onClick={()=>setPage(current-1)} className="rounded border px-2 py-1 enabled:cursor-pointer enabled:hover:bg-blue-50 disabled:opacity-40">Anterior</button>{Array.from({length:Math.min(5,pages)},(_,index)=>Math.max(1,Math.min(pages-4,current-2))+index).map(number=><button key={number} type="button" onClick={()=>setPage(number)} className={`cursor-pointer rounded border px-2 py-1 hover:bg-blue-50 ${number===current?'bg-blue-100':''}`}>{number}</button>)}<button type="button" disabled={current===pages} onClick={()=>setPage(current+1)} className="rounded border px-2 py-1 enabled:cursor-pointer enabled:hover:bg-blue-50 disabled:opacity-40">Siguiente</button><button type="button" disabled={current===pages} onClick={()=>setPage(pages)} className="rounded border px-2 py-1 enabled:cursor-pointer enabled:hover:bg-blue-50 disabled:opacity-40">»</button></div><button type="button" disabled={!rows.some(row=>row.id_cuenta===selected)} onClick={()=>onSelect(selected)} className="rounded bg-blue-950 px-3 py-2 text-white enabled:cursor-pointer enabled:hover:bg-blue-900 disabled:opacity-50">Seleccionar cuenta</button></footer></section></div>;
}
