'use client';
import TableFilters from '@/app/components/TableFilters';
import {useEffect,useState} from 'react';

import {CuentaService} from '@/app/service/CuentaService';
const pageSize=30;
type Account={id_cuenta:string;nombre_empresa?:string;pais_cuenta?:string;correo_principal?:string};
export default function AccountSearchModal({onSelect,onClose}:{accounts?:Account[];onSelect:(id:string)=>void;onClose:()=>void}){
  const [filters,setFilters]=useState({nombre_empresa:'',id_cuenta:'',pais_cuenta:'',correo_principal:''});
  const [selected,setSelected]=useState(''),[page,setPage]=useState(1);
  useEffect(()=>{const close=(event:KeyboardEvent)=>{if(event.key==='Escape')onClose();};window.addEventListener('keydown',close);return()=>window.removeEventListener('keydown',close);},[onClose]);
  const [visible,setVisible]=useState<Account[]>([]),[total,setTotal]=useState(0),[loading,setLoading]=useState(true),[error,setError]=useState('');
  useEffect(()=>{const controller=new AbortController();const timer=setTimeout(()=>{setLoading(true);setError('');CuentaService.getCuentas({limit:pageSize,page,clienteFiltro:filters.nombre_empresa,codigoCrmFiltro:filters.id_cuenta,paisFiltro:filters.pais_cuenta,correoFiltro:filters.correo_principal},{signal:controller.signal}).then(data=>{if(!controller.signal.aborted){setVisible(data.rows);setTotal(data.total);}}).catch(reason=>{if(!controller.signal.aborted)setError(reason.message);}).finally(()=>{if(!controller.signal.aborted)setLoading(false);});},250);return()=>{clearTimeout(timer);controller.abort();};},[filters,page]);
  const pages=Math.max(1,Math.ceil(total/pageSize)),current=page;
  const filter=(field:keyof typeof filters,value:string)=>{setFilters(prev=>({...prev,[field]:value}));setPage(1);setSelected('');};
  return <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/40 p-3"><section role="dialog" aria-modal="true" aria-label="Buscar cuenta" className="flex max-h-[94vh] w-full max-w-5xl flex-col rounded-lg bg-white p-5 text-xs shadow-xl"><header className="flex items-center justify-between"><h2 className="text-lg font-semibold text-blue-950">Buscar cuenta</h2><button type="button" aria-label="Cerrar búsqueda de cuentas" onClick={onClose} className="cursor-pointer rounded px-2 text-2xl hover:bg-gray-100">×</button></header><p className="mt-1 text-slate-500">Filtra la tabla y selecciona una cuenta.</p>
    {loading&&<p role="status" className="mt-2">Cargando cuentas...</p>}{error&&<p role="alert" className="text-red-700">{error}</p>}
    <div className="mt-3 min-h-0 flex-1 overflow-auto rounded border"><TableFilters>{([['nombre_empresa','Empresa'],['id_cuenta','CRM'],['pais_cuenta','Pa\u00eds'],['correo_principal','Correo']] as const).map(([field,label])=><div key={field}><label className="block text-xs font-extralight text-gray-600"><span className="mb-1 block">{label}</span><input aria-label={label} type="search" value={filters[field]} onChange={event=>filter(field,event.target.value)} className="mt-1 w-full rounded border bg-white px-2 py-1.5 text-xs text-black"/></label></div>)}</TableFilters><table className="w-full text-left text-xs"><thead className="sticky top-0 bg-blue-950 text-white"><tr><th className="px-2 py-2"></th>{([['nombre_empresa','Empresa'],['id_cuenta','CRM'],['pais_cuenta','Pa\u00eds'],['correo_principal','Correo']] as const).map(([field,label])=><th key={field} className="px-2 py-2 font-medium">{label}</th>)}</tr></thead><tbody>{visible.map(account=><tr key={account.id_cuenta} onClick={()=>setSelected(account.id_cuenta)} onDoubleClick={()=>onSelect(account.id_cuenta)} className={`cursor-pointer border-t hover:bg-blue-50 ${selected===account.id_cuenta?'bg-blue-100':''}`}><td className="px-2 py-1.5"><input type="radio" aria-label={`Seleccionar ${account.nombre_empresa||account.id_cuenta}`} checked={selected===account.id_cuenta} onChange={()=>setSelected(account.id_cuenta)} className="cursor-pointer" /></td><td className="px-2 py-1.5">{account.nombre_empresa||'—'}</td><td className="px-2 py-1.5">{account.id_cuenta}</td><td className="px-2 py-1.5">{account.pais_cuenta||'—'}</td><td className="px-2 py-1.5">{account.correo_principal||'—'}</td></tr>)}</tbody></table>{!loading&&!error&&!visible.length&&<p className="p-4 text-center text-slate-500">No hay cuentas con esos filtros.</p>}</div>
    <footer className="mt-3 flex flex-wrap items-center justify-between gap-2"><span className="text-slate-500">{total} cuentas · Página {current} de {pages} · 30 por página</span><div className="flex items-center gap-1"><button type="button" disabled={current===1} onClick={()=>setPage(1)} className="rounded border px-2 py-1 enabled:cursor-pointer enabled:hover:bg-blue-50 disabled:opacity-40">«</button><button type="button" disabled={current===1} onClick={()=>setPage(current-1)} className="rounded border px-2 py-1 enabled:cursor-pointer enabled:hover:bg-blue-50 disabled:opacity-40">Anterior</button>{Array.from({length:Math.min(5,pages)},(_,index)=>Math.max(1,Math.min(pages-4,current-2))+index).map(number=><button key={number} type="button" onClick={()=>setPage(number)} className={`cursor-pointer rounded border px-2 py-1 hover:bg-blue-50 ${number===current?'bg-blue-100':''}`}>{number}</button>)}<button type="button" disabled={current===pages} onClick={()=>setPage(current+1)} className="rounded border px-2 py-1 enabled:cursor-pointer enabled:hover:bg-blue-50 disabled:opacity-40">Siguiente</button><button type="button" disabled={current===pages} onClick={()=>setPage(pages)} className="rounded border px-2 py-1 enabled:cursor-pointer enabled:hover:bg-blue-50 disabled:opacity-40">»</button></div><button type="button" disabled={loading||!visible.some(row=>row.id_cuenta===selected)} onClick={()=>onSelect(selected)} className="rounded bg-blue-950 px-3 py-2 text-white enabled:cursor-pointer enabled:hover:bg-blue-900 disabled:opacity-50">Seleccionar cuenta</button></footer></section></div>;
}
