'use client';
import {useEffect,useState} from 'react';
import SearchableSelect from './SearchableSelect';
import apiClient from '@/app/apiClient';
export default function EntityExcelImport({entity,mode}:{entity:'cuentas'|'contactos';mode:string}) {
  const [fields,setFields]=useState<string[]>([]),[headers,setHeaders]=useState<string[]>([]),[rows,setRows]=useState<any[]>([]),[mapping,setMapping]=useState<Record<string,string>>({}),[preview,setPreview]=useState<any>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false);
  useEffect(()=>{apiClient.get('/api/v1/operaciones/importar-entidades').then(r=>setFields(r.data[entity])).catch(e=>setError(e.message));},[entity]);
  async function read(file:File){setBusy(true);setError('');setPreview(null);setRows([]);try{if(file.size>10*1024*1024)throw new Error('El Excel debe ocupar como máximo 10 MB.');const XLSX=await import('xlsx');const book=XLSX.read(await file.arrayBuffer());if(!book.SheetNames.length)throw new Error('El Excel no tiene hojas.');const grid:any[][]=XLSX.utils.sheet_to_json(book.Sheets[book.SheetNames[0]],{header:1,defval:''});if(!grid.length)throw new Error('La hoja está vacía.');const names=grid[0].map(value=>String(value).trim());if(new Set(names).size!==names.length||names.some(name=>!name))throw new Error('Las cabeceras deben tener nombre y ser únicas.');if(grid.length>2001)throw new Error('Divide la importación en archivos de hasta 2.000 filas.');setHeaders(names);setRows(grid.slice(1).filter(row=>row.some(value=>String(value).trim())).map(row=>Object.fromEntries(names.map((name,i)=>[name,row[i]??'']))));setMapping(Object.fromEntries(fields.map(field=>[field,names.includes(field)?field:''])));}catch(e:any){setError(e.message);}finally{setBusy(false);}}
  async function send(action:string){setBusy(true);setError('');try{const mapped=rows.map(row=>Object.fromEntries(fields.filter(field=>mapping[field]).map(field=>[field,row[mapping[field]]])));const result=await apiClient.post('/api/v1/operaciones/importar-entidades',{entity,mode,rows:mapped,action,fingerprint:preview?.fingerprint});setPreview(result.data);}catch(e:any){setError(e.message);if(e.status===409)setPreview(null);}finally{setBusy(false);}}
  return <section className="space-y-4"><h2 className="text-xl font-semibold">Importar {entity}</h2><p>Selecciona el Excel, asocia sus columnas y revisa las diferencias antes de aplicar. Las identidades existentes se conservan.</p><input type="file" accept=".xls,.xlsx" disabled={busy} className="cursor-pointer rounded border p-2 hover:bg-blue-50 disabled:cursor-not-allowed" onChange={e=>{if(e.target.files?.[0])void read(e.target.files[0]);}}/>{rows.length>0&&<><p>{rows.length} filas · primera hoja</p><div className="grid gap-3 md:grid-cols-3">{fields.map(field=><SearchableSelect key={field} label={field} value={mapping[field]||''} onChange={value=>{setMapping(current=>({...current,[field]:value}));setPreview(null);}} options={[{value:'',label:'No importar'},...headers.map(name=>({value:name,label:name}))]} disabled={busy||preview?.applied}/>)}</div><button type="button" disabled={busy||preview?.applied} className="cursor-pointer rounded bg-blue-950 px-4 py-2 text-white hover:bg-blue-800 disabled:cursor-not-allowed disabled:opacity-50" onClick={()=>void send('preview')}>Revisar diferencias</button></>}{busy&&<p role="status">Procesando…</p>}{error&&<p role="alert" className="text-red-700">{error}</p>}{preview&&<><div className="max-h-96 overflow-auto"><table className="w-full text-left text-sm"><thead><tr>{['Fila','Identidad','Operación','Cambios'].map(label=><th key={label} className="p-2">{label}</th>)}</tr></thead><tbody>{preview.plan.map((item:any)=><tr key={item.id} className="border-t"><td className="p-2">{item.line}</td><td className="p-2">{item.id}</td><td className="p-2">{item.operation}</td><td className="p-2">{item.changes.map((key:string)=>`${key}: ${item.before?.[key]??'vacío'} → ${item.after[key]}`).join('; ')}</td></tr>)}</tbody></table></div>{preview.applied?<p role="status" className="text-green-800">Importación aplicada. Este resultado corresponde a los cambios guardados.</p>:<button type="button" disabled={busy} className="cursor-pointer rounded bg-blue-950 px-4 py-2 text-white hover:bg-blue-800 disabled:cursor-not-allowed disabled:opacity-50" onClick={()=>void send('apply')}>Aplicar estos cambios</button>}</>}</section>;
}
