"use client";
import {useEffect,useState} from 'react';
import {ServicioService} from '@/app/service/ServicioService';
import {RevistaService} from '@/app/service/RevistaService';
import {emptyLinea,ServiceWizardBody,type Linea} from './ProposalServices';
export default function ServicePickerModal({onConfirm,onClose}:{onConfirm:(line:Linea)=>void;onClose:()=>void}) {
  const [services,setServices]=useState<any[]>([]),[publications,setPublications]=useState<any[]>([]),[line,setLine]=useState(emptyLinea),[step,setStep]=useState(1),[error,setError]=useState(''),[loading,setLoading]=useState(true);
  useEffect(()=>{let active=true;Promise.all([ServicioService.getServicios(),RevistaService.getRevistas()]).then(([s,p])=>{if(active){setServices(s.filter((item:any)=>item.disponibilidad!=='Oculto'));setPublications(p);}}).catch(e=>{if(active)setError(e.message);}).finally(()=>{if(active)setLoading(false);});return()=>{active=false;};},[]);
  useEffect(()=>{const close=(e:KeyboardEvent)=>{if(e.key==='Escape')onClose();};window.addEventListener('keydown',close);return()=>window.removeEventListener('keydown',close);},[onClose]);
  const groups=Array.from(new Map(services.map(service=>[service.id_medio,service.nombre_medio || service.id_medio])).entries()).map(([id,nombre])=>({id,nombre}));
  const patch=(value:Partial<Linea>)=>setLine(current=>({...current,...value}));
  return <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/40 p-6"><section role="dialog" aria-modal="true" aria-label="Seleccionar servicio" className="max-h-[90vh] w-full max-w-5xl overflow-y-auto rounded-lg bg-white p-6 shadow-2xl"><div className="mb-4 flex items-center justify-between"><div><h3 className="text-lg font-semibold text-blue-950">Seleccionar servicio</h3><p className="text-sm text-gray-600">Fase {step}: {step===1?'elige el canal':step===2?'elige el servicio':'configura las especificaciones'}.</p></div><button type="button" onClick={onClose} aria-label="Cerrar selector de servicios" className="cursor-pointer rounded px-2 py-1 text-gray-600 hover:bg-gray-100">×</button></div><div className="mb-4 flex gap-2 border-y py-3">{['Canal','Servicio','Especificaciones'].map((label,index)=><button key={label} type="button" disabled={index+1>step} onClick={()=>setStep(index+1)} className={`rounded-full px-3 py-1 text-sm enabled:cursor-pointer enabled:hover:bg-blue-50 disabled:cursor-default ${index+1===step?'bg-blue-100 text-blue-800':'bg-gray-100'}`}>{index+1} · {label}</button>)}</div>{error?<p role="alert">{error}</p>:loading?<p>Cargando servicios…</p>:<ServiceWizardBody step={step} linea={line} grupos={groups} servicios={services} revistas={publications} onPatch={patch} onStep={setStep} onSelectService={id=>{const s=services.find(item=>item.id_servicio===id);patch({id_servicio:id,grupo_servicio:s.id_medio,producto:s.nombre_servicio_es,medio:s.medio_servicio_es,publicacion:[s.edicion_servicio_es,s.publicacion_servicio_es].filter(Boolean).join(' '),descripcion_linea:[s.edicion_servicio_es,s.publicacion_servicio_es].filter(Boolean).join(' '),especificaciones_linea:s.nombre_servicio_es,precio_tarifa:Number(s.precio_tarifa ?? s.precio_servicio)||0,precio_unitario:Number(s.precio_tarifa ?? s.precio_servicio)||0,deadline_publicacion:s.fecha_deadline_servicio,fecha_publicacion_publicacion:s.fecha_publicacion_servicio,servicio_personalizado:false});}} onApplyPublication={id=>{const p=publications.find(item=>item.id_publicacion===id);patch({id_publicacion:id,deadline_publicacion:p?.deadline_materiales || '',fecha_publicacion_publicacion:p?.fecha_publicacion || ''});}}/>}<div className="mt-5 flex justify-end"><button type="button" disabled={step<3||!line.id_servicio||!line.producto.trim()} onClick={()=>onConfirm(line)} className="rounded-lg bg-blue-950 px-4 py-2 text-sm text-white enabled:cursor-pointer enabled:hover:bg-blue-900 disabled:cursor-default disabled:bg-gray-300">Confirmar</button></div></section></div>;
}
