'use client';
import {useCallback,useEffect,useState} from 'react';
import Link from 'next/link';
import RecurringChargeManageModal from '@/app/dashboard/direccion/tesoreria/RecurringChargeManageModal';
import SearchableSelect from '@/app/components/SearchableSelect';
import RecurringChargeForm,{newCharge} from '@/app/dashboard/direccion/tesoreria/RecurringChargeForm';
import {api,button,CardEditor,CardTable,date,ForecastItems,money} from './CardComponents';
const tabs=['Tickets','Cargos recurrentes (suscripciones)','Liquidaciones anteriores','Próxima liquidación'];
export default function CardDetail({id}:{id:string}){
  const [editingCharge,setEditingCharge]=useState('');
  const base=`/api/v1/admin/tarjetas/${encodeURIComponent(id)}`;
  const [data,setData]=useState<any>(null),[error,setError]=useState(''),[tab,setTab]=useState(tabs[0]),[edit,setEdit]=useState(false),[busy,setBusy]=useState(false);
  const [tickets,setTickets]=useState<any[]>([]),[charges,setCharges]=useState<any[]>([]),[ticket,setTicket]=useState(''),[charge,setCharge]=useState(''),[due,setDue]=useState('');
  const [create,setCreate]=useState(false),[schedule,setSchedule]=useState<any>(newCharge),[vat,setVat]=useState(true),[providers,setProviders]=useState<any[]>([]),[provider,setProvider]=useState('');
  const load=useCallback(async()=>{const [d,t,c,p]=await Promise.all([api(base),api('/api/v1/admin/tickets'),api(base+'/cargos'),api('/api/v1/admin/proveedores')]);setData(d);setTickets(t);setCharges(c);setProviders(p);},[base]);
  useEffect(()=>{load().catch(e=>setError(e.message));},[load]);
  const save=async(path:string,body:any)=>{if(busy)return;setBusy(true);setError('');try{await api(base+path,body);setTicket('');setCharge('');setDue('');setCreate(false);await load();}catch(e:any){setError(e.message);}finally{setBusy(false);}};
  if(!data)return <main className="p-8">{error?<p role="alert">{error}</p>:'Cargando tarjeta…'}</main>;
  const {card,next}=data;
  return <main className="min-h-screen space-y-6 bg-gray-100 p-6 text-slate-900 lg:p-12"><Link className="cursor-pointer text-blue-900 hover:underline" href="/dashboard/administracion/tarjetas">← Tarjetas</Link><section className="rounded bg-white p-6"><header className="flex justify-between"><h1 className="text-2xl font-semibold">{card.codigo} · {card.nombre}</h1><button className={button} onClick={()=>setEdit(true)}>Editar datos</button></header><p className="mt-3">{card.banco} · **** {card.ultimos_digitos} · {card.tipo==='p3'?'P3':'Personal'} · {card.estado}</p><p className="mt-2">Liquidación cada {card.periodicidad_meses} mes(es). Cierre: {date(card.proximo_cierre)||'Sin configurar'}. Cargo en banco: {date(card.proxima_liquidacion)||'Sin configurar'}.</p><p className="mt-4 whitespace-pre-wrap text-gray-600">{card.descripcion||'Sin descripción.'}</p></section>
    {error&&<p role="alert" className="rounded bg-red-50 p-3 text-red-700">{error}</p>}
    <div role="tablist" aria-label="Información de la tarjeta" className="flex flex-wrap gap-2">{tabs.map(t=><button key={t} role="tab" aria-selected={tab===t} onClick={()=>setTab(t)} className={`${button} ${tab===t?'border-blue-950 font-semibold':''}`}>{t}</button>)}</div>
    <section role="tabpanel" aria-label={tab} className="space-y-5 rounded bg-white p-5">
    {tab===tabs[0]&&<><Link className="inline-block cursor-pointer text-blue-900 underline hover:text-blue-600" href={`/dashboard/administracion/proveedores/tickets/anadir?id_tarjeta=${encodeURIComponent(id)}`}>Añadir ticket</Link><div className="grid items-end gap-3 md:grid-cols-3"><div><p className="mb-1 text-sm">Asignar ticket existente</p><SearchableSelect label="Ticket" value={ticket} onChange={setTicket} options={tickets.filter(t=>!t.id_tarjeta||t.id_tarjeta===id).map(t=>({value:String(t.id_ticket),label:`${t.id_ticket} · ${t.fecha_ticket} · ${t.proveedor} · ${money(t.importe_total)}`}))}/></div><div><p className="mb-1 text-sm">Sustituye una previsión de suscripción (opcional)</p><SearchableSelect label="Vencimiento de suscripción" value={due} onChange={setDue} options={[{value:'',label:'Consumo independiente'},...data.dues.filter((d:any)=>next&&d.fecha>=next.inicio&&d.fecha<=next.cierre).map((d:any)=>({value:d.id,label:`${date(d.fecha)} · ${d.descripcion} · ${money(d.importe)}`}))]}/></div><button className={button} disabled={busy||!ticket} onClick={()=>save('/tickets',{id_ticket:ticket,id_vencimiento_tarjeta:due})}>Guardar asociación</button></div><p className="text-sm text-gray-600">Si el ticket justifica una suscripción prevista, selecciona su vencimiento para contar el importe real una sola vez.</p><CardTable rows={data.tickets.map((t:any)=>({...t,fecha:date(t.fecha),importe:money(t.importe_total)}))} columns={[{key:'id_ticket',label:'Ticket'},{key:'fecha',label:'Fecha'},{key:'proveedor',label:'Proveedor'},{key:'importe',label:'Importe'},{key:'ambito',label:'Ámbito'},{key:'id_vencimiento_tarjeta',label:'Suscripción',render:t=>t.id_vencimiento_tarjeta?'Vinculada':'Consumo independiente'},{key:'documento_src',label:'Archivo',render:t=>t.documento_src?<a className="cursor-pointer text-blue-900 underline hover:text-blue-600" href={t.documento_src} target="_blank" rel="noreferrer">Ver ticket</a>:'Sin archivo'}]}/></>}
    {tab===tabs[1]&&<><div className="flex flex-wrap items-end gap-3"><div className="min-w-72 flex-1"><p className="mb-1 text-sm">Asociar cargo previsto</p><SearchableSelect label="Cargo recurrente" value={charge} onChange={setCharge} options={charges.filter(c=>!c.id_tarjeta).map(c=>({value:String(c.id_cargo_recurrente),label:`${c.nombre_proveedor||'Otro'} · ${c.programacion.map((r:any)=>r.descripcion).join(', ')} · ${c.id_cargo_recurrente}`}))}/></div><button className={button} disabled={busy||!charge} onClick={()=>save('/cargos',{id_cargo_recurrente:charge})}>Asociar</button><button className={button} onClick={()=>setCreate(!create)}>{create?'Cerrar formulario':'Nueva suscripción'}</button></div>{create&&<div className="space-y-4 rounded border p-4"><SearchableSelect label="Proveedor de la suscripción" value={provider} onChange={setProvider} options={[{value:'',label:'Otro (sin proveedor)'},...providers.map(p=>({value:p.id_proveedor,label:p.nombre_proveedor}))]}/><RecurringChargeForm fixedBank={card.banco} value={{...schedule,banco_pago:card.banco}} onChange={setSchedule} vat={vat} onVatChange={setVat}/><button className={button} disabled={busy} onClick={()=>save('/cargos',{...schedule,action:'create',tipo_cargo:provider?'proveedor':'otro',id_proveedor:provider||null,programacion:schedule.programacion.map((r:any)=>({...r,base_imponible:Math.round(Number(r.total_iva)/(vat?1.21:1)*100)/100}))})}>Guardar suscripción</button></div>}<CardTable rows={data.charges.map((c:any)=>({...c,descripcion:c.programacion.map((r:any)=>r.descripcion).join(', '),importe:money(c.programacion.reduce((n:number,r:any)=>n+Number(r.total_iva),0))}))} columns={[{key:'id_cargo_recurrente',label:'Código'},{key:'descripcion',label:'Descripción'},{key:'importe',label:'Importes programados'},{key:'tipo_programacion',label:'Programación'},{key:'acciones',label:'Acciones',render:c=><div className="flex gap-2"><button className={button} onClick={()=>setEditingCharge(String(c.id_cargo_recurrente))}>Editar</button><button className={button} disabled={busy} onClick={()=>save('/cargos',{id_cargo_recurrente:c.id_cargo_recurrente,remove:true})}>Desvincular</button></div>}]}/></>}
    {tab===tabs[2]&&<>{!data.history.length&&<p>No hay liquidaciones anteriores.</p>}{data.history.map((h:any)=><details key={h.id} className="rounded border"><summary className="cursor-pointer p-4 hover:bg-blue-50">{date(h.fecha)} · {money(h.real)} · {h.estado} · Previsto: {money(h.previsto)}</summary><div className="space-y-3 border-t p-4"><p>Período {date(h.inicio)} — {date(h.cierre)}. Diferencia: {money(Number(h.real)-Number(h.previsto))}.</p><p>{h.comentario}</p><p>Movimientos: {(h.detalle.movimientos||[]).map((m:any)=>m.id).join(', ')}</p><ForecastItems items={h.detalle.items||[]}/></div></details>)}</>}
    {tab===tabs[3]&&(next?<><h2 className="text-lg font-semibold">{money(next.total)} previstos para el {date(next.fecha)}</h2><p>Consumos del {date(next.inicio)} al {date(next.cierre)}. La previsión cambia al añadir tickets o modificar las suscripciones hasta que se confirme en Conciliación.</p><ForecastItems items={next.items}/><p className="text-sm text-gray-600">En Conciliación, selecciona el cargo bancario y pulsa Liquidación tarjeta. Confirmar guardará esta previsión y abrirá el siguiente período.</p></>:<p>Edita la tarjeta para configurar las fechas del primer período.</p>)}
    </section>{edit&&<CardEditor card={card} close={()=>setEdit(false)} done={()=>{setEdit(false);load().catch(e=>setError(e.message));}}/>}
    {editingCharge&&<RecurringChargeManageModal id={editingCharge} endpoint={`${base}/cargos/${editingCharge}`} fixedBank={card.banco} action="edit" onClose={()=>setEditingCharge('')} onSaved={()=>{setEditingCharge('');load().catch(e=>setError(e.message));}}/>}
  </main>;
}
