'use client';
import {useEffect,useState} from 'react';
import {useRouter} from 'next/navigation';
import Link from 'next/link';
import DatePartsInput from '@/app/components/DatePartsInput';
import SearchableSelect from '@/app/components/SearchableSelect';
import {api,button,input,iso} from './CardComponents';
import TicketSupplier,{emptySupplier} from './TicketSupplier';
export default function AddTicket(){
  const router=useRouter();
  const [newProvider,setNewProvider]=useState(false),[supplier,setSupplier]=useState(emptySupplier);
  const [providers,setProviders]=useState<any[]>([]),[cards,setCards]=useState<any[]>([]),[error,setError]=useState(''),[busy,setBusy]=useState(false),[file,setFile]=useState<File|null>(null);
  const [form,setForm]=useState({fecha:'',ambito:'P3',id_proveedor:'',base:'',total:'',forma_pago:'efectivo',id_tarjeta:''});
  useEffect(()=>{const q=new URLSearchParams(window.location.search),now=new Date();setForm(f=>({...f,fecha:`${now.getDate()}/${now.getMonth()+1}/${now.getFullYear()}`,ambito:q.get('ambito')==='GM'?'GM':'P3',id_proveedor:q.get('id_proveedor')||'',id_tarjeta:q.get('id_tarjeta')||'',forma_pago:q.has('id_tarjeta')?'tarjeta':'efectivo'}));Promise.all([api('/api/v1/admin/proveedores'),api('/api/v1/admin/tarjetas')]).then(([p,c])=>{setProviders(p);setCards(c);}).catch(e=>setError(e.message));},[]);
  const change=(key:string,value:string)=>setForm(f=>({...f,[key]:value}));
  const submit=async(e:React.FormEvent)=>{e.preventDefault();if(busy)return;setBusy(true);setError('');try{
    if(!file)throw new Error('Adjunta un PDF, JPG o PNG.');
    const card=cards.find(c=>c.id_tarjeta===form.id_tarjeta&&c.estado==='activa');
    if(form.forma_pago==='tarjeta'&&!card)throw new Error('Selecciona una tarjeta activa.');
    const body=new FormData();body.set('file',file);body.set('data',JSON.stringify({fecha_ticket:iso(form.fecha),ambito:form.ambito,id_proveedor:newProvider?null:form.id_proveedor,...(newProvider?{nuevo_proveedor:supplier}:{}),base_imponible:form.ambito==='P3'?Number(form.base):null,importe_total:Number(form.total),forma_pago:form.forma_pago,id_tarjeta:form.forma_pago==='tarjeta'?card.id_tarjeta:null,tarjeta_ultimos_digitos:form.forma_pago==='tarjeta'?card.ultimos_digitos:'',tarjeta_banco:form.forma_pago==='tarjeta'?card.banco:''}));
    const r=await fetch('/api/v1/admin/tickets',{method:'POST',body});const data=await r.json();if(!r.ok)throw new Error(data.message);
    router.push(form.forma_pago==='tarjeta'?`/dashboard/administracion/tarjetas/${encodeURIComponent(card.id_tarjeta)}`:'/dashboard/administracion/proveedores/tickets');
  }catch(e:any){setError(e.message);}finally{setBusy(false);}};
  return <main className="min-h-screen bg-gray-100 p-6 text-slate-900 lg:p-12"><Link href="/dashboard/administracion/proveedores/tickets" className="cursor-pointer text-blue-900 hover:underline">← Tickets</Link><h1 className="my-5 text-2xl font-semibold">Añadir ticket</h1><form onSubmit={submit} className="max-w-3xl space-y-5 rounded bg-white p-6"><fieldset disabled={busy} className="space-y-5"><DatePartsInput label="Fecha del ticket" value={form.fecha} onChange={v=>change('fecha',v)}/><label className="block">Ámbito<select className={`${input} cursor-pointer hover:border-blue-950`} value={form.ambito} onChange={e=>change('ambito',e.target.value)}><option>P3</option><option>GM</option></select></label><label className="flex cursor-pointer gap-2 rounded p-2 hover:bg-blue-50"><input type="checkbox" className="cursor-pointer" checked={newProvider} onChange={e=>setNewProvider(e.target.checked)}/>Registrar un proveedor nuevo</label>{newProvider?<TicketSupplier value={supplier} onChange={setSupplier}/>:<div><p className="mb-1">Proveedor</p><SearchableSelect required label="Proveedor" value={form.id_proveedor} onChange={v=>change('id_proveedor',v)} options={providers.map(p=>({value:p.id_proveedor,label:p.nombre_proveedor}))}/><Link className="mt-2 inline-block cursor-pointer text-sm text-blue-900 underline hover:text-blue-600" href="/dashboard/administracion/proveedores" target="_blank">Gestionar proveedores</Link></div>}<div className="grid gap-4 sm:grid-cols-2">{form.ambito==='P3'&&<label>Base imponible<input required type="number" min="0" step="0.01" className={input} value={form.base} onChange={e=>change('base',e.target.value)}/></label>}<label>Importe total<input required type="number" min="0.01" step="0.01" className={input} value={form.total} onChange={e=>change('total',e.target.value)}/></label></div><label className="block">Forma de pago<select className={`${input} cursor-pointer hover:border-blue-950`} value={form.forma_pago} onChange={e=>change('forma_pago',e.target.value)}><option value="efectivo">Efectivo</option><option value="tarjeta">Tarjeta</option></select></label>{form.forma_pago==='tarjeta'&&<div><p className="mb-1">Tarjeta</p><SearchableSelect required label="Tarjeta" value={form.id_tarjeta} onChange={v=>change('id_tarjeta',v)} options={cards.filter(c=>c.estado==='activa').map(c=>({value:c.id_tarjeta,label:`${c.codigo} · ${c.nombre} · ${c.banco} · ${c.ultimos_digitos}`}))}/></div>}<label className="block">Archivo (PDF, JPG o PNG, hasta 15 MB)<input required type="file" accept="application/pdf,image/jpeg,image/png" className="mt-2 block w-full cursor-pointer rounded border p-2 hover:bg-gray-50" onChange={e=>setFile(e.target.files?.[0]||null)}/></label></fieldset>{error&&<p role="alert" className="text-red-700">{error}</p>}<button className={button} disabled={busy}>{busy?'Guardando…':'Guardar ticket'}</button></form></main>;
}
