'use client';
import {useEffect,useState} from 'react';
import Link from 'next/link';
import apiClient from '@/app/apiClient';
export default function SubscriptionRenewalModal({subscription,onClose,onSaved}:{subscription:any;onClose:()=>void;onSaved?:()=>void}){
  const [first,setFirst]=useState(String(Number(subscription.num_final||0)+1)),[last,setLast]=useState(String(Number(subscription.num_final||0)+Math.max(1,Number(subscription.num_final||0)-Number(subscription.num_inicial||0)+1))),[preview,setPreview]=useState<any>(null),[busy,setBusy]=useState(false),[error,setError]=useState('');
  useEffect(()=>{const close=(e:KeyboardEvent)=>{if(e.key==='Escape')onClose();};window.addEventListener('keydown',close);return()=>window.removeEventListener('keydown',close);},[onClose]);
  async function send(confirm=false){setBusy(true);setError('');try{const result=await apiClient.post(`/api/v1/admin/suscripciones/${encodeURIComponent(subscription.id_suscripcion)}/renovar`,{first,last,confirm});setPreview(result.data);if(confirm)onSaved?.();}catch(e:any){setError(e.message);}finally{setBusy(false);}}
  return <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/60 p-4"><section role="dialog" aria-modal="true" aria-label="Renovar suscripción" className="w-full max-w-xl space-y-4 rounded bg-white p-6"><header className="flex justify-between"><h3 className="font-semibold">Renovar · {subscription.nombre_empresa}</h3><button type="button" onClick={onClose} aria-label="Cerrar" className="cursor-pointer rounded px-3 text-2xl hover:bg-blue-50">×</button></header><p>{subscription.revista} · {subscription.edicion}</p><div className="flex gap-3">{[['Primer número',first,setFirst],['Último número',last,setLast]].map(([label,value,setter]:any)=><label key={label}>{label}<input type="number" min="1" value={value} disabled={preview?.created} onChange={e=>{setter(e.target.value);setPreview(null);}} className="block w-full rounded border p-2"/></label>)}</div>{error&&<p role="alert" className="text-red-700">{error}</p>}{preview&&<p>{preview.title}. {preview.services} servicios anteriores preparados para revisar. Se crea una sola propuesta en borrador; el contrato actual se conserva.</p>}{preview?.created?<Link className="block cursor-pointer rounded bg-blue-950 p-3 text-white hover:bg-blue-800" href={`/dashboard/comercial/propuestas/${preview.id_propuesta}`}>Completar propuesta de renovación</Link>:<button type="button" disabled={busy} onClick={()=>void send(Boolean(preview))} className="cursor-pointer rounded bg-blue-950 px-4 py-2 text-white hover:bg-blue-800 disabled:cursor-not-allowed disabled:opacity-50">{busy?'Preparando…':preview?'Crear propuesta de renovación':'Revisar renovación'}</button>}</section></div>;
}
