'use client';
import SortableTable from '@/app/components/SortableTable';

import {useState} from 'react';
import DownloadDocumentButton from '@/app/components/DownloadDocumentButton';
import {contractDocumentModel} from '@/app/lib/contractDocumentModel';
export default function ContractDocument({contract}:{contract:any}){
 const [version,setVersion]=useState<'original'|'gm'>('original');const model=contractDocumentModel(contract,version==='gm');
 return <section className="space-y-4"><div className="flex flex-wrap items-center justify-between gap-4"><div role="tablist" aria-label="Versión del contrato" className="flex gap-2">{(['original','gm'] as const).map(value=><button key={value} role="tab" aria-selected={version===value} type="button" onClick={()=>setVersion(value)} className={`cursor-pointer rounded px-4 py-2 ${version===value?'bg-blue-950 text-white hover:bg-blue-900':'bg-white hover:bg-blue-50'}`}>{value==='original'?'Versión original':'Versión GM · Español'}</button>)}</div><DownloadDocumentButton model={model} filename={`${contract.id_contrato}-${version}`}/></div><div className="overflow-x-auto rounded bg-gray-200 p-5"><article lang={version==='gm'?'es':contract.propuesta_snapshot?.idioma_propuesta||'es'} className="mx-auto min-h-[1123px] w-[794px] bg-white p-10 text-black shadow-lg">
 {/* eslint-disable-next-line @next/next/no-img-element */}
 <img src="/invoices/proporcion3-letterhead.png" alt="Proporción 3, S.A." className="mb-8 w-80"/><h1 className="text-2xl font-semibold">{model.title}</h1><p className="mt-2 text-lg">{model.reference}</p><div className="my-6 rounded border p-4"><strong>{model.customer}</strong>{model.details.map((detail,i)=><p key={i}>{detail}</p>)}</div><SortableTable className="w-full text-sm"><thead className="bg-black text-white"><tr>{model.head.map(label=><th key={label} className="p-2 text-left">{label}</th>)}</tr></thead><tbody>{model.body.map((row,i)=><tr key={i} className="border-b">{row.map((cell,j)=><td key={j} className="whitespace-pre-line p-2 align-top">{cell}</td>)}</tr>)}</tbody></SortableTable><dl className="my-6 ml-auto w-80">{model.totals.map(([label,value])=><div key={label} className="flex justify-between border-b py-2"><dt>{label}</dt><dd>{value}</dd></div>)}</dl>{model.payments.length>0&&<SortableTable className="mt-8 w-full text-sm"><thead><tr>{model.paymentHead.map(label=><th key={label} className="border-b p-2 text-left">{label}</th>)}</tr></thead><tbody>{model.payments.map((row,i)=><tr key={i}>{row.map((cell,j)=><td key={j} className="p-2">{cell}</td>)}</tr>)}</tbody></SortableTable>}{model.notes&&<p className="mt-8 whitespace-pre-line text-sm">{model.notes}</p>}</article></div></section>;
}
