'use client';
import {useEffect,useState} from 'react';
import {ContactoService} from '@/app/service/ContactoService';

export default function ContractContactModal({accountId,onClose,onSelect}:{accountId:string;onClose:()=>void;onSelect:(id:string)=>Promise<void>}){
  const [contacts,setContacts]=useState<any[]>([]),[name,setName]=useState(''),[email,setEmail]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);
  useEffect(()=>{ContactoService.getContactos({id_cuenta:accountId}).then(v=>setContacts(Array.isArray(v)?v:[])).catch(()=>setError('No se pudieron cargar los contactos.'));const esc=(e:KeyboardEvent)=>{if(e.key==='Escape')onClose()};window.addEventListener('keydown',esc);return()=>window.removeEventListener('keydown',esc)},[accountId,onClose]);
  async function choose(id:string){setBusy(true);setError('');try{await onSelect(id);onClose()}catch(e:any){setError(e?.message||'No se pudo guardar el contacto.')}finally{setBusy(false)}}
  async function create(){setBusy(true);setError('');try{const contact=await ContactoService.createContacto({id_cuenta:accountId,nombre_contacto:name,email_contacto:email});await onSelect(contact.id_contacto);onClose()}catch(e:any){setError(e?.response?.data?.detail||e?.message||'No se pudo crear el contacto.')}finally{setBusy(false)}}
  return <div role="dialog" aria-modal="true" aria-label="Editar contacto del contrato" className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 p-4"><div className="max-h-[85vh] w-full max-w-xl overflow-auto rounded-xl bg-white p-5 shadow-xl"><div className="mb-4 flex items-center justify-between"><h2 className="text-lg font-semibold text-blue-950">Contacto de la cuenta</h2><button type="button" onClick={onClose} aria-label="Cerrar" className="cursor-pointer rounded px-2 text-2xl hover:bg-gray-100">×</button></div>{error&&<p role="alert" className="mb-3 text-sm text-red-700">{error}</p>}<div className="space-y-2">{contacts.map(c=><button key={c.id_contacto} type="button" disabled={busy} onClick={()=>choose(c.id_contacto)} className="block w-full cursor-pointer rounded border p-3 text-left text-sm hover:bg-blue-50 disabled:cursor-not-allowed disabled:opacity-50">{c.nombre_completo_contacto||c.nombre_contacto} · {c.email_contacto}</button>)}</div><div className="mt-5 border-t pt-4"><h3 className="mb-3 font-medium">Crear contacto personalizado</h3><div className="grid gap-2 sm:grid-cols-2"><input aria-label="Nombre del contacto" placeholder="Nombre" value={name} onChange={e=>setName(e.target.value)} className="rounded border p-2 text-sm"/><input aria-label="Correo del contacto" type="email" placeholder="Correo electrónico" value={email} onChange={e=>setEmail(e.target.value)} className="rounded border p-2 text-sm"/></div><button type="button" disabled={busy||!name.trim()||!email.trim()} onClick={create} className="mt-3 cursor-pointer rounded bg-blue-950 px-4 py-2 text-sm text-white hover:bg-blue-800 disabled:cursor-not-allowed disabled:opacity-50">Crear y seleccionar</button></div></div></div>;
}
