'use client';
import {useEffect,useState} from 'react';
import apiClient from '@/app/apiClient';
import TaskList from './TaskList';
export default function MyTasksPanel(){
 const [open,setOpen]=useState(false),[saving,setSaving]=useState(false),[error,setError]=useState(''),[revision,setRevision]=useState(0),[form,setForm]=useState({nombre:'',descripcion:''});
 useEffect(()=>{if(!open)return;const close=(event:KeyboardEvent)=>{if(event.key==='Escape')setOpen(false);};window.addEventListener('keydown',close);return()=>window.removeEventListener('keydown',close);},[open]);
 const save=async(event:React.FormEvent)=>{event.preventDefault();if(saving)return;setSaving(true);setError('');try{await apiClient.post('/api/v1/tareas/propias',form);setOpen(false);setForm({nombre:'',descripcion:''});setRevision(v=>v+1);}catch(reason:any){setError(reason.response?.data?.message||'No se pudo crear la tarea.');}finally{setSaving(false);}};
 return <section className="space-y-4"><div className="flex justify-end"><button type="button" onClick={()=>{setError('');setOpen(true);}} disabled={saving} className="rounded bg-blue-950 px-4 py-2 text-white enabled:cursor-pointer enabled:hover:bg-blue-900 disabled:cursor-not-allowed disabled:opacity-50">Agregar tarea</button></div><TaskList key={revision} pendingOnly groupedFilters/>{open&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 p-4"><section role="dialog" aria-modal="true" aria-labelledby="own-task-title" className="relative w-full max-w-xl rounded bg-white p-6 text-slate-900 shadow-xl"><button aria-label="Cerrar" type="button" onClick={()=>setOpen(false)} className="absolute right-3 top-2 cursor-pointer rounded px-2 text-2xl hover:bg-gray-100">×</button><h2 id="own-task-title" className="mb-2 text-xl font-semibold">Agregarme una tarea</h2><p className="mb-4 text-sm text-slate-600">Se asignará a ti y aparecerá en tus tareas pendientes.</p><form onSubmit={save} className="space-y-4"><label className="block">Nombre<input autoFocus required maxLength={250} disabled={saving} value={form.nombre} onChange={event=>setForm({...form,nombre:event.target.value})} className="mt-1 block w-full rounded border border-gray-200 p-2 disabled:cursor-not-allowed disabled:bg-gray-100"/></label><label className="block">Descripción<textarea disabled={saving} value={form.descripcion} onChange={event=>setForm({...form,descripcion:event.target.value})} className="mt-1 block min-h-32 w-full rounded border border-gray-200 p-2 disabled:cursor-not-allowed disabled:bg-gray-100"/></label>{error&&<p role="alert" className="text-red-700">{error}</p>}<div className="flex justify-end"><button disabled={saving||!form.nombre.trim()} className="rounded bg-blue-950 px-4 py-2 text-white enabled:cursor-pointer enabled:hover:bg-blue-900 disabled:cursor-not-allowed disabled:opacity-50">{saving?'Guardando…':'Crear tarea'}</button></div></form></section></div>}</section>;
}
