'use client';
import {useEffect,useState} from 'react';
import Link from 'next/link';
import apiClient from '@/app/apiClient';
import TableColumnFilter from '@/app/components/TableColumnFilter';
export const taskStates:Record<string,string>={pendiente:'Pendiente',en_curso:'En curso',completada:'Completada',cancelada:'Cancelada'};
export default function TaskList({employee,pendingOnly=false,groupedFilters=false}:{employee?:string;pendingOnly?:boolean;groupedFilters?:boolean}){
 const [rows,setRows]=useState<any[]>([]),[tab,setTab]=useState('pendientes'),[error,setError]=useState(''),[loading,setLoading]=useState(true),[filters,setFilters]=useState<Record<string,string>>({});
 useEffect(()=>{let active=true;setLoading(true);apiClient.get('/api/v1/tareas'+(employee?'?agente='+encodeURIComponent(employee):'')).then(r=>{if(active){setRows(r.data);setError('');}}).catch(e=>{if(active)setError(e.response?.data?.message||'No se pudieron cargar las tareas.');}).finally(()=>{if(active)setLoading(false);});return()=>{active=false;};},[employee]);
 const columns=[['nombre','Tarea'],['estado','Estado'],['descripcion','Descripción']];
 const value=(row:any,key:string)=>key==='estado'?taskStates[row.estado]:row[key]||'';
 const visible=rows.filter(row=>((pendingOnly||tab==='pendientes')?['pendiente','en_curso'].includes(row.estado):['completada','cancelada'].includes(row.estado))&&columns.every(([key])=>String(value(row,key)).toLocaleLowerCase('es').includes((filters[key]||'').trim().toLocaleLowerCase('es'))));
 return <section className="space-y-4">{pendingOnly?<Link href="/tareas" className="inline-block cursor-pointer text-blue-900 hover:underline">Ver todas mis tareas</Link>:<div role="tablist" aria-label="Estado de las tareas" className="flex gap-2">{['pendientes','terminadas'].map(t=><button key={t} type="button" role="tab" aria-selected={tab===t} onClick={()=>setTab(t)} className={`cursor-pointer rounded px-4 py-2 ${tab===t?'bg-blue-950 text-white hover:bg-blue-900':'bg-white hover:bg-blue-50'}`}>{t==='pendientes'?'Pendientes':'Terminadas'}</button>)}</div>}{groupedFilters&&<details className="rounded border border-gray-200 bg-white"><summary className="cursor-pointer rounded px-4 py-3 text-sm font-semibold text-blue-950 transition hover:bg-blue-50">Filtros{columns.some(([key])=>filters[key]?.trim())?' · Filtros activos':''}</summary><div className="grid gap-3 border-t border-gray-100 p-4 md:grid-cols-3">{columns.map(([key,label])=><label key={key} className="block text-sm text-gray-700"><span className="mb-1 block font-medium">{label}</span>{key==='estado'?<select aria-label="Filtrar Estado" value={filters.estado||''} onChange={event=>setFilters(f=>({...f,estado:event.target.value}))} className="w-full cursor-pointer rounded border border-gray-300 bg-white p-2 text-gray-900 outline-none transition hover:border-blue-950 hover:bg-blue-50 focus:border-blue-950"><option value="">Todos los estados</option>{Object.entries(taskStates).filter(([state])=>!pendingOnly||['pendiente','en_curso'].includes(state)).map(([state,label])=><option key={state} value={label}>{label}</option>)}</select>:<input type="search" aria-label={`Filtrar ${label}`} value={filters[key]||''} onChange={event=>setFilters(f=>({...f,[key]:event.target.value}))} className="w-full rounded border border-gray-300 bg-white p-2 text-gray-900 outline-none focus:border-blue-950"/>}</label>)}</div></details>}{error?<p role="alert" className="text-red-700">{error}</p>:<div className="overflow-x-auto rounded border border-gray-100 bg-white"><table className="w-full text-left text-sm"><thead><tr>{columns.map(([key,label])=><th key={key} className="p-3">{groupedFilters?label:<TableColumnFilter label={label} value={filters[key]||''} onChange={v=>setFilters(f=>({...f,[key]:v}))}/>}</th>)}</tr></thead><tbody>{!loading&&visible.map(row=><tr key={row.id} className="border-t border-gray-100"><td className="p-3"><Link href={'/tareas/'+encodeURIComponent(row.id)+(employee?'?gestion=1':'')} className="cursor-pointer text-blue-900 hover:underline">{row.nombre}</Link></td><td className="p-3">{taskStates[row.estado]}</td><td className="max-w-xl whitespace-pre-line p-3">{row.descripcion}</td></tr>)}{(loading||!visible.length)&&<tr><td colSpan={3} className="p-5">{loading?'Cargando tareas…':'No hay tareas con estos filtros.'}</td></tr>}</tbody></table></div>}</section>;
}
