'use client';
import SortableTable from '@/app/components/SortableTable';

import TableFilters from '@/app/components/TableFilters';
import {useEffect,useState} from 'react';
import Link from 'next/link';
import apiClient from '@/app/apiClient';
import TableColumnFilter from '@/app/components/TableColumnFilter';
export const taskStates:Record<string,string>={pendiente:'Pendiente',en_curso:'En curso',completada:'Completada',cancelada:'Cancelada'};
export default function TaskList({employee,pendingOnly=false}:{employee?:string;pendingOnly?:boolean;groupedFilters?:boolean}){
 const [revision,setRevision]=useState(0);
 useEffect(()=>{const refresh=()=>setRevision(r=>r+1);window.addEventListener('focus',refresh);return()=>window.removeEventListener('focus',refresh);},[]);
 const [rows,setRows]=useState<any[]>([]),[tab,setTab]=useState('pendientes'),[error,setError]=useState(''),[loading,setLoading]=useState(true),[filters,setFilters]=useState<Record<string,string>>({});
 useEffect(()=>{let active=true;setLoading(true);apiClient.get('/api/v1/tareas'+(employee?'?agente='+encodeURIComponent(employee):'')).then(r=>{if(active){setRows(r.data);setError('');}}).catch(e=>{if(active)setError(e.response?.data?.message||'No se pudieron cargar las tareas.');}).finally(()=>{if(active)setLoading(false);});return()=>{active=false;};},[employee,revision]);
 const columns=[['nombre','Tarea'],['estado','Estado'],['nombre_cuenta','Cuenta'],['descripcion','Descripción']];
 const value=(row:any,key:string)=>key==='estado'?taskStates[row.estado]:row[key]||'';
 const visible=rows.filter(row=>((pendingOnly||tab==='pendientes')?['pendiente','en_curso'].includes(row.estado):['completada','cancelada'].includes(row.estado))&&columns.every(([key])=>String(value(row,key)).toLocaleLowerCase('es').includes((filters[key]||'').trim().toLocaleLowerCase('es'))));
 return <section className="space-y-4">{pendingOnly?<Link href="/tareas" className="inline-block cursor-pointer text-blue-900 hover:underline">Ver todas mis tareas</Link>:<div role="tablist" aria-label="Estado de las tareas" className="flex gap-2">{['pendientes','terminadas'].map(t=><button key={t} type="button" role="tab" aria-selected={tab===t} onClick={()=>setTab(t)} className={`cursor-pointer rounded px-4 py-2 ${tab===t?'bg-blue-950 text-white hover:bg-blue-900':'bg-white hover:bg-blue-50'}`}>{t==='pendientes'?'Pendientes':'Terminadas'}</button>)}</div>}{error?<p role="alert" className="text-red-700">{error}</p>:<div className="overflow-x-auto rounded border border-gray-100 bg-white"><TableFilters>{columns.map(([key,label])=><div key={key}>{key==='estado'?<label className="block text-xs font-extralight text-gray-600"><span className="mb-1 block">{label}</span><select aria-label="Filtrar Estado" value={filters.estado||''} onChange={event=>setFilters(f=>({...f,estado:event.target.value}))} className="w-full cursor-pointer rounded border bg-white p-2 text-sm hover:border-blue-900"><option value="">Todos los estados</option>{Object.entries(taskStates).filter(([state])=>!pendingOnly||['pendiente','en_curso'].includes(state)).map(([state,label])=><option key={state} value={label}>{label}</option>)}</select></label>:<TableColumnFilter label={label} value={filters[key]||''} onChange={v=>setFilters(f=>({...f,[key]:v}))}/> }</div>)}</TableFilters><SortableTable className="w-full text-left text-sm"><thead><tr>{columns.map(([key,label])=><th key={key} className="p-3">{label}</th>)}</tr></thead><tbody>{!loading&&visible.map(row=><tr key={row.id} className="border-t border-gray-100"><td className="p-3"><Link href={'/tareas/'+encodeURIComponent(row.id)+(employee?'?gestion=1':'')} className="cursor-pointer text-blue-900 hover:underline">{row.nombre}</Link></td><td className="p-3">{taskStates[row.estado]}</td><td className="p-3">{row.id_cuenta?<Link className="cursor-pointer text-blue-900 hover:underline" href={'/dashboard/comercial/cuentas/'+encodeURIComponent(row.id_cuenta)}>{row.nombre_cuenta}</Link>:'—'}</td><td className="max-w-xl whitespace-pre-line p-3">{row.descripcion}</td></tr>)}{(loading||!visible.length)&&<tr><td colSpan={columns.length} className="p-5">{loading?'Cargando tareas…':'No hay tareas con estos filtros.'}</td></tr>}</tbody></SortableTable></div>}</section>;
}
