'use client';
import {useEffect,useState} from 'react';
import {useParams,useRouter,useSearchParams} from 'next/navigation';
import Link from 'next/link';
import apiClient from '@/app/apiClient';
import {taskStates} from './TaskList';
export default function TaskDetail(){
 const {id}=useParams(),router=useRouter(),search=useSearchParams();
 const [task,setTask]=useState<any>(null),[manage,setManage]=useState(false),[error,setError]=useState(''),[saving,setSaving]=useState(false),[saved,setSaved]=useState(false);
 useEffect(()=>{apiClient.get('/api/v1/tareas/'+encodeURIComponent(String(id))).then(r=>setTask(r.data)).catch(e=>{if([401,403].includes(e.response?.status))router.replace('/');else setError(e.response?.data?.message||'No se pudo cargar la tarea.');});if(search.get('gestion')==='1')apiClient.get('/api/v1/tareas/agentes').then(()=>setManage(true)).catch(()=>setManage(false));},[id,router,search]);
 const save=async(event:React.FormEvent)=>{event.preventDefault();setSaving(true);setError('');setSaved(false);try{setTask({...task,...(await apiClient.put('/api/v1/tareas/'+encodeURIComponent(task.id),task)).data});setSaved(true);}catch(e:any){setError(e.response?.data?.message||'No se pudo guardar la tarea.');}finally{setSaving(false);}};
 return <main className="space-y-5 bg-gray-100 p-8"><Link href={manage&&task?'/dashboard/operaciones/tareas/'+encodeURIComponent(task.agente):'/tareas'} className="cursor-pointer text-blue-900 hover:underline">Volver a las tareas</Link><h1 className="text-2xl font-semibold">{manage?'Editar tarea':'Detalle de la tarea'}</h1>{error&&<p role="alert" className="text-red-700">{error}</p>}{task?<form onSubmit={save} className="space-y-4 rounded bg-white p-6"><p>Agente: <strong>{task.nombre_agente}</strong></p><label className="block">Nombre<input required maxLength={250} disabled={!manage||saving} value={task.nombre} onChange={e=>{setSaved(false);setTask({...task,nombre:e.target.value});}} className="mt-1 block w-full rounded border border-gray-200 p-2 disabled:cursor-not-allowed disabled:bg-gray-100"/></label><label className="block">Estado<select disabled={!manage||saving} value={task.estado} onChange={e=>{setSaved(false);setTask({...task,estado:e.target.value});}} className="mt-1 block w-full rounded border border-gray-200 p-2 enabled:cursor-pointer enabled:hover:border-blue-900 disabled:cursor-not-allowed disabled:bg-gray-100">{Object.entries(taskStates).map(([v,label])=><option key={v} value={v}>{label}</option>)}</select></label><label className="block">Descripción<textarea disabled={!manage||saving} value={task.descripcion} onChange={e=>{setSaved(false);setTask({...task,descripcion:e.target.value});}} className="mt-1 block min-h-40 w-full rounded border border-gray-200 p-2 disabled:cursor-not-allowed disabled:bg-gray-100"/></label>{manage&&<button disabled={saving} className="rounded bg-blue-950 px-4 py-2 text-white enabled:cursor-pointer enabled:hover:bg-blue-900 disabled:cursor-not-allowed disabled:opacity-50">{saving?'Guardando…':'Guardar cambios'}</button>}{saved&&<p role="status">Cambios guardados.</p>}</form>:!error&&<p>Cargando tarea…</p>}</main>;
}
