"use client";
import { useEffect, useState } from "react";
import MiddleNav from "@/app/general_components/componentes_recurrentes/MiddleNav";
export default function PrevisionLiquidezPage(){
 const now=new Date();const [date,setDate]=useState({d:String(now.getDate()),m:String(now.getMonth()+1),y:String(now.getFullYear())});const [values,setValues]=useState({Sabadell:0,Santander:0});const [error,setError]=useState("");
 const fecha=`${date.d.padStart(2,"0")}/${date.m.padStart(2,"0")}/${date.y}`;
 useEffect(()=>{if(!date.d||!date.m||date.y.length!==4)return;fetch(`/api/v1/direccion/prevision-liquidez?fecha=${encodeURIComponent(fecha)}`).then(r=>{if(!r.ok)throw new Error();return r.json()}).then(setValues).catch(()=>setError("No se pudo calcular la previsión."));},[fecha]);
 const money=(v:number)=>Number(v||0).toLocaleString("es-ES",{style:"currency",currency:"EUR"});
 return <div className="min-h-screen bg-gray-100 text-gray-700"><MiddleNav tituloprincipal="Previsión liquidez"/><main className="p-6 lg:p-12"><section className="rounded-xl bg-white p-6 shadow"><h1 className="text-xl font-semibold text-blue-950">Previsión liquidez en fecha</h1><div className="mt-6 grid gap-4 md:grid-cols-4"><div><p className="mb-2 text-sm font-medium">Fecha</p><div className="flex gap-1">{[["d","dd",2],["m","mm",2],["y","yyyy",4]].map(([k,p,n])=><input key={k} aria-label={p} maxLength={Number(n)} value={(date as any)[k]} onChange={e=>setDate({...date,[k]:e.target.value.replace(/\D/g,"")})} className="min-w-0 flex-1 rounded border p-2" placeholder={p}/>)}</div></div>{[["Banco Sabadell",values.Sabadell],["Banco Santander",values.Santander],["Total",values.Sabadell+values.Santander]].map(([label,value])=><div key={String(label)} className="rounded border border-blue-100 bg-blue-50 p-4"><p className="text-sm text-gray-500">{label}</p><p className="mt-2 text-xl font-semibold text-blue-950">{money(Number(value))}</p></div>)}</div>{error&&<p className="mt-4 text-red-700">{error}</p>}</section></main></div>;
}
