'use client';
import {useEffect,useState} from 'react';
import RecurringChargeForm,{reviewButton} from './RecurringChargeForm';
export default function RecurringChargeManageModal({id,action,onClose,onSaved}:{id:string;action:'edit'|'delete';onClose:()=>void;onSaved:()=>void}) {
  const [original,setOriginal]=useState<any>(null),[value,setValue]=useState<any>(null),[vat,setVat]=useState(true),[error,setError]=useState(''),[busy,setBusy]=useState(false);
  useEffect(()=>{const controller=new AbortController();fetch(`/api/v1/direccion/cargos-recurrentes/${id}`,{cache:'no-store',signal:controller.signal}).then(async r=>{const d=await r.json();if(!r.ok)throw Error(d.message);setOriginal(d);setValue(d);setVat(d.programacion.some((p:any)=>Number(p.base_imponible)<Number(p.total_iva)));}).catch(e=>{if(e.name!=='AbortError')setError(e.message);});return()=>controller.abort();},[id]);
  useEffect(()=>{const close=(e:KeyboardEvent)=>{if(e.key==='Escape')onClose();};window.addEventListener('keydown',close);return()=>window.removeEventListener('keydown',close);},[onClose]);
  const save=async()=>{setBusy(true);setError('');try{const body=action==='delete'?{confirm:true,version:original.updated_at}:{...value,expectedSchedule:original.programacion,expectedType:original.tipo_programacion,programacion:value.programacion.map((p:any)=>({...p,base_imponible:value.tipo_cargo==='nomina'?0:Math.round(Number(p.total_iva)/(vat?1.21:1)*100)/100}))};const r=await fetch(`/api/v1/direccion/cargos-recurrentes/${id}`,{method:action==='delete'?'DELETE':'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const d=await r.json();if(!r.ok)throw Error(d.message);onSaved();}catch(e:any){setError(e.message);}finally{setBusy(false);}};
  return <div className="fixed inset-0 z-50 overflow-y-auto bg-black/60 p-4"><section role="dialog" aria-modal="true" aria-label={action==='delete'?'Eliminar cargo recurrente':'Editar cargo recurrente'} className="mx-auto my-6 max-w-4xl space-y-4 rounded bg-white p-6 text-slate-900"><header className="flex justify-between"><h2 className="text-xl font-semibold">{action==='delete'?'Eliminar':'Editar'} cargo recurrente {id}</h2><button aria-label="Cerrar" className="cursor-pointer rounded px-3 text-2xl hover:bg-blue-50" onClick={onClose}>×</button></header>{value ? action==='delete'?<><p>¿Confirmas la eliminación de este cargo recurrente?</p><p className="rounded bg-amber-50 p-3">Se desasignarán todos los registros de extractos bancarios asociados ({original.movimientos.length}). Los movimientos bancarios y las nóminas registradas se conservarán.</p></>:<><RecurringChargeForm value={value} onChange={setValue} payroll={value.tipo_cargo==='nomina'} vat={vat} onVatChange={setVat}/><p>Confirma los nuevos datos para actualizar el cargo recurrente. Los importes bancarios históricos no cambian.</p></>:<p>Cargando…</p>}{error&&<p role="alert" className="text-red-700">{error}</p>}<footer className="flex justify-end gap-3"><button className={reviewButton} onClick={onClose}>Cancelar</button><button disabled={!value||busy} className={`${reviewButton} ${action==='delete'?'bg-red-700 text-white enabled:hover:bg-red-800':''}`} onClick={save}>{busy?'Guardando…':action==='delete'?'Confirmar eliminación':'Confirmar cambios'}</button></footer></section></div>;
}
