'use client';
import { useEffect, useMemo, useState } from 'react';
import MiddleNav from '@/app/general_components/componentes_recurrentes/MiddleNav';
import { useRouter } from 'next/navigation';
import { ProveedorService } from '@/app/service/ProveedorService';

const money = (value?: number) => Number(value || 0) ? `${Number(value).toLocaleString('es-ES')} EUR` : '-';
export default function ProveedoresPage() {
  const router = useRouter();
  const [rows, setRows] = useState<any[]>([]), [loading, setLoading] = useState(true), [error, setError] = useState('');
  useEffect(() => { ProveedorService.getProveedores().then(data => setRows(Array.isArray(data) ? data : [])).catch(() => setError('No se han podido cargar los proveedores.')).finally(() => setLoading(false)); }, []);
  const [columns, setColumns] = useState({ nombre_proveedor: '', nombre_fiscal_proveedor: '', vat_code: '' });
  const shown = useMemo(() => { return rows.filter(row => Object.entries(columns).every(([key, value]) => String(row[key] || '').toLowerCase().includes(value.trim().toLowerCase()))); }, [rows, columns]);
  return <div className="min-h-screen bg-gray-100 text-gray-700"><MiddleNav tituloprincipal="Proveedores" /><main className="px-12 py-10"><div className="mb-4 flex justify-end"><button onClick={() => router.push('/dashboard/administracion/proveedores/crear')} className="cursor-pointer rounded bg-blue-950 px-4 py-2 text-white hover:bg-blue-900">Crear proveedor</button></div><details className="mb-5 rounded border border-gray-200 bg-white"><summary className="cursor-pointer rounded px-4 py-3 font-medium text-blue-950 hover:bg-blue-50">Filtros{Object.values(columns).some(Boolean) ? ` (${Object.values(columns).filter(Boolean).length} activos)` : ''}</summary><div className="grid gap-3 p-4 sm:grid-cols-3">{Object.entries({ nombre_proveedor: 'Proveedor', nombre_fiscal_proveedor: 'Nombre fiscal', vat_code: 'Código fiscal' }).map(([key, label]) => <label key={key} className="text-sm">{label}<input type="search" value={columns[key as keyof typeof columns]} onChange={event => setColumns(current => ({ ...current, [key]: event.target.value }))} className="mt-1 w-full rounded border bg-white px-3 py-2" /></label>)}</div></details>{error && <p className="mb-4 rounded border border-red-200 bg-red-50 p-3 text-sm text-red-700">{error}</p>}<div className="overflow-x-auto bg-white"><table className="min-w-full"><thead className="bg-blue-950 text-white"><tr>{['ID proveedor','Proveedor','Nombre fiscal','VAT','País','Moneda','Pagos','Total pagos','Último pago'].map(label => <th key={label} className="p-2 text-left font-light first:pl-6">{label}</th>)}</tr></thead><tbody>{loading ? <tr><td colSpan={9} className="p-6 text-center text-gray-500">Cargando proveedores...</td></tr> : shown.length === 0 ? <tr><td colSpan={9} className="p-6 text-center text-gray-500">No hay proveedores.</td></tr> : shown.map(row => <tr key={row.id_proveedor} onClick={() => router.push(`/dashboard/administracion/proveedores/${encodeURIComponent(row.id_proveedor)}`)} className="cursor-pointer transition hover:bg-blue-50"><td className="border-b p-2 pl-6 font-medium text-blue-950">{row.id_proveedor || '-'}</td><td className="border-b p-2">{row.nombre_proveedor || '-'}</td><td className="border-b p-2">{row.nombre_fiscal_proveedor || '-'}</td><td className="border-b p-2">{row.vat_code || '-'}</td><td className="border-b p-2">{row.pais_proveedor || '-'}</td><td className="border-b p-2">{row.moneda_proveedor || '-'}</td><td className="border-b p-2">{row.numero_pagos}</td><td className="border-b p-2">{money(row.total_pagos)}</td><td className="border-b p-2">{row.ultimo_pago || '-'}</td></tr>)}</tbody></table></div></main></div>;
}
