'use client';
import {useState} from 'react';
import Link from 'next/link';
const columns=[['id_linea_banco','Registro'],['banco','Banco'],['fecha_valor','Fecha'],['concepto','Concepto'],['importe','Importe'],['cargo','Cargo recurrente'],['pago','Pago previsto'],['revisado','Revisado']] as const;
export default function SupplierBankCharges({rows}:{rows:any[]}) {
  const [filters,setFilters]=useState<Record<string,string>>({});
  const data=rows.map(r=>({...r,importe:Number(r.importe).toLocaleString('es-ES',{style:'currency',currency:'EUR'}),cargo:r.id_cargo_recurrente?(r.programacion_cargo||[]).map((p:any)=>p.descripcion).filter(Boolean).join(' · ')||String(r.id_cargo_recurrente):'Sin cargo recurrente',pago:r.id_pago||'Sin pago previsto',revisado:r.estado_revision?'Sí':'No'}));
  const shown=data.filter(r=>columns.every(([k])=>String(r[k]||'').toLocaleLowerCase().includes((filters[k]||'').toLocaleLowerCase())));
  return <section className="overflow-x-auto rounded bg-white p-4"><h2 className="mb-3 text-lg font-semibold">Cargos bancarios del proveedor</h2><table className="w-full text-left text-sm"><thead><tr>{columns.map(([k,label])=><th key={k} className="p-2">{label}<input aria-label={`Filtrar ${label}`} className="mt-2 block w-full min-w-28 rounded border p-2 font-normal" value={filters[k]||''} onChange={e=>setFilters({...filters,[k]:e.target.value})}/></th>)}</tr></thead><tbody>{shown.map(r=><tr key={r.id_linea_banco} className="border-t">{columns.map(([k])=><td key={k} className="p-2">{k==='id_linea_banco'?<Link className="cursor-pointer text-blue-900 hover:underline" href={`/dashboard/direccion/tesoreria/extractos/${r.id_linea_banco}`}>{r[k]}</Link>:k==='cargo'&&r.id_cargo_recurrente?<Link className="cursor-pointer text-blue-900 hover:underline" href={`/dashboard/direccion/tesoreria/prevision-liquidez/${r.id_cargo_recurrente}`}>{r[k]}</Link>:r[k]}</td>)}</tr>)}</tbody></table>{!shown.length&&<p className="p-4">No hay cargos para estos filtros.</p>}</section>;
}
