'use client';
import { useEffect, useState } from 'react';
import RecurringChargeModal from '../../direccion/bancos/RecurringChargeModal';
import { reviewButton as button } from '../../direccion/bancos/RecurringChargeForm';
export default function SupplierActions({ supplier, tab }: { supplier:any; tab:string }) {
  const [modal,setModal]=useState(''),[rows,setRows]=useState<any[]>([]),[charges,setCharges]=useState<any[]>([]),[version,setVersion]=useState(0),[error,setError]=useState(''),[saving,setSaving]=useState(false);
  const [form,setForm]=useState({servicio:'',descripcion:'',unidad:'',precio_por_unidad:''});
  useEffect(()=>{if(!supplier)return;const controller=new AbortController();Promise.all([`/api/v1/admin/proveedores/${encodeURIComponent(supplier.id_proveedor)}/benchmark`,'/api/v1/direccion/cargos-recurrentes'].map(url=>fetch(url,{signal:controller.signal,cache:'no-store'}).then(async r=>{const d=await r.json();if(!r.ok)throw new Error(d.message);return d;}))).then(([p,c])=>{setRows(p);setCharges(c.filter((r:any)=>r.id_proveedor===supplier.id_proveedor));setError('');}).catch(e=>{if(e.name!=='AbortError')setError(e.message);});return()=>controller.abort();},[supplier,version]);
  useEffect(()=>{const close=(e:KeyboardEvent)=>{if(e.key==='Escape')setModal('');};window.addEventListener('keydown',close);return()=>window.removeEventListener('keydown',close);},[]);
  if(!supplier)return null;
  const save=async()=>{setSaving(true);setError('');try{const r=await fetch(`/api/v1/admin/proveedores/${encodeURIComponent(supplier.id_proveedor)}/benchmark`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(form)});const d=await r.json();if(!r.ok)throw new Error(d.message);setRows(current=>[d,...current]);setModal('');setForm({servicio:'',descripcion:'',unidad:'',precio_por_unidad:''});}catch(e:any){setError(e.message);}finally{setSaving(false);}};
  return <div className="mb-5 space-y-3">
    <div className="flex flex-wrap gap-3"><button type="button" className={button} onClick={()=>setModal('charge')}>Agregar cargo previsto</button>{tab==='tickets'&&<a className="cursor-pointer rounded border bg-white px-4 py-2 hover:bg-blue-100" href={`/dashboard/administracion/proveedores/tickets/anadir?id_proveedor=${encodeURIComponent(supplier.id_proveedor)}`}>Agregar ticket</a>}{tab==='facturas'&&<a className="cursor-pointer rounded border bg-white px-4 py-2 hover:bg-blue-100" href={`/dashboard/administracion/facturas-proveedores/agregar?id_proveedor=${encodeURIComponent(supplier.id_proveedor)}`}>Agregar factura</a>}{tab==='precios'&&<button type="button" className={button} onClick={()=>setModal('price')}>Agregar producto / servicio</button>}</div>
    {tab==='cargos-pendientes'&&<section className="rounded bg-white p-4"><h3 className="font-semibold">Cargos previstos recurrentes</h3>{charges.length?charges.map(c=><p key={c.id_cargo_recurrente}>{c.programacion.map((p:any)=>`${p.descripcion} · ${Number(p.total_iva).toFixed(2)} € · ${c.tipo_programacion==='fechas'?`${p.dia}/${p.mes}/${p.anio||''}`:`Cada ${p.cada} ${p.unidad}`}`).join(' / ')}</p>):<p>Sin cargos previstos recurrentes.</p>}</section>}
    {tab==='precios'&&<div className="overflow-auto rounded bg-white"><table className="w-full text-left text-sm"><caption className="p-3 text-left font-semibold">Productos y servicios del proveedor</caption><thead><tr>{['Servicio','Descripción','Unidad','Precio por unidad'].map(h=><th key={h} className="p-3">{h}</th>)}</tr></thead><tbody>{rows.map(r=><tr key={r.id} className="border-t"><td className="p-3">{r.servicio}</td><td className="p-3">{r.descripcion}</td><td className="p-3">{r.unidad}</td><td className="p-3">{Number(r.precio_por_unidad).toFixed(2)} {supplier.moneda_proveedor||'EUR'}</td></tr>)}{!rows.length&&<tr><td colSpan={4} className="p-3">No hay productos o servicios registrados.</td></tr>}</tbody></table></div>}
    {error&&<p role="alert" className="text-red-700">{error}</p>}
    {modal==='charge'&&<RecurringChargeModal providers={[supplier]} supplierId={supplier.id_proveedor} close={()=>setModal('')} done={()=>{setModal('');setVersion(v=>v+1);}} />}
    {modal==='price'&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-black/65 p-4"><form role="dialog" aria-modal="true" aria-label="Agregar producto o servicio" className="max-h-[90vh] w-full max-w-xl space-y-4 overflow-auto rounded-xl bg-white p-6" onSubmit={e=>{e.preventDefault();void save();}}><header className="flex justify-between"><h2 className="text-xl font-semibold">Agregar producto / servicio</h2><button type="button" aria-label="Cerrar" onClick={()=>setModal('')} className="cursor-pointer rounded px-3 text-2xl hover:bg-blue-50">×</button></header>{([['servicio','Servicio'],['descripcion','Descripción'],['unidad','Unidad'],['precio_por_unidad','Precio por unidad']] as const).map(([key,label])=><label key={key} className="block">{label}<input required={key!=='descripcion'} type={key==='precio_por_unidad'?'number':'text'} min={key==='precio_por_unidad'?'0':undefined} step={key==='precio_por_unidad'?'0.01':undefined} className="mt-1 w-full rounded border p-2" value={form[key]} onChange={e=>setForm({...form,[key]:e.target.value})} /></label>)}{error&&<p role="alert" className="text-red-700">{error}</p>}<button type="submit" disabled={saving} className={button}>{saving?'Guardando…':'Guardar'}</button></form></div>}
  </div>;
}
