'use client';

import Link from 'next/link';
import { useEffect, useMemo, useState } from 'react';

type Column = { nombre: string; tipo: string; esClave: boolean };
type Table = { nombre: string; columnas: Column[] };
type Selection = Record<string, string[]>;
const primary = 'cursor-pointer rounded bg-blue-950 px-5 py-2.5 text-sm font-semibold text-white transition hover:bg-blue-800 hover:shadow disabled:cursor-not-allowed disabled:bg-slate-400';
const secondary = 'cursor-pointer rounded border border-slate-300 bg-white px-5 py-2.5 text-sm font-semibold text-slate-800 transition hover:border-blue-800 hover:bg-blue-50';

export default function NuevaCopiaSeguridadPage() {
  const [phase, setPhase] = useState(1), [catalog, setCatalog] = useState<Table[]>([]);
  const [selection, setSelection] = useState<Selection>({});
  const [expanded, setExpanded] = useState<string | null>(null);
  const [name, setName] = useState(''), [details, setDetails] = useState(''), [error, setError] = useState('');
  const [loading, setLoading] = useState(true);
  const [tableFilter, setTableFilter] = useState(''), [selectAllChecked, setSelectAllChecked] = useState(false), [progress, setProgress] = useState(0);
  const [processState, setProcessState] = useState<'idle' | 'working' | 'success' | 'error'>('idle');
  useEffect(() => { fetch('/api/v1/direccion/copias-seguridad/catalogo', { cache: 'no-store' }).then(async response => { const body = await response.json(); if (!response.ok) throw new Error(body.message || 'No se pudo cargar el catálogo.'); setCatalog(body); }).catch(reason => setError(reason.message)).finally(() => setLoading(false)); }, []);
  const selectedTables = useMemo(() => catalog.filter(table => selection[table.nombre]), [catalog, selection]);
  const filteredCatalog = useMemo(() => catalog.filter(table => table.nombre.toLowerCase().includes(tableFilter.trim().toLowerCase())), [catalog, tableFilter]);
  const allSelection = () => Object.fromEntries(catalog.map(table => [table.nombre, table.columnas.map(column => column.nombre)]));
  const toggleTable = (table: Table) => { setSelectAllChecked(false); setSelection(current => { if (current[table.nombre]) { const next = { ...current }; delete next[table.nombre]; return next; } return { ...current, [table.nombre]: table.columnas.map(column => column.nombre) }; }); };
  const toggleColumn = (table: Table, column: Column) => { if (column.esClave) return; setSelection(current => { const columns = new Set(current[table.nombre] || []); if (columns.has(column.nombre)) columns.delete(column.nombre); else columns.add(column.nombre); return { ...current, [table.nombre]: [...columns] }; }); };
  const startFull = () => { if (!name.trim()) return setError('Escribe primero un nombre para la copia completa.'); setSelection(allSelection()); setDetails('COPIA COMPLETA'); setError(''); setPhase(4); };
  const next = () => { setError(''); if (phase === 1) { if (!name.trim()) return setError('El nombre de la copia es obligatorio.'); if (!selectedTables.length) return setError('Selecciona al menos una tabla.'); setExpanded(selectedTables[0].nombre); setPhase(2); } else if (phase === 2) { if (selectedTables.some(table => !selection[table.nombre].length)) return setError('Cada tabla debe conservar al menos una columna.'); setPhase(3); } else if (phase === 3) setPhase(4); };
  const generate = async () => { setPhase(5); setProcessState('working'); setProgress(5); setError(''); const timer = window.setInterval(() => setProgress(current => current >= 90 ? current : current + Math.max(1, Math.round((90 - current) / 8))), 350); try { const response = await fetch('/api/v1/direccion/copias-seguridad/generar', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ nombre: name, detalles: details, selecciones: selectedTables.map(table => ({ tabla: table.nombre, columnas: selection[table.nombre] })) }) }); if (!response.ok) { const body = await response.json(); throw new Error(body.message || 'La copia no se pudo generar.'); } const blob = await response.blob(); const filename = (response.headers.get('content-disposition') || '').match(/filename="([^"]+)"/)?.[1] || 'copia-seguridad.json'; const url = URL.createObjectURL(blob); const anchor = document.createElement('a'); anchor.href = url; anchor.download = filename; document.body.appendChild(anchor); anchor.click(); anchor.remove(); URL.revokeObjectURL(url); setProgress(100); setProcessState('success'); } catch (reason) { setProgress(100); setError(reason instanceof Error ? reason.message : 'La copia no se pudo generar.'); setProcessState('error'); } finally { window.clearInterval(timer); } };

  return <main className="min-h-screen bg-gray-100 px-8 py-8 text-gray-900 lg:px-12">
    <header className="mb-6 flex items-start justify-between gap-4"><div><h1 className="text-2xl font-semibold text-slate-800">Nueva copia de seguridad</h1><p className="mt-1 text-sm text-slate-600">Fase {phase} de 5</p></div><Link href="/dashboard/direccion/copias-seguridad" className={secondary}>← Volver al registro</Link></header>
    <div className="mb-6 grid grid-cols-5 gap-2" aria-label="Progreso">{[1,2,3,4,5].map(step => <div key={step} className={`rounded px-2 py-2 text-center text-xs font-semibold ${step === phase ? 'bg-blue-950 text-white' : step < phase ? 'bg-blue-200 text-blue-950' : 'bg-slate-200 text-slate-700'}`}>Fase {step}</div>)}</div>
    {error && <p className="mb-4 rounded border border-red-300 bg-red-50 p-3 text-sm text-red-800">{error}</p>}
    <section className="rounded-lg border border-slate-200 bg-white p-6 shadow-sm">
      {phase === 1 && <><h2 className="text-lg font-semibold">Nombre y tablas</h2><label className="mt-4 block max-w-xl text-sm font-semibold">Nombre de la copia<input value={name} onChange={event => setName(event.target.value)} maxLength={255} className="mt-1 w-full rounded border border-slate-300 bg-white px-3 py-2 outline-none hover:border-blue-700 focus:border-blue-900" /></label><div className="my-5 flex flex-wrap items-center justify-between gap-3 rounded border border-blue-200 bg-blue-50 p-4"><div><p className="font-semibold text-blue-950">Copia completa</p><p className="text-sm text-blue-900">Incluye todas las tablas y columnas con el detalle “COPIA COMPLETA”.</p></div><button type="button" onClick={startFull} className={primary}>Hacer copia completa</button></div><label className="mb-3 block text-sm font-semibold">Filtrar por nombre de tabla<input type="search" value={tableFilter} onChange={event => setTableFilter(event.target.value)} placeholder="Buscar tabla RDS…" className="mt-1 w-full rounded border border-slate-300 px-3 py-2 outline-none focus:border-blue-900" /></label><div className="overflow-hidden rounded border border-slate-200"><table className="w-full text-sm"><thead className="bg-slate-800 text-left text-white"><tr><th className="w-20 px-4 py-3">Elegir</th><th className="px-4 py-3">Tabla RDS</th><th className="px-4 py-3 text-right">Columnas</th></tr><tr className="bg-slate-100 text-slate-900"><th className="px-4 py-2"><input type="checkbox" checked={selectAllChecked} onChange={event => { setSelectAllChecked(event.target.checked); if (event.target.checked) setSelection(allSelection()); }} className="h-4 w-4 cursor-pointer accent-blue-950" aria-label="Seleccionar todas las tablas" /></th><th colSpan={2} className="px-4 py-2 font-semibold">Seleccionar todas las checkboxes</th></tr></thead><tbody>{loading ? <tr><td colSpan={3} className="p-8 text-center">Cargando tablas…</td></tr> : filteredCatalog.map(table => <tr key={table.nombre} onClick={() => toggleTable(table)} className="cursor-pointer border-t border-slate-200 hover:bg-blue-50"><td className="px-4 py-3"><input aria-label={`Seleccionar ${table.nombre}`} type="checkbox" checked={Boolean(selection[table.nombre])} onChange={() => toggleTable(table)} onClick={event => event.stopPropagation()} className="h-4 w-4 cursor-pointer accent-blue-950" /></td><td className="px-4 py-3 font-mono">{table.nombre}</td><td className="px-4 py-3 text-right">{table.columnas.length}</td></tr>)}</tbody></table></div></>}
      {phase === 2 && <><h2 className="text-lg font-semibold">Columnas que se copiarán</h2><p className="mt-1 text-sm text-slate-600">Las claves primarias son obligatorias.</p><div className="mt-5 space-y-3">{selectedTables.map(table => <article key={table.nombre} className="overflow-hidden rounded border border-slate-300"><button type="button" onClick={() => setExpanded(expanded === table.nombre ? null : table.nombre)} className="flex w-full cursor-pointer justify-between bg-slate-100 px-4 py-3 text-left font-semibold hover:bg-blue-100"><span>{table.nombre}</span><span>{expanded === table.nombre ? '−' : '+'}</span></button>{expanded === table.nombre && <div className="overflow-x-auto p-3"><table className="w-full text-sm"><thead className="bg-slate-800 text-left text-white"><tr><th className="px-3 py-2">Copiar</th><th className="px-3 py-2">Columna</th><th className="px-3 py-2">Tipo</th><th className="px-3 py-2">Clave</th></tr></thead><tbody>{table.columnas.map(column => <tr key={column.nombre} className="border-t"><td className="px-3 py-2"><input type="checkbox" checked={selection[table.nombre]?.includes(column.nombre) || false} disabled={column.esClave} onChange={() => toggleColumn(table, column)} className="h-4 w-4 cursor-pointer accent-blue-950 disabled:cursor-not-allowed" /></td><td className="px-3 py-2 font-mono">{column.nombre}</td><td className="px-3 py-2">{column.tipo}</td><td className="px-3 py-2">{column.esClave ? 'Primaria (obligatoria)' : '—'}</td></tr>)}</tbody></table></div>}</article>)}</div></>}
      {phase === 3 && <><h2 className="text-lg font-semibold">Detalles</h2><label className="mt-4 block text-sm font-semibold">Descripción de la copia<textarea value={details} onChange={event => setDetails(event.target.value)} rows={7} className="mt-1 w-full resize-y rounded border border-slate-300 bg-white px-3 py-2 outline-none hover:border-blue-700 focus:border-blue-900" placeholder="Añade el motivo o información útil…" /></label></>}
      {phase === 4 && <><h2 className="text-lg font-semibold">Resumen</h2><dl className="mt-5 grid gap-4 rounded bg-slate-50 p-5 text-sm sm:grid-cols-2"><div><dt className="font-semibold text-slate-600">Nombre</dt><dd>{name}</dd></div><div><dt className="font-semibold text-slate-600">Tablas</dt><dd>{selectedTables.length}</dd></div><div className="sm:col-span-2"><dt className="font-semibold text-slate-600">Selección</dt><dd className="break-words">{selectedTables.map(table => `${table.nombre} (${selection[table.nombre].length} columnas)`).join(', ')}</dd></div><div className="sm:col-span-2"><dt className="font-semibold text-slate-600">Detalles</dt><dd className="whitespace-pre-wrap">{details || 'Sin detalles'}</dd></div></dl><p className="mt-4 rounded border border-amber-200 bg-amber-50 p-3 text-sm text-amber-900">El archivo se descarga una sola vez. Después solo permanecerá el registro informativo.</p></>}
      {phase === 5 && <div className="py-10 text-center"><div className={`mx-auto mb-4 flex h-14 w-14 items-center justify-center rounded-full text-2xl ${processState === 'working' ? 'bg-blue-100 text-blue-900' : processState === 'success' ? 'bg-green-100 text-green-800' : 'bg-red-100 text-red-800'}`}>{processState === 'working' ? '…' : processState === 'success' ? '✓' : '!'}</div><h2 className="text-xl font-semibold">{processState === 'working' ? 'Generando la copia…' : processState === 'success' ? 'Copia generada y descarga iniciada' : 'No se pudo generar la copia'}</h2><div className="mx-auto mt-5 h-4 max-w-xl overflow-hidden rounded-full bg-slate-200" role="progressbar" aria-valuenow={progress} aria-valuemin={0} aria-valuemax={100}><div className={`h-full transition-all duration-300 ${processState === 'error' ? 'bg-red-600' : 'bg-blue-900'}`} style={{ width: `${progress}%` }} /></div><p className="mt-2 text-sm font-semibold text-slate-700">{progress}%</p><p className="mt-2 text-sm text-slate-600">{processState === 'working' ? 'Se están leyendo las tablas seleccionadas.' : processState === 'success' ? 'El archivo no se conserva en el servidor.' : 'El error ha quedado anotado en el registro.'}</p>{processState !== 'working' && <Link href="/dashboard/direccion/copias-seguridad" className={`${primary} mt-6 inline-block`}>Ver registro de copias</Link>}</div>}
      {phase < 5 && <footer className="mt-7 flex justify-between"><button type="button" onClick={() => phase === 1 ? history.back() : setPhase(current => current - 1)} className={secondary}>{phase === 1 ? 'Cancelar' : 'Anterior'}</button>{phase < 4 ? <button type="button" onClick={next} className={primary}>Continuar</button> : <button type="button" onClick={generate} className={primary}>Confirmar y generar copia</button>}</footer>}
    </section>
  </main>;
}
