BEGIN;
ALTER TABLE tesoreria_tarjetas DROP CONSTRAINT IF EXISTS tarjetas_ultimos_digitos_check;
ALTER TABLE tesoreria_tarjetas DROP CONSTRAINT IF EXISTS tesoreria_tarjetas_ultimos_digitos_check;
ALTER TABLE tesoreria_tarjetas DROP CONSTRAINT IF EXISTS tarjeta_digitos_configuracion;
ALTER TABLE tesoreria_tarjetas ADD CONSTRAINT tarjeta_digitos_configuracion CHECK (ultimos_digitos='' OR ultimos_digitos ~ '^[0-9]{4}$');
ALTER TABLE administracion_tickets ADD COLUMN IF NOT EXISTS estado_revision text NOT NULL DEFAULT 'pendiente', ADD COLUMN IF NOT EXISTS clasificacion text NOT NULL DEFAULT 'asociable', ADD COLUMN IF NOT EXISTS comentarios text NOT NULL DEFAULT '', ADD COLUMN IF NOT EXISTS updated_at timestamptz NOT NULL DEFAULT now();
ALTER TABLE administracion_tickets ADD COLUMN IF NOT EXISTS id_liquidacion_tarjeta text REFERENCES tesoreria_tarjetas_liquidaciones(id);
ALTER TABLE administracion_tickets DROP CONSTRAINT IF EXISTS tickets_db_proveedor_check;
ALTER TABLE administracion_tickets DROP CONSTRAINT IF EXISTS ticket_proveedor_ambito;
ALTER TABLE administracion_tickets ADD CONSTRAINT ticket_proveedor_ambito CHECK(ambito='GM' OR id_proveedor IS NOT NULL OR length(btrim(nombre_personalizado_proveedor))>0);
ALTER TABLE tesoreria_tarjetas_liquidaciones DROP CONSTRAINT IF EXISTS tesoreria_tarjetas_liquidaciones_estado_check;
ALTER TABLE tesoreria_tarjetas_liquidaciones DROP CONSTRAINT IF EXISTS liquidacion_estado;
ALTER TABLE tesoreria_tarjetas_liquidaciones ADD CONSTRAINT liquidacion_estado CHECK(estado IN ('pendiente','revisada','anulada'));
ALTER TABLE tesoreria_tarjetas_liquidaciones ALTER COLUMN real DROP NOT NULL;
ALTER TABLE tesoreria_tarjetas_liquidaciones ADD COLUMN IF NOT EXISTS version integer NOT NULL DEFAULT 1, ADD COLUMN IF NOT EXISTS updated_at timestamptz NOT NULL DEFAULT now();
CREATE UNIQUE INDEX IF NOT EXISTS liquidacion_periodo_activo ON tesoreria_tarjetas_liquidaciones(id_tarjeta,fecha) WHERE estado<>'anulada';
CREATE UNIQUE INDEX IF NOT EXISTS liquidacion_mes_activo ON tesoreria_tarjetas_liquidaciones(id_tarjeta,EXTRACT(YEAR FROM fecha),EXTRACT(MONTH FROM fecha)) WHERE estado<>'anulada';
CREATE TABLE IF NOT EXISTS tesoreria_tarjetas_documentos(id_liquidacion text PRIMARY KEY REFERENCES tesoreria_tarjetas_liquidaciones(id),nombre text NOT NULL,sha256 text NOT NULL UNIQUE,contenido bytea NOT NULL,extraccion jsonb NOT NULL,created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS tesoreria_tarjetas_lineas(id text PRIMARY KEY,id_liquidacion text NOT NULL REFERENCES tesoreria_tarjetas_liquidaciones(id),posicion integer NOT NULL,fecha date NOT NULL,fecha_valor date NOT NULL,concepto text NOT NULL,importe numeric(14,2) NOT NULL,estado text NOT NULL DEFAULT 'pendiente' CHECK(estado IN ('pendiente','conciliado','pendiente_ticket','sin_ticket')),motivo text NOT NULL DEFAULT '',id_ticket bigint REFERENCES administracion_tickets(id_ticket),id_vencimiento text REFERENCES tesoreria_cargos_vencimientos(id),id_otro text,UNIQUE(id_liquidacion,posicion));
CREATE UNIQUE INDEX IF NOT EXISTS tarjeta_linea_ticket_unico ON tesoreria_tarjetas_lineas(id_ticket) WHERE id_ticket IS NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS tarjeta_linea_vencimiento_unico ON tesoreria_tarjetas_lineas(id_vencimiento) WHERE id_vencimiento IS NOT NULL;
INSERT INTO tesoreria_tarjetas(id_tarjeta,codigo,nombre,banco,ultimos_digitos,tipo,estado,descripcion) SELECT gen_random_uuid()::text,'PASS-GIMENO','PASS Gimeno','Por configurar','','personal','activa','PASS Carrefour. Pendiente de configurar últimos dígitos, banco de cargo y calendario.' WHERE NOT EXISTS(SELECT 1 FROM tesoreria_tarjetas WHERE tipo='personal' AND lower(nombre) LIKE '%pass%gimeno%');
INSERT INTO tesoreria_tarjetas(id_tarjeta,codigo,nombre,banco,ultimos_digitos,tipo,estado,descripcion) SELECT gen_random_uuid()::text,'SAN-PERSONAL-GIMENO','Santander Personal Gimeno','Santander','','personal','activa','Pendiente de configurar últimos dígitos y calendario.' WHERE NOT EXISTS(SELECT 1 FROM tesoreria_tarjetas WHERE tipo='personal' AND banco='Santander' AND lower(nombre) LIKE '%gimeno%');
COMMIT;
