ALTER TABLE cuentas_db
  ADD COLUMN IF NOT EXISTS website TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS identificador_fiscal_tipo TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS cif TEXT NOT NULL DEFAULT '';
