'use client';
import { useEffect, useMemo, useState } from 'react';
type Row = { id:string; prioridad:string; donde_esta:string; empresa:string; titulo:string; estado:string; responsable_correccion:string; revista:string; espana_previsto_numero:string; latam_previsto_numero:string; especial_numero:string; hueco_previsto:string; paginas:string; estado_publicacion_vidrioperfil:string };
const columns: [keyof Row,string][] = [['prioridad','Prioridad'],['donde_esta','Dónde está'],['empresa','Empresa'],['titulo','Título'],['estado','Estado'],['responsable_correccion','Responsable corrección'],['revista','Revista'],['espana_previsto_numero','España previsto Nº'],['latam_previsto_numero','Latam previsto Nº'],['especial_numero','Especial Nº'],['hueco_previsto','Hueco previsto'],['paginas','Páginas'],['estado_publicacion_vidrioperfil','Estado publicación en vidrioperfil']];
const tableColumns = columns.filter(([field]) => !['prioridad', 'donde_esta'].includes(field));
const selectFields = new Set<keyof Row>(['prioridad','estado','responsable_correccion','revista']);
export default function ControlRedaccionTable(){
  const [rows,setRows]=useState<Row[]>([]); const [filters,setFilters]=useState<Partial<Record<keyof Row,string>>>({}); const [loading,setLoading]=useState(true); const [error,setError]=useState('');
  useEffect(()=>{fetch('/api/v1/produccion/control-redaccion').then(async r=>{const d=await r.json();if(!r.ok)throw new Error(d.message);setRows(d)}).catch(e=>setError(e.message)).finally(()=>setLoading(false))},[]);
  const filtered=useMemo(()=>rows.filter(row=>columns.every(([field])=>!filters[field]?.trim()||String(row[field]||'').toLowerCase().includes(filters[field]!.trim().toLowerCase()))),[rows,filters]);
  return <section className="rounded-lg bg-white p-8 shadow-xl"><div className="mb-5 flex items-end justify-between"><div><h1 className="text-[19px] font-semibold text-blue-950">Control redacción</h1><p className="mt-1 text-[13px] text-gray-500">{filtered.length} de {rows.length} registros</p></div><button type="button" onClick={()=>setFilters({})} className="cursor-pointer rounded border border-blue-950 px-4 py-2 text-[13px] text-blue-950 hover:bg-blue-50">Limpiar filtros</button></div>
    <details className="group mb-6 rounded border border-gray-200 p-4"><summary className="cursor-pointer rounded text-[13px] font-semibold uppercase text-gray-500 hover:bg-gray-50 hover:text-blue-950 group-open:mb-3">Filtros</summary><div className="grid grid-cols-1 gap-3 md:grid-cols-3 xl:grid-cols-5">{columns.map(([field,label])=><label key={field} className="text-[13px]"><span className="mb-1 block text-[11px] font-semibold uppercase text-gray-500">{label}</span>{selectFields.has(field)?<select value={filters[field]||''} onChange={e=>setFilters({...filters,[field]:e.target.value})} className="cursor-pointer hover:border-blue-950 w-full rounded border border-gray-300 bg-white px-3 py-2 outline-none focus:border-blue-950"><option value="">Todos</option>{[...new Set(rows.map(row=>row[field]).filter(Boolean))].sort().map(value=><option key={value} value={value}>{value}</option>)}</select>:<input value={filters[field]||''} onChange={e=>setFilters({...filters,[field]:e.target.value})} className="w-full rounded border border-gray-300 px-3 py-2 outline-none focus:border-blue-950"/>}</label>)}</div></details>
    <div className="overflow-x-auto"><table className="w-full text-[11px]"><thead className="bg-blue-950 text-white"><tr>{tableColumns.map(([field,label])=><th key={field} className="whitespace-nowrap p-2 text-left font-light">{label}</th>)}</tr></thead><tbody>{filtered.map(row=><tr key={row.id} className="border-t hover:bg-gray-50">{tableColumns.map(([field])=><td key={field} className="max-w-80 border-b p-2 align-top">{row[field]||'-'}</td>)}</tr>)}</tbody></table>{loading&&<p className="p-6 text-center">Cargando control de redacción…</p>}{error&&<p className="p-6 text-center text-red-600">{error}</p>}{!loading&&!error&&!filtered.length&&<p className="p-6 text-center">No hay registros que coincidan con los filtros.</p>}</div>
  </section>;
}
