'use client';
import {useEffect,useState} from 'react';
import apiClient from '@/app/apiClient';
import {articleStates,articleOwners,articleMagazines,articlePlacements,validateArticle} from '@/app/config/editorialArticle';
const input='mt-1 block w-full rounded border border-gray-300 bg-white p-2 disabled:bg-gray-100';
export default function NewArticleModal({onClose,onCreated}:{onClose:()=>void;onCreated:(row:any)=>void}) {
  const [data,setData]=useState({empresa:'',titulo:'',estado:'Pendiente',responsable_correccion:'',revista:'',espana_previsto_numero:'',latam_previsto_numero:'',especial_numero:'',hueco_previsto:'',paginas:'',estado_publicacion_vidrioperfil:false});
  const [busy,setBusy]=useState(false),[error,setError]=useState('');
  useEffect(()=>{const close=(event:KeyboardEvent)=>{if(event.key==='Escape')onClose();};window.addEventListener('keydown',close);return()=>window.removeEventListener('keydown',close);},[onClose]);
  const save=async(event:React.FormEvent)=>{event.preventDefault();if(busy)return;setError('');try{validateArticle(data);setBusy(true);const response=await apiClient.post('/api/v1/produccion/control-redaccion',data);onCreated(response.data);}catch(e:any){setError(e.message || 'No se pudo crear el artículo.');}finally{setBusy(false);}};
  return <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/40 p-4"><section role="dialog" aria-modal="true" aria-labelledby="new-article-title" className="relative max-h-[90vh] w-full max-w-3xl overflow-y-auto rounded-lg bg-white p-6 shadow-xl"><button type="button" aria-label="Cerrar nuevo artículo" onClick={onClose} className="absolute right-3 top-2 cursor-pointer rounded px-2 text-2xl hover:bg-gray-100">×</button><h2 id="new-article-title" className="mb-5 pr-8 text-xl font-semibold text-blue-950">Nuevo contenido para artículo</h2><form onSubmit={save} className="space-y-4"><fieldset disabled={busy} className="grid gap-4 md:grid-cols-2">{(['empresa','titulo'] as const).map(key=><label key={key}>{key==='empresa'?'Empresa':'Título'} *<input required maxLength={2000} autoFocus={key==='empresa'} value={data[key]} onChange={e=>setData({...data,[key]:e.target.value})} className={input}/></label>)}{([['estado','Estado',articleStates],['responsable_correccion','Responsable corrección',articleOwners],['revista','Revista',articleMagazines]] as const).map(([key,label,options])=><label key={key}>{label}{key!=='revista'?' *':''}<select required={key!=='revista'} value={data[key]} onChange={e=>setData({...data,[key]:e.target.value})} className={`${input} enabled:cursor-pointer enabled:hover:border-blue-950 disabled:cursor-default`}>{key==='responsable_correccion'&&<option value="">Selecciona un responsable</option>}{options.map(value=><option key={value} value={value}>{value || 'En blanco'}</option>)}</select></label>)}<label>Páginas *<input required type="number" min="1" step="1" value={data.paginas} onChange={e=>setData({...data,paginas:e.target.value})} className={input}/></label><p className="text-sm text-gray-600 md:col-span-2">Rellena al menos uno de estos cuatro campos; los demás pueden quedar vacíos.</p>{Object.entries(articlePlacements).map(([key,label])=><label key={key}>{label}<input maxLength={2000} value={data[key as keyof typeof articlePlacements]} onChange={e=>setData({...data,[key]:e.target.value})} className={input}/></label>)}<label className="flex items-center gap-3 rounded p-2 hover:bg-blue-50 md:col-span-2"><input type="checkbox" checked={data.estado_publicacion_vidrioperfil} onChange={e=>setData({...data,estado_publicacion_vidrioperfil:e.target.checked})} className="h-4 w-4 enabled:cursor-pointer disabled:cursor-default"/>Estado publicación en Vidrioperfil (publicado)</label></fieldset>{error&&<p role="alert" className="rounded bg-red-50 p-3 text-red-700">{error}</p>}<div className="flex justify-end gap-3"><button type="button" onClick={onClose} className="cursor-pointer rounded border px-4 py-2 hover:bg-gray-100">Cancelar</button><button disabled={busy} className="rounded bg-blue-950 px-4 py-2 text-white enabled:cursor-pointer enabled:hover:bg-blue-900 disabled:cursor-default disabled:opacity-50">{busy?'Guardando…':'Crear artículo'}</button></div></form></section></div>;
}
