'use client';
import SortableTable from '@/app/components/SortableTable';

import TableFilters from '@/app/components/TableFilters';
import {useEffect,useState} from 'react';
import Link from 'next/link';
import apiClient from '@/app/apiClient';
import TaskCalendar from './TaskCalendar';
import TableColumnFilter from '@/app/components/TableColumnFilter';
export default function TasksEmployees(){
 const [tab,setTab]=useState('agentes'),[tasks,setTasks]=useState<any[]>([]);
 const [rows,setRows]=useState<any[]>([]),[error,setError]=useState(''),[loading,setLoading]=useState(true),[filters,setFilters]=useState<Record<string,string>>({});
 useEffect(()=>{Promise.all([apiClient.get('/api/v1/tareas/agentes'),apiClient.get('/api/v1/tareas/calendario')]).then(([agents,calendar])=>{setRows(agents.data);setTasks(calendar.data);}).catch(e=>setError(e.response?.data?.message||'No se pudieron cargar los agentes.')).finally(()=>setLoading(false));},[]);
 const columns=[['nombre','Agente'],['pendientes','Pendientes'],['terminadas','Terminadas']];
 const visible=rows.filter(row=>columns.every(([key])=>String(row[key]).toLocaleLowerCase('es').includes((filters[key]||'').toLocaleLowerCase('es'))));
 return <main className="min-h-screen space-y-5 bg-gray-100 p-4 text-slate-900 md:p-8"><header className="flex flex-wrap items-center justify-between gap-4"><h1 className="text-2xl font-semibold text-blue-950">Tareas</h1><Link href="/dashboard/operaciones/tareas/importar" className="cursor-pointer rounded bg-blue-950 px-4 py-2 text-white hover:bg-blue-900">Importar tareas de vtiger</Link></header><div role="tablist" aria-label="Vistas de tareas" className="flex gap-2">{[['agentes','Tareas por agente'],['calendario','Calendario']].map(([key,label])=><button key={key} role="tab" aria-selected={tab===key} onClick={()=>setTab(key)} className={tab===key?'cursor-pointer rounded px-4 py-2 bg-blue-950 text-white hover:bg-blue-900':'cursor-pointer rounded px-4 py-2 bg-white text-blue-950 hover:bg-blue-50'}>{label}</button>)}</div>{error?<p role="alert" className="text-red-700">{error}</p>:loading?<p>Cargando tareas...</p>:tab==='calendario'?<TaskCalendar rows={tasks}/>:<><TableFilters>{columns.map(([key,label])=><div key={key}><TableColumnFilter label={label} value={filters[key]||''} onChange={value=>setFilters(f=>({...f,[key]:value}))}/></div>)}</TableFilters><SortableTable className="w-full rounded border border-gray-100 bg-white text-left"><thead className="bg-blue-950 text-white"><tr>{columns.map(([key,label])=><th key={key} className="p-3">{label}</th>)}</tr></thead><tbody>{visible.map(row=><tr key={row.id_agente} className="border-t border-gray-100 hover:bg-blue-50"><td className="p-3"><Link href={'/dashboard/operaciones/tareas/'+encodeURIComponent(row.id_agente)} className="cursor-pointer text-blue-900 hover:underline">{row.nombre}</Link></td><td className="p-3">{row.pendientes}</td><td className="p-3">{row.terminadas}</td></tr>)}{(loading||!visible.length)&&<tr><td colSpan={3} className="p-5">{loading?'Cargando…':'No hay agentes con estos filtros.'}</td></tr>}</tbody></SortableTable><section className="rounded-lg border border-slate-200 bg-white p-4"><h2 className="mb-3 font-semibold">Tareas sin agente asociado</h2><div className="max-h-96 space-y-2 overflow-auto">{tasks.filter(task=>task.vtiger_original&&!task.agente).map(task=><Link key={task.id} href={'/tareas/'+encodeURIComponent(task.id)+'?gestion=1'} className="block cursor-pointer rounded border border-slate-200 p-3 text-blue-950 hover:bg-blue-50">{task.nombre}<span className="block text-sm text-slate-700">{task.vtiger_original['Asignado a']||'Sin responsable'} · {task.vtiger_original['En relación con']||'Sin cuenta'}</span></Link>)}{!tasks.some(task=>task.vtiger_original&&!task.agente)&&<p className="text-sm text-slate-600">No hay tareas sin agente asociado.</p>}</div></section></>}</main>;
}
