"use client";
import SortableTable from '@/app/components/SortableTable';

import { useState } from 'react';
import Link from 'next/link';
import * as XLSX from 'xlsx';
import MiddleNav from '@/app/general_components/componentes_recurrentes/MiddleNav';
import { bulkImportTypes, bulkPolicies } from '@/app/config/bulkImportFields';
import apiClient from '@/app/apiClient';

type ImportType=keyof typeof bulkImportTypes;
const button='rounded border px-4 py-2 transition enabled:cursor-pointer enabled:hover:bg-blue-100 disabled:cursor-default disabled:opacity-50';
const select='rounded border bg-white p-2 cursor-pointer hover:border-blue-900';
const phases=['Tipo y reglas','Formato exacto','Archivo Excel','Validación','Incidencias','Confirmación'];
const descriptions:Record<string,string>={text:'Texto; IDs exactos existentes para las asociaciones',amount:'Número o decimal con coma. EUR, sin valores negativos',date:'Fecha Excel o dd/mm/yyyy',boolean:'sí / no',integer:'Entero positivo',payment:'transferencia / recibo / tarjeta / efectivo / pagaré',bank:'Sabadell / Santander'};

export default function ImportacionMasivaPage() {
  const [type,setType]=useState<ImportType>('ordenes'),[policy,setPolicy]=useState('update'),[quantity,setQuantity]=useState('many');
  const [phase,setPhase]=useState(0),[file,setFile]=useState<File|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState('');
  const [preview,setPreview]=useState<any>(null),[choices,setChoices]=useState<Record<string,string>>({}),[result,setResult]=useState<any>(null);
  const schema=bulkImportTypes[type];
  const template=()=>{const book=XLSX.utils.book_new();XLSX.utils.book_append_sheet(book,XLSX.utils.aoa_to_sheet([schema.fields.map(field=>field.key)]),'Importación');XLSX.writeFile(book,`plantilla_${type}.xlsx`);};
  const validate=async(destination:number)=>{
    setBusy(true);setError('');try {
      const form=new FormData();if(file)form.append('file',file);form.append('type',type);form.append('policy',policy);form.append('quantity',quantity);form.append('action','preview');form.append('choices',JSON.stringify(choices));
      const response=await apiClient.post('/api/v1/admin/control-administrativo/importacion-masiva',form);setPreview(response.data);
      if(destination===5&&response.data.summary.errors){setError('Quedan incidencias: corrige el Excel o elige saltar las filas afectadas.');setPhase(4);}else setPhase(destination);
    }catch(e:any){setError(e?.message || 'No se pudo validar el archivo.');}finally{setBusy(false);}
  };
  const confirm=async()=>{
    setBusy(true);setError('');try {
      const form=new FormData();if(file)form.append('file',file);form.append('type',type);form.append('policy',policy);form.append('quantity',quantity);form.append('action','commit');form.append('choices',JSON.stringify(choices));form.append('token',preview.token);
      const response=await apiClient.post('/api/v1/admin/control-administrativo/importacion-masiva',form);setResult(response.data);
    }catch(e:any){setError(e?.message || 'No se ha guardado ningún registro.');setPhase(4);setPreview(null);}finally{setBusy(false);}
  };
  const resetPreview=()=>{setPreview(null);setChoices({});setError('');};
  return <div className="min-h-screen bg-gray-100 text-gray-700"><MiddleNav tituloprincipal="Importación masiva"/><main className="mx-auto max-w-6xl space-y-5 p-6">
    <Link href="/dashboard/administracion/control-administrativo" className="inline-block cursor-pointer text-blue-900 hover:underline">Volver a Órdenes</Link>
    <ol className="grid grid-cols-2 gap-2 md:grid-cols-6">{phases.map((name,index)=><li key={name} aria-current={phase===index?'step':undefined} className={`rounded p-3 text-sm ${phase===index?'bg-blue-950 text-white':'bg-white'}`}>{index+1}. {name}</li>)}</ol>
    {error&&<p role="alert" className="rounded bg-red-50 p-3 text-red-700">{error}</p>}
    {result?<section className="rounded bg-green-50 p-6"><h2 className="text-xl font-semibold">Importación completada</h2><p>{result.summary.create} creados · {result.summary.update} actualizados · {result.summary.unchanged} sin cambios · {result.summary.skip} omitidos.</p><ul className="mt-4 space-y-2">{result.ids.slice(0,30).map((id:string)=><li key={id}><Link className="cursor-pointer text-blue-900 hover:underline" href={type==='contratos'?`/dashboard/comercial/contratos/${encodeURIComponent(id)}`:type==='facturas'?`/dashboard/administracion/facturas-clientes/${encodeURIComponent(id)}`:`/dashboard/administracion/control-administrativo/${encodeURIComponent(id)}`}>{id}</Link></li>)}</ul><button className={`${button} mt-4`} onClick={()=>{setResult(null);setPhase(0);setFile(null);resetPreview();}}>Nueva importación</button></section>:<section className="space-y-5 rounded bg-white p-6">
      {phase===0&&<><h2 className="text-xl font-semibold">Qué vas a importar</h2><div className="grid gap-4 md:grid-cols-3"><label>Tipo<select className={`${select} block w-full`} value={type} onChange={e=>{setType(e.target.value as ImportType);setFile(null);resetPreview();}}>{Object.entries(bulkImportTypes).map(([key,value])=><option key={key} value={key}>{value.label}</option>)}</select></label><label>Cantidad<select className={`${select} block w-full`} value={quantity} onChange={e=>{setQuantity(e.target.value);resetPreview();}}><option value="one">Un registro</option><option value="many">Varios registros</option></select></label><label>Si ya existe<select className={`${select} block w-full`} value={policy} onChange={e=>{setPolicy(e.target.value);resetPreview();}}>{Object.entries(bulkPolicies).map(([key,value])=><option key={key} value={key}>{value}</option>)}</select></label></div><p>El identificador determina si se crea o se actualiza. Las celdas vacías y «-» conservan valores anteriores; los registros ausentes del Excel no se borran. Las decisiones por fila se revisan antes de guardar.</p></>}
      {phase===1&&<><h2 className="text-xl font-semibold">Formato de {schema.label.toLowerCase()}</h2><p>Una fila por registro, primera hoja y cabeceras exactas. Los campos marcados * son necesarios al crear; para actualizar basta el identificador y los campos que cambian. Introduce los IDs como texto para conservar ceros iniciales.</p><button className={button} onClick={template}>Descargar plantilla Excel</button><div className="overflow-x-auto"><SortableTable className="w-full text-sm"><thead><tr><th className="p-2 text-left">Columna</th><th className="p-2 text-left">Formato</th></tr></thead><tbody>{schema.fields.map(field=><tr key={field.key} className="border-t"><td className="p-2 font-mono">{field.key}{field.required?' *':''}</td><td className="p-2">{descriptions[field.type]}</td></tr>)}</tbody></SortableTable></div>
        <p>Los IDs de cuenta, agente, contacto, contrato y factura deben existir y corresponder entre sí. El identificador principal de un registro nuevo debe ser único.</p>
        {type==='facturas'&&<p>Se crean facturas en proceso. Esta importación no emite ni envía facturas a VeriFactu; sus líneas e impuestos se completan en el editor. Las facturas emitidas o contabilizadas no se sobrescriben.</p>}
        {type==='contratos'&&<p>Se importan los datos generales del contrato, sin propuesta ni factura automática. Sus órdenes pueden importarse después usando id_contrato; los servicios se preparan al facturar.</p>}
        {type==='ordenes'&&<p>Contrato y factura son opcionales. No se inventan facturas para completar referencias. Los recibos se generan desde las órdenes; los cobros ya conciliados se modifican desde revisión bancaria.</p>}
      </>}
      {phase===2&&<><h2 className="text-xl font-semibold">Subir Excel</h2><label className="block">Archivo .xlsx o .xls · hasta 10 MB y 5.000 filas<input className="mt-3 block w-full cursor-pointer rounded border p-3 hover:border-blue-900" type="file" accept=".xlsx,.xls" onChange={e=>{setFile(e.target.files?.[0] || null);resetPreview();}}/></label>{file&&<p>{file.name}</p>}<p>El archivo se valida antes de guardar cualquier registro.</p></>}
      {phase===3&&preview&&<><h2 className="text-xl font-semibold">Resultado de la validación</h2><p>{preview.rows.length} filas: {preview.summary.create} nuevas, {preview.summary.update} actualizaciones, {preview.summary.unchanged} sin cambios y {preview.summary.skip} omitidas.</p><p>{preview.summary.errors} filas requieren resolver incidencias. Todavía no se ha guardado ningún cambio.</p></>}
      {phase===4&&<><h2 className="text-xl font-semibold">Incidencias y sobrescrituras</h2><p>Despliega una tarjeta para ver errores y cambios. Corrige el archivo volviendo al paso anterior o salta la fila; los valores anteriores permanecen si no llega un valor nuevo.</p>{!preview&&<button className={button} disabled={busy} onClick={()=>validate(4)}>Volver a validar</button>}{preview?.rows.filter((row:any)=>row.errors.length||row.action==='update'||row.action==='skip').map((row:any)=><details key={row.row} className="rounded border p-3"><summary className="cursor-pointer rounded p-2 hover:bg-blue-50">Fila {row.row} · {row.id || 'Sin identificador'} · {row.errors.length?`${row.errors.length} incidencias`:row.action==='skip'?'Omitida':'Actualización'}</summary><div className="space-y-3 p-2">{row.errors.map((message:string,index:number)=><p key={index} className="text-red-700">{message}</p>)}{row.changes.length>0&&<div className="overflow-x-auto"><SortableTable className="w-full text-sm"><thead><tr><th className="text-left">Campo</th><th className="text-left">Anterior</th><th className="text-left">Nuevo</th></tr></thead><tbody>{row.changes.map((change:any)=><tr key={change.field}><td className="p-1">{change.field}</td><td className="p-1">{String(change.before)}</td><td className="p-1">{String(change.after)}</td></tr>)}</tbody></SortableTable></div>}<label>Decisión<select className={`${select} ml-3`} value={choices[row.row] || ''} onChange={e=>setChoices({...choices,[row.row]:e.target.value})}><option value="">Aplicar regla general</option><option value="skip">Saltar esta fila</option><option value="update">Crear o actualizar solo campos con valor</option></select></label></div></details>)}</>}
      {phase===5&&preview&&<><h2 className="text-xl font-semibold">Confirmación final</h2><p>{preview.summary.create} registros nuevos · {preview.summary.update} actualizaciones · {preview.summary.unchanged} sin cambios · {preview.summary.skip} omitidos.</p><p>Se guardará el conjunto validado en una única transacción. Si cambian los datos desde la validación, se pedirá revisarlos de nuevo. No se borran registros ausentes ni se emiten facturas fiscales.</p></>}
      <div className="flex justify-between gap-3"><button className={button} disabled={phase===0||busy} onClick={()=>{setError('');setPhase(phase-1);}}>Anterior</button>{phase<2?<button className={button} onClick={()=>setPhase(phase+1)}>Continuar</button>:phase===2?<button className={button} disabled={!file||busy} onClick={()=>validate(3)}>{busy?'Validando…':'Validar Excel'}</button>:phase===3?<button className={button} onClick={()=>setPhase(4)}>Revisar incidencias</button>:phase===4?<button className={button} disabled={!file||busy} onClick={()=>validate(5)}>{busy?'Validando…':'Validar decisiones y continuar'}</button>:<button className={button} disabled={busy||!preview||preview.summary.errors>0} onClick={confirm}>{busy?'Guardando…':'Confirmar importación'}</button>}</div>
    </section>}
  </main></div>;
}
