'use client';
import { useEffect, useState } from 'react';
import apiClient from '@/app/apiClient';
import type { Linea } from '@/app/components/ProposalServices';

type Template={id_plantilla:string;nombre:string;versiones:Record<string,Linea[]>};
const labels:Record<string,string>={es:'Español',en:'Inglés',it:'Italiano',pt:'Portugués'};
export default function ProposalTemplatePicker({language,onLanguageChange,onUse,onClose}:{language:string;onLanguageChange:(value:string)=>void;onUse:(lines:Linea[],mode:'replace'|'append')=>void;onClose:()=>void}){
  const [rows,setRows]=useState<Template[]>([]),[selected,setSelected]=useState(''),[tab,setTab]=useState(language),[mode,setMode]=useState<'replace'|'append'>('replace'),[error,setError]=useState('');
  useEffect(()=>{apiClient.get('/api/v1/comercial/propuestas/plantillas').then(response=>{setRows(response.data);setSelected(response.data[0]?.id_plantilla||'');}).catch(reason=>setError(reason.response?.data?.message||reason.message));},[]);
  useEffect(()=>{const close=(event:KeyboardEvent)=>{if(event.key==='Escape')onClose();};window.addEventListener('keydown',close);return()=>window.removeEventListener('keydown',close);},[onClose]);
  const template=rows.find(row=>row.id_plantilla===selected);
  const lines=template?.versiones[tab]||[];
  return <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 p-4"><section role="dialog" aria-modal="true" aria-label="Usar plantilla" className="max-h-[90vh] w-full max-w-4xl overflow-auto rounded bg-white p-6 text-slate-900 shadow-xl"><div className="flex justify-between"><h2 className="text-lg font-semibold">Aplicar plantilla a los productos</h2><button type="button" aria-label="Cerrar" onClick={onClose} className="cursor-pointer rounded px-2 text-xl hover:bg-slate-100">×</button></div>{error&&<p role="alert" className="mt-3 text-red-700">{error}</p>}
    <label className="mt-4 block text-sm">Idioma de la propuesta<select value={language} onChange={event=>onLanguageChange(event.target.value)} className="mt-1 w-full cursor-pointer rounded border p-2 hover:border-blue-900">{Object.entries(labels).map(([code,label])=><option key={code} value={code}>{label}</option>)}</select></label>
    <label className="mt-4 block text-sm">Plantilla<select value={selected} onChange={event=>{setSelected(event.target.value);setTab(language);}} className="mt-1 w-full cursor-pointer rounded border p-2 hover:border-blue-900">{rows.map(row=><option key={row.id_plantilla} value={row.id_plantilla}>{row.nombre}</option>)}</select></label>
    {template&&<><nav className="mt-5 flex flex-wrap gap-2" aria-label="Idioma de la plantilla">{Object.keys(template.versiones).map(lang=><button type="button" key={lang} onClick={()=>setTab(lang)} className={`cursor-pointer rounded px-3 py-2 hover:bg-blue-100 ${tab===lang?'bg-blue-950 text-white hover:bg-blue-900':''}`}>{labels[lang]||lang}</button>)}</nav><div className="mt-4 space-y-2">{lines.map((line,i)=><article key={i} className="rounded border p-3 text-sm"><strong>{line.producto||line.id_servicio}</strong><p>{line.descripcion_linea}</p><p className="text-slate-500">{Number(line.precio_unitario).toFixed(2)} € · {line.unidades} unidades</p></article>)}</div><label className="mt-4 block text-sm">Aplicación<select value={mode} onChange={event=>setMode(event.target.value as 'replace'|'append')} className="mt-1 w-full cursor-pointer rounded border p-2 hover:border-blue-900"><option value="replace">Sustituir productos actuales</option><option value="append">Añadir a los productos actuales</option></select></label>{tab!==language&&<p className="mt-3 text-sm text-amber-700">Cambia arriba el idioma de la propuesta a {labels[tab]||tab} para usar esta versión.</p>}<button type="button" disabled={tab!==language||!lines.length} onClick={()=>onUse(lines.map(line=>({...line,id_linea_propuesta:undefined})),mode)} className="mt-4 rounded bg-blue-950 px-4 py-2 text-white enabled:cursor-pointer enabled:hover:bg-blue-900 disabled:cursor-default disabled:opacity-50">Usar esta versión</button></>}</section></div>;
}
