"use client";

import { use, useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import MiddleNav from "@/app/general_components/componentes_recurrentes/MiddleNav";

export default function EditPlannedExpensePage({ params }: { params: Promise<{ id_pago: string }> }) {
  const { id_pago } = use(params);
  const router = useRouter();
  const [form, setForm] = useState<any>(null);
  const [providers, setProviders] = useState<any[]>([]);
  const [providerFilter, setProviderFilter] = useState("");
  const [saving, setSaving] = useState(false);
  const [message, setMessage] = useState("");
  useEffect(() => { Promise.all([fetch(`/api/v1/direccion/prevision-gastos/${encodeURIComponent(id_pago)}`).then((r) => r.json()), fetch("/api/v1/admin/proveedores").then((r) => r.json())]).then(([payment, providerRows]) => { const [day = "", month = "", year = ""] = String(payment.fecha_pago || "").split("/"); setForm({ ...payment, day, month, year }); setProviders(Array.isArray(providerRows) ? providerRows : []); }); }, [id_pago]);
  if (!form) return <div className="min-h-screen bg-gray-100"><MiddleNav tituloprincipal="Gasto previsto"/><main className="p-12">Cargando…</main></div>;
  const date = `${form.day}/${form.month}/${form.year}`;
  const save = async () => { setSaving(true); setMessage(""); const response = await fetch(`/api/v1/direccion/prevision-gastos/${encodeURIComponent(id_pago)}`, { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ...form, fecha_pago: date }) }); const data = await response.json(); setSaving(false); setMessage(response.ok ? "Cambios guardados" : data.message || "No se ha podido guardar"); };
  const shownProviders = providers.filter((provider) => !providerFilter.trim() || [provider.id_proveedor, provider.nombre_proveedor, provider.nombre_fiscal_proveedor, provider.vat_code].join(" ").toLowerCase().includes(providerFilter.trim().toLowerCase())).slice(0, 12);
  return <div className="min-h-screen bg-gray-100"><MiddleNav tituloprincipal={`Cargo previsto ${id_pago}`}/><main className="p-6 lg:p-12"><button type="button" onClick={() => router.push("/dashboard/direccion/bancos/prevision-cargos")} className="mb-4 cursor-pointer rounded border bg-white px-4 py-2 transition hover:bg-gray-50">← Volver a previsión de cargos</button><section className="mx-auto max-w-4xl space-y-5 rounded-xl bg-white p-6 shadow">
    <div><h1 className="text-xl font-semibold text-blue-950">Modificar cargo previsto</h1><p className="text-sm text-gray-500">Asocia un proveedor pendiente o actualiza los datos de este cargo concreto.</p></div>
    <div><label className="text-sm font-medium">Buscar proveedor<input type="search" value={providerFilter} onChange={(e) => setProviderFilter(e.target.value)} className="mt-1 w-full rounded border px-3 py-2"/></label><div className="mt-2 max-h-40 overflow-y-auto border">{shownProviders.map((provider) => <button key={provider.id_proveedor} type="button" onClick={() => setForm({ ...form, id_proveedor: provider.id_proveedor, nombre_proveedor: provider.nombre_proveedor })} className={`flex w-full cursor-pointer justify-between border-b p-2 text-left text-sm transition hover:bg-blue-50 ${form.id_proveedor === provider.id_proveedor ? "bg-blue-100" : ""}`}><span>{provider.nombre_proveedor || provider.nombre_fiscal_proveedor}</span><span>{provider.id_proveedor}</span></button>)}</div></div>
    <div className="grid gap-4 sm:grid-cols-2"><label className="text-sm font-medium">Concepto<input value={form.nombre_planificacion || ""} onChange={(e) => setForm({ ...form, nombre_planificacion: e.target.value })} className="mt-1 w-full rounded border px-3 py-2"/></label><label className="text-sm font-medium">Factura de proveedor<input value={form.id_factura_proveedor || ""} onChange={(e) => setForm({ ...form, id_factura_proveedor: e.target.value })} className="mt-1 w-full rounded border px-3 py-2"/></label></div>
    <fieldset><legend className="mb-1 text-sm font-medium">Fecha prevista</legend><div className="flex gap-2"><input aria-label="Día" value={form.day} onChange={(e) => setForm({ ...form, day: e.target.value.replace(/\D/g, "").slice(0,2) })} className="w-20 rounded border px-3 py-2"/><input aria-label="Mes" value={form.month} onChange={(e) => setForm({ ...form, month: e.target.value.replace(/\D/g, "").slice(0,2) })} className="w-20 rounded border px-3 py-2"/><input aria-label="Año" value={form.year} onChange={(e) => setForm({ ...form, year: e.target.value.replace(/\D/g, "").slice(0,4) })} className="w-28 rounded border px-3 py-2"/></div></fieldset>
    <div className="grid gap-4 sm:grid-cols-2"><label className="text-sm font-medium">Forma<select value={form.forma_pago || "recibo"} onChange={(e) => setForm({ ...form, forma_pago: e.target.value })} className="mt-1 w-full cursor-pointer rounded border bg-white px-3 py-2"><option value="recibo">Recibo</option><option value="transferencia">Transferencia</option><option value="pagaré">Pagaré</option></select></label><label className="text-sm font-medium">Banco<select value={form.cuenta_pago || "Sabadell"} onChange={(e) => setForm({ ...form, cuenta_pago: e.target.value })} className="mt-1 w-full cursor-pointer rounded border bg-white px-3 py-2"><option>Sabadell</option><option>Santander</option></select></label></div>
    <div className="grid gap-4 sm:grid-cols-2"><label className="text-sm font-medium">Base imponible (€)<input type="number" step="0.01" value={form.bi_pago || ""} onChange={(e) => setForm({ ...form, bi_pago: e.target.value })} className="mt-1 w-full rounded border px-3 py-2"/></label><label className="text-sm font-medium">Importe (€)<input type="number" min="0.01" step="0.01" value={form.total_pago || ""} onChange={(e) => setForm({ ...form, total_pago: e.target.value })} className="mt-1 w-full rounded border px-3 py-2"/></label></div>
    <label className="block text-sm font-medium">Descripción<textarea value={form.descripcion_planificacion || ""} onChange={(e) => setForm({ ...form, descripcion_planificacion: e.target.value })} className="mt-1 min-h-24 w-full rounded border px-3 py-2"/></label>{message && <p className="rounded bg-blue-50 p-3 text-sm text-blue-900">{message}</p>}<div className="flex justify-end"><button type="button" disabled={saving} onClick={() => void save()} className="cursor-pointer rounded bg-blue-950 px-5 py-2 font-semibold text-white transition hover:bg-blue-900 disabled:cursor-not-allowed disabled:bg-gray-400">{saving ? "Guardando…" : "Guardar cambios"}</button></div>
  </section></main></div>;
}
