'use client';
import {useEffect,useState} from 'react';
import {useParams} from 'next/navigation';
import Link from 'next/link';
import apiClient from '@/app/apiClient';
import TaskList from '@/app/components/tasks/TaskList';
export default function EmployeeTasks(){
 const {id}=useParams(),employee=String(id);
 const [agent,setAgent]=useState<any>(null),[open,setOpen]=useState(false),[saving,setSaving]=useState(false),[error,setError]=useState(''),[revision,setRevision]=useState(0),[form,setForm]=useState({nombre:'',descripcion:''});
 useEffect(()=>{apiClient.get('/api/v1/tareas/agentes').then(r=>{const found=r.data.find((a:any)=>a.id_agente===employee);if(!found)setError('Agente empleado no encontrado.');else setAgent(found);}).catch(e=>setError(e.response?.data?.message||'No se pudo cargar el empleado.'));},[employee]);
 useEffect(()=>{if(!open)return;const close=(e:KeyboardEvent)=>{if(e.key==='Escape')setOpen(false);};window.addEventListener('keydown',close);return()=>window.removeEventListener('keydown',close);},[open]);
 const create=async(e:React.FormEvent)=>{e.preventDefault();setSaving(true);setError('');try{await apiClient.post('/api/v1/tareas',{...form,agente:employee,estado:'pendiente'});setOpen(false);setForm({nombre:'',descripcion:''});setRevision(r=>r+1);}catch(reason:any){setError(reason.response?.data?.message||'No se pudo crear la tarea.');}finally{setSaving(false);}};
 return <main className="space-y-5 bg-gray-100 p-8"><Link href="/dashboard/operaciones/tareas" className="cursor-pointer text-blue-900 hover:underline">Todos los empleados</Link><header className="flex items-center justify-between gap-4"><h1 className="text-2xl font-semibold">Tareas de {agent?.nombre||'…'}</h1><button type="button" disabled={!agent} onClick={()=>setOpen(true)} className="rounded bg-blue-950 px-4 py-2 text-white enabled:cursor-pointer enabled:hover:bg-blue-900 disabled:cursor-not-allowed disabled:opacity-50">Crear tarea</button></header>{error&&<p role="alert" className="text-red-700">{error}</p>}{agent&&<TaskList key={revision} employee={employee}/>}{open&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 p-4"><section role="dialog" aria-modal="true" aria-label="Crear tarea" className="relative w-full max-w-xl rounded bg-white p-6"><button aria-label="Cerrar" type="button" onClick={()=>setOpen(false)} className="absolute right-3 top-2 cursor-pointer rounded px-2 text-2xl hover:bg-gray-100">×</button><h2 className="mb-4 text-xl font-semibold">Crear tarea para {agent?.nombre}</h2><form onSubmit={create} className="space-y-4"><label className="block">Nombre<input required maxLength={250} disabled={saving} value={form.nombre} onChange={e=>setForm({...form,nombre:e.target.value})} className="mt-1 block w-full rounded border border-gray-200 p-2"/></label><label className="block">Descripción<textarea disabled={saving} value={form.descripcion} onChange={e=>setForm({...form,descripcion:e.target.value})} className="mt-1 block min-h-32 w-full rounded border border-gray-200 p-2"/></label>{error&&<p role="alert" className="text-red-700">{error}</p>}<button disabled={saving} className="rounded bg-blue-950 px-4 py-2 text-white enabled:cursor-pointer enabled:hover:bg-blue-900 disabled:cursor-not-allowed disabled:opacity-50">{saving?'Guardando…':'Crear tarea'}</button></form></section></div>}</main>;
}
