'use client';
import {useCallback,useEffect,useState} from 'react';
import apiClient from '@/app/apiClient';
const button='rounded border px-4 py-2 enabled:cursor-pointer enabled:hover:bg-blue-50 disabled:cursor-not-allowed disabled:opacity-50';
export default function RecoverableBackups(){
  const [rows,setRows]=useState<any[]>([]),[name,setName]=useState(''),[error,setError]=useState(''),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false);
  const load=useCallback(async(signal?:AbortSignal)=>{try{const response=await apiClient.get('/api/v1/direccion/copias-seguridad/recuperables',{signal});if(!signal?.aborted){setRows(response.data);setError('');}}catch(reason:any){if(!signal?.aborted)setError(reason.message);}finally{if(!signal?.aborted)setLoading(false);}},[]);
  useEffect(()=>{const controller=new AbortController();void load(controller.signal);return()=>controller.abort();},[load]);
  const running=rows.some(row=>row.state==='working');
  useEffect(()=>{if(!running)return;const controller=new AbortController();const timer=setInterval(()=>void load(controller.signal),3000);return()=>{controller.abort();clearInterval(timer);};},[running,load]);
  async function start(){setBusy(true);setError('');try{await apiClient.post('/api/v1/direccion/copias-seguridad/recuperables',{name});setName('');await load();}catch(reason:any){setError(reason.message);}finally{setBusy(false);}}
  return <section className="mb-6 space-y-3 rounded border bg-white p-5"><h2 className="text-xl font-semibold">Copias recuperables</h2><p>Estructura y datos PostgreSQL, documentos y manifiesto con comprobaciones SHA-256. Se conservan en el servidor para volver a descargarlas. La restauración se prueba en una base aislada antes de usarlas en producción.</p><div className="flex flex-wrap gap-3"><label>Nombre<input value={name} onChange={event=>setName(event.target.value)} className="ml-3 rounded border p-2"/></label><button type="button" disabled={!name.trim()||busy||running} onClick={()=>void start()} className={button}>{busy?'Preparando…':'Crear copia recuperable'}</button></div>{loading&&<p role="status">Cargando copias…</p>}{error&&<p role="alert" className="text-red-700">{error} <button type="button" className={button} onClick={()=>void load()}>Reintentar</button></p>}{rows.map(row=><article key={row.id} className="rounded border p-3"><p className="font-semibold">{row.name} · {new Date(row.created).toLocaleString('es-ES')}</p><p role={row.state==='working'?'status':undefined}>{row.stage} · {row.objects} documentos</p>{row.state==='ready'&&<><a className="mt-2 inline-block cursor-pointer rounded border px-3 py-2 hover:bg-blue-50" href={`/api/v1/direccion/copias-seguridad/recuperables/${row.id}?download=1`}>Descargar copia</a><p className="break-all text-xs">SHA-256: {row.sha256}</p></>}</article>)}</section>;
}
