'use client';
import {useEffect,useMemo,useState} from 'react';
import Link from 'next/link';
import DatePartsInput from '@/app/components/DatePartsInput';
import apiClient from '@/app/apiClient';
import {magazineEvents,magazineMonths,magazineDate,magazineDateKey} from '@/app/config/magazineEvents';
export type Magazine={id_revista:string;revista:string;edicion:string;numero_publicacion:string;estado_publicacion:string;[key:string]:string};
export default function MagazineCalendar({rows,onSaved}:{rows:Magazine[];onSaved:()=>Promise<void>}){
  const [filter,setFilter]=useState(''),[editing,setEditing]=useState(''),[date,setDate]=useState(''),[saving,setSaving]=useState(false),[error,setError]=useState('');
  const months=useMemo(()=>magazineMonths(),[]);
  const events=useMemo(()=>{
    const first=months[0],last=months[months.length-1],start=`${first.year}-${String(first.month+1).padStart(2,'0')}-01`,end=`${last.year}-${String(last.month+1).padStart(2,'0')}-31`;
    return rows.flatMap(row=>magazineEvents.map(event=>({...event,row,id:`${row.id_revista}:${event.key}`,date:row[event.key]||'',day:magazineDateKey(row[event.key])}))).filter(event=>(event.day?event.day>=start&&event.day<=end:event.row.estado_publicacion!=='publicada')&&`${event.row.revista} ${event.row.edicion} ${event.row.numero_publicacion} ${event.label}`.toLocaleLowerCase('es').includes(filter.toLocaleLowerCase('es'))).sort((a,b)=>(a.day||'9999').localeCompare(b.day||'9999')||a.row.revista.localeCompare(b.row.revista));
  },[rows,filter,months]);
  useEffect(()=>{if(editing)document.getElementById(`event-${editing}`)?.scrollIntoView({block:'nearest'});},[editing]);
  const save=async(event:typeof events[number])=>{if(magazineDate(date)===null){setError('Revisa la fecha: dd / mm / yyyy.');return;}setSaving(true);setError('');try{await apiClient.patch(`/api/v1/produccion/revistas/${encodeURIComponent(event.row.id_revista)}`,{[event.key]:date});await onSaved();setEditing('');}catch(reason:any){setError(reason.response?.data?.detail||reason.message);}finally{setSaving(false);}};
  return <div className="grid items-start gap-6 xl:grid-cols-[minmax(0,1fr)_360px]">
    <div className="space-y-6">{months.map(month=><section key={`${month.year}-${month.month}`} className="overflow-hidden rounded-lg border bg-white"><h2 className="bg-blue-950 px-4 py-3 text-lg font-semibold capitalize text-white">{month.title}</h2><div className="grid grid-cols-7 bg-slate-100 text-center text-sm font-semibold">{['L','M','X','J','V','S','D'].map((day,index)=><span key={index} className="p-2">{day}</span>)}</div>{month.weeks.map((week,index)=><div key={index} className="grid grid-cols-7">{week.map((day,column)=>{const key=day?`${month.year}-${String(month.month+1).padStart(2,'0')}-${String(day).padStart(2,'0')}`:'';return <div key={column} className={`min-h-24 min-w-0 border-t border-r p-1.5 ${day?'':'bg-slate-50'}`}>{day&&<><span className="text-sm font-medium">{day}</span><div className="mt-1 space-y-1">{events.filter(event=>event.day===key).map(event=><button key={event.id} type="button" onClick={()=>{setEditing(event.id);setDate(event.date);document.getElementById('magazine-event-editor')?.scrollIntoView({block:'nearest'});}} title={`${event.row.revista} ${event.row.edicion} ${event.row.numero_publicacion}: ${event.label}`} className={`block w-full cursor-pointer rounded p-1 text-left text-[10px] leading-tight transition hover:brightness-95 ${event.color}`}>{event.row.revista} {event.row.numero_publicacion}<br/>{event.label}</button>)}</div></>}</div>;})}</div>)}</section>)}</div>
    <aside id="magazine-event-editor" className="sticky top-4 rounded-lg border bg-white p-4 shadow-sm"><h2 className="mb-3 font-semibold">Eventos de revista</h2><label className="block text-xs font-light text-slate-600">Filtrar por revista, edición, número o evento<input value={filter} onChange={event=>setFilter(event.target.value)} className="mb-4 mt-1 w-full rounded border p-2 text-sm"/></label>{error&&<p role="alert" className="mb-3 text-sm text-red-700">{error}</p>}<div className="max-h-[70vh] space-y-3 overflow-y-auto">{events.map(event=><article id={`event-${event.id}`} key={event.id} className="rounded border p-3"><Link href={`/dashboard/produccion/revistas/${encodeURIComponent(event.row.id_revista)}`} className="cursor-pointer text-sm font-semibold text-blue-950 hover:underline">{event.row.revista} · {event.row.edicion} · {event.row.numero_publicacion}</Link><p className={`my-2 rounded p-1.5 text-xs ${event.color}`}>{event.label}</p>{editing===event.id?<div><DatePartsInput label="Fecha" value={date} onChange={setDate}/><div className="mt-2 flex gap-2"><button disabled={saving} type="button" onClick={()=>void save(event)} className="cursor-pointer rounded bg-blue-950 px-3 py-1.5 text-sm text-white hover:bg-blue-900 disabled:cursor-default disabled:opacity-50">Guardar</button><button disabled={saving} type="button" onClick={()=>setEditing('')} className="cursor-pointer rounded px-2 py-1.5 text-sm hover:bg-slate-100 disabled:cursor-default">Cancelar</button></div></div>:<button type="button" onClick={()=>{setEditing(event.id);setDate(event.date);}} className="cursor-pointer rounded px-2 py-1 text-sm text-blue-900 hover:bg-blue-50">{event.date||'Sin fecha'} · Editar</button>}</article>)}{!events.length&&<p className="text-sm text-slate-500">No hay eventos con este filtro.</p>}</div></aside>
  </div>;
}
