'use client';
import {useEffect,useState} from 'react';
import {useParams,usePathname} from 'next/navigation';
import Link from 'next/link';
import apiClient from '@/app/apiClient';
import DatePartsInput from '@/app/components/DatePartsInput';
import {magazineEvents,magazineDate} from '@/app/config/magazineEvents';
import MagazineContents from '@/app/dashboard/produccion/contenidos/revistas/[id_revista]/MagazineContents';
import type {Magazine} from './MagazineCalendar';
export default function MagazineDetail(){
  const {id_revista}=useParams<{id_revista:string}>(),pathname=usePathname();
  const contents=pathname.endsWith('/contenidos'),base=`${pathname.startsWith('/dashboard/produccion/contenidos/')?'/dashboard/produccion/contenidos/revistas':'/dashboard/produccion/revistas'}/${encodeURIComponent(id_revista)}`;
  const [row,setRow]=useState<Magazine|null>(null),[form,setForm]=useState<Record<string,string>>({}),[error,setError]=useState(''),[saving,setSaving]=useState(false),[saved,setSaved]=useState(false);
  useEffect(()=>{let alive=true;apiClient.get(`/api/v1/produccion/revistas/${encodeURIComponent(id_revista)}`).then(response=>{if(alive){setRow(response.data);setForm(response.data);}}).catch(reason=>{if(alive)setError(reason.message);});return()=>{alive=false;};},[id_revista]);
  const save=async()=>{const keys=['fecha_publicacion',...magazineEvents.map(event=>event.key)];if(keys.some(key=>magazineDate(form[key])===null)){setError('Revisa las fechas: dd / mm / yyyy.');return;}setSaving(true);setError('');setSaved(false);try{const response=await apiClient.patch(`/api/v1/produccion/revistas/${encodeURIComponent(id_revista)}`,{...Object.fromEntries(keys.map(key=>[key,form[key]||''])),estado_publicacion:form.estado_publicacion||'pendiente de publicar'});setRow(response.data);setForm(response.data);setSaved(true);}catch(reason:any){setError(reason.response?.data?.detail||reason.message);}finally{setSaving(false);}};
  return <main className="min-h-screen bg-gray-100 p-6 pb-16 text-slate-900 lg:p-8"><Link href="/dashboard/produccion/revistas" className="cursor-pointer text-blue-900 hover:underline">← Volver a revistas</Link>{error&&<p role="alert" className="my-4 rounded bg-red-50 p-3 text-red-700">{error}</p>}{!row?<p className="mt-6">Cargando revista…</p>:<><h1 className="my-5 text-2xl font-semibold">{row.revista} · {row.edicion} · {row.numero_publicacion}</h1><nav aria-label="Ficha de revista" className="flex gap-1">{[{label:'Datos de la revista',href:base,active:!contents},{label:'Contenidos',href:`${base}/contenidos`,active:contents}].map(tab=><Link key={tab.href} href={tab.href} aria-current={tab.active?'page':undefined} className={`cursor-pointer rounded-t-lg border px-5 py-3 font-medium transition ${tab.active?'border-b-white bg-white text-blue-950':'bg-slate-200 text-slate-600 hover:bg-slate-100'}`}>{tab.label}</Link>)}</nav><div className="rounded-b-lg rounded-tr-lg border bg-white p-5">{contents?<MagazineContents/>:<form onSubmit={event=>{event.preventDefault();void save();}}><div className="grid gap-5 md:grid-cols-2 xl:grid-cols-3">{[{key:'fecha_publicacion',label:'Fecha de publicación'},...magazineEvents].map(event=><DatePartsInput key={event.key} label={event.label} value={form[event.key]||''} onChange={value=>{setSaved(false);setForm(previous=>({...previous,[event.key]:value}));}}/>)}<label className="text-sm">Estado de publicación<select value={form.estado_publicacion||'pendiente de publicar'} onChange={event=>{setSaved(false);setForm(previous=>({...previous,estado_publicacion:event.target.value}));}} className="mt-1 block w-full cursor-pointer rounded border p-2 hover:border-blue-900"><option value="pendiente de publicar">Pendiente de publicar</option><option value="publicada">Publicada</option></select></label></div><button disabled={saving} type="submit" className="mt-6 cursor-pointer rounded bg-blue-950 px-4 py-2 text-white hover:bg-blue-900 disabled:cursor-default disabled:opacity-50">{saving?'Guardando…':'Guardar datos'}</button>{saved&&<p role="status" className="mt-3 text-green-700">Datos guardados.</p>}</form>}</div></>}</main>;
}
