'use client';
import { matchesTableFilter } from "@/app/lib/dateFilters";
import TableFilterInput from "@/app/components/TableFilterInput";
import TableFilters from '@/app/components/TableFilters';
import Link from 'next/link';
import {useEffect,useState} from 'react';
import apiClient from '@/app/apiClient';
import DatePartsInput from '@/app/components/DatePartsInput';
import MiddleNav from '@/app/general_components/componentes_recurrentes/MiddleNav';

type Revista={id_revista:string;revista:string;edicion:string;numero_publicacion:string;estado_publicacion:string;fecha_publicacion:string;deadline_materiales:string;fecha_recordatorio:string};
type Dates=Pick<Revista,'fecha_publicacion'|'deadline_materiales'|'fecha_recordatorio'>;
const pending='pendiente de publicar';
const emptyDates=():Dates=>({fecha_publicacion:'',deadline_materiales:'',fecha_recordatorio:''});
const dateValid=(value:string)=>{if(!value)return true;const match=value.match(/^(\d{1,2})\/(\d{1,2})\/(\d{4})$/);if(!match)return false;const date=new Date(Number(match[3]),Number(match[2])-1,Number(match[1]));return date.getFullYear()===Number(match[3])&&date.getMonth()+1===Number(match[2])&&date.getDate()===Number(match[1]);};
const labels:Record<string,string>={revista:'Revista',edicion:'Edición',numero_publicacion:'Número',estado_publicacion:'Estado',fecha_publicacion:'Fecha publicación',deadline_materiales:'Fecha límite material',fecha_recordatorio:'Fecha recordatorio'};

export default function RevistasProduccionPage(){
  const [rows,setRows]=useState<Revista[]>([]),[tab,setTab]=useState<'pendientes'|'calendario'>('pendientes');
  const [selectedMagazine,setSelectedMagazine]=useState('');
  const [selectedEdition,setSelectedEdition]=useState('');
  const [filters,setFilters]=useState<Record<string,string>>({}),[createOpen,setCreateOpen]=useState(false),[editing,setEditing]=useState<Revista|null>(null);
  const [saving,setSaving]=useState(false),[error,setError]=useState('');
  const [form,setForm]=useState({revista:'',edicion:'',numero_publicacion:'',estado_publicacion:pending,...emptyDates()}),[dates,setDates]=useState<Dates>(emptyDates());
  const reload=async()=>setRows((await apiClient.get('/api/v1/produccion/revistas')).data);
  useEffect(()=>{reload().catch(reason=>setError(reason.response?.data?.message||reason.message));},[]);
  useEffect(()=>{if(!createOpen&&!editing)return;const close=(event:KeyboardEvent)=>{if(event.key==='Escape'){setCreateOpen(false);setEditing(null);}};window.addEventListener('keydown',close);return()=>window.removeEventListener('keydown',close);},[createOpen,editing]);
  const magazineRank=(name:string)=>/vidrio/i.test(name)?0:/^ventanas/i.test(name)?1:/qui[eé]n/i.test(name)?2:3;
  const magazines=Array.from(new Set(rows.filter(row=>row.estado_publicacion!=='publicada').map(row=>row.revista))).sort((a,b)=>magazineRank(a)-magazineRank(b)||a.localeCompare(b,'es'));
  const activeMagazine=magazines.includes(selectedMagazine)?selectedMagazine:magazines[0];
  const hasEditions=tab==='pendientes'&&/vidrio|^ventanas|qui[eé]n/i.test(activeMagazine||'');
  const editions=Array.from(new Set(rows.filter(row=>row.revista===activeMagazine).map(row=>row.edicion))).sort((a,b)=>a.localeCompare(b,'es'));
  const activeEdition=editions.includes(selectedEdition)?selectedEdition:editions[0];
  const columns=tab==='pendientes'?['numero_publicacion','revista',...(!hasEditions?['edicion']:[]),'estado_publicacion']:['numero_publicacion','revista','fecha_publicacion','deadline_materiales','fecha_recordatorio'];
  const visible=rows.filter(row=>(tab==='calendario'||row.estado_publicacion!=='publicada'&&row.revista===activeMagazine&&(!hasEditions||row.edicion===activeEdition))&&columns.every(column=>matchesTableFilter(String(row[column as keyof Revista]||'').toLocaleLowerCase('es'), (filters[column]||'').trim().toLocaleLowerCase('es'))));
  const create=async(event:React.FormEvent)=>{event.preventDefault();if(![form.fecha_publicacion,form.deadline_materiales,form.fecha_recordatorio].every(dateValid)){setError('Revisa las fechas.');return;}setSaving(true);setError('');try{await apiClient.post('/api/v1/produccion/revistas',{...form,publicacion:form.numero_publicacion});await reload();setCreateOpen(false);setForm({revista:'',edicion:'',numero_publicacion:'',estado_publicacion:pending,...emptyDates()});}catch(reason:any){setError(reason.response?.data?.detail||reason.response?.data?.message||reason.message);}finally{setSaving(false);}};
  const changeStatus=async(row:Revista,status:string)=>{setError('');try{await apiClient.patch(`/api/v1/produccion/revistas/${encodeURIComponent(row.id_revista)}/estado`,{estado:status});await reload();}catch(reason:any){setError(reason.response?.data?.message||reason.message);}};
  const saveDates=async(event:React.FormEvent)=>{event.preventDefault();if(!editing)return;if(!Object.values(dates).every(dateValid)){setError('Revisa las fechas.');return;}setSaving(true);setError('');try{await apiClient.patch(`/api/v1/produccion/revistas/${encodeURIComponent(editing.id_revista)}`,dates);await reload();setEditing(null);}catch(reason:any){setError(reason.response?.data?.detail||reason.response?.data?.message||reason.message);}finally{setSaving(false);}};
  const dateFields=(value:Dates,onChange:(patch:Partial<Dates>)=>void)=><div className="grid gap-3 md:grid-cols-3"><DatePartsInput label="Fecha publicación" value={value.fecha_publicacion} onChange={next=>onChange({fecha_publicacion:next})}/><DatePartsInput label="Fecha límite material" value={value.deadline_materiales} onChange={next=>onChange({deadline_materiales:next})}/><DatePartsInput label="Fecha recordatorio" value={value.fecha_recordatorio} onChange={next=>onChange({fecha_recordatorio:next})}/></div>;
  return <main className="min-h-screen bg-gray-100 text-slate-900"><MiddleNav tituloprincipal="Revistas"/><div className="mx-auto max-w-6xl p-8">
    <header className="mb-5 flex flex-wrap items-center justify-between gap-3"><h1 className="text-2xl font-semibold">Revistas</h1><button type="button" onClick={()=>setCreateOpen(true)} className="cursor-pointer rounded bg-blue-950 px-4 py-2 text-white hover:bg-blue-900">Agregar revista</button></header>
    {error&&<p role="alert" className="mb-4 rounded bg-red-50 p-3 text-red-700">{error}</p>}
    <div className="mb-4 flex gap-2">{(['pendientes','calendario'] as const).map(value=><button key={value} type="button" onClick={()=>{setTab(value);setFilters({});}} className={`cursor-pointer rounded px-4 py-2 text-sm hover:bg-blue-100 ${tab===value?'bg-blue-950 text-white hover:bg-blue-900':'bg-white'}`}>{value==='pendientes'?'Pendientes':'Calendario'}</button>)}</div>
    {tab==='pendientes'&&<div role="tablist" aria-label="Revistas pendientes" className="mb-4 flex flex-wrap gap-2">{magazines.map(magazine=><button role="tab" aria-selected={activeMagazine===magazine} type="button" key={magazine} onClick={()=>{setSelectedMagazine(magazine);setSelectedEdition('');setFilters({});}} className={`cursor-pointer rounded px-4 py-2 text-sm transition ${activeMagazine===magazine?'bg-blue-950 text-white hover:bg-blue-900':'bg-white hover:bg-blue-100'}`}>{magazine||'Sin revista'}</button>)}</div>}
    {hasEditions&&<div role="tablist" aria-label="Ediciones" className="mb-4 flex flex-wrap gap-2">{editions.map(edition=><button key={edition} role="tab" aria-selected={edition===activeEdition} type="button" onClick={()=>{setSelectedEdition(edition);setFilters({});}} className={`cursor-pointer rounded px-3 py-1.5 text-sm ${edition===activeEdition?'bg-blue-100 text-blue-950 hover:bg-blue-200':'bg-white hover:bg-blue-50'}`}>{edition||'Sin edición'}</button>)}</div>}
    <TableFilters><div className="contents">{columns.map(column=><label key={column} className="text-xs text-slate-600">{labels[column]}<TableFilterInput label={labels[column]} field={column} value={filters[column]||''} className="mt-1 w-full rounded border border-gray-100 bg-white px-2 py-1.5 text-xs" onChange={nextValue => setFilters(previous=>({...previous,[column]:nextValue}))} /></label>)}</div></TableFilters>
    <div className="overflow-x-auto rounded border border-gray-100 bg-white"><table className="w-full text-left text-sm"><thead className="bg-blue-950 text-white"><tr>{columns.map(column=><th key={column} className="p-3">{labels[column]}</th>)}<th className="p-3">{tab==='calendario'?'Modificar':'Gestión'}</th></tr></thead><tbody>{visible.map(row=><tr key={row.id_revista} className="border-t border-gray-100 hover:bg-blue-50">{columns.map(column=><td key={column} className="p-3">{column==='estado_publicacion'?<select aria-label={`Estado de ${row.revista} ${row.numero_publicacion}`} value={row.estado_publicacion||pending} onChange={event=>void changeStatus(row,event.target.value)} className="cursor-pointer rounded border border-gray-100 p-2 hover:border-blue-900"><option value={pending}>Pendiente de publicar</option><option value="publicada">Publicada</option></select>:row[column as keyof Revista]||'—'}</td>)}<td className="p-3">{tab==='calendario'?<button type="button" onClick={()=>{setDates({fecha_publicacion:row.fecha_publicacion||'',deadline_materiales:row.deadline_materiales||'',fecha_recordatorio:row.fecha_recordatorio||''});setEditing(row);}} className="cursor-pointer text-blue-900 hover:underline">Modificar</button>:<Link href={`/dashboard/produccion/contenidos/revistas/${encodeURIComponent(row.id_revista)}`} className="cursor-pointer text-blue-900 hover:underline">Abrir</Link>}</td></tr>)}</tbody></table>{!visible.length&&<p className="p-5 text-slate-500">No hay revistas con estos filtros.</p>}</div>
  </div>{(createOpen||editing)&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 p-4"><section role="dialog" aria-modal="true" aria-label={editing?'Modificar calendario':'Agregar revista'} className="relative w-full max-w-3xl rounded bg-white p-6 shadow-xl"><button type="button" aria-label="Cerrar" onClick={()=>{setCreateOpen(false);setEditing(null);}} className="absolute right-3 top-2 cursor-pointer rounded px-2 text-2xl hover:bg-gray-100">×</button><h2 className="mb-5 text-xl font-semibold">{editing?`Modificar fechas: ${editing.revista} ${editing.numero_publicacion}`:'Agregar revista'}</h2><form onSubmit={editing?saveDates:create} className="space-y-4">{!editing&&<div className="grid gap-3 md:grid-cols-3"><label className="text-sm">Revista<input required value={form.revista} onChange={event=>setForm({...form,revista:event.target.value})} className="mt-1 w-full rounded border p-2"/></label><label className="text-sm">Edición<input required value={form.edicion} onChange={event=>setForm({...form,edicion:event.target.value})} className="mt-1 w-full rounded border p-2"/></label><label className="text-sm">Número<input required type="number" min="1" step="1" value={form.numero_publicacion} onChange={event=>setForm({...form,numero_publicacion:event.target.value})} className="mt-1 w-full rounded border p-2"/></label></div>}{dateFields(editing?dates:form,patch=>editing?setDates(previous=>({...previous,...patch})):setForm(previous=>({...previous,...patch})))}{!editing&&<label className="block text-sm">Estado<select value={form.estado_publicacion} onChange={event=>setForm({...form,estado_publicacion:event.target.value})} className="mt-1 w-full cursor-pointer rounded border p-2 hover:border-blue-900"><option value={pending}>Pendiente de publicar</option><option value="publicada">Publicada</option></select></label>}<button type="submit" disabled={saving} className="cursor-pointer rounded bg-blue-950 px-4 py-2 text-white hover:bg-blue-900 disabled:cursor-default disabled:opacity-50">{saving?'Guardando...':editing?'Guardar fechas':'Crear revista'}</button></form></section></div>}</main>;
}
