'use client';
import SortableTable from '@/app/components/SortableTable';

import {useEffect,useState} from 'react';
import {useParams,useRouter} from 'next/navigation';
import Link from 'next/link';
import RecurringChargeEnd from '../../RecurringChargeEnd';
import RecurringChargeManageModal from '../../RecurringChargeManageModal';
import {reviewButton} from '../../RecurringChargeForm';
export default function Page(){
  const {id}=useParams<{id:string}>(),router=useRouter();const [data,setData]=useState<any>(null),[error,setError]=useState(''),[version,setVersion]=useState(0),[action,setAction]=useState<'edit'|'delete'|null>(null);
  useEffect(()=>{const controller=new AbortController();fetch(`/api/v1/direccion/cargos-recurrentes/${id}`,{cache:'no-store',signal:controller.signal}).then(async r=>{const d=await r.json();if(!r.ok)throw Error(d.message);setData(d);}).catch(e=>{if(e.name!=='AbortError')setError(e.message);});return()=>controller.abort();},[id,version]);
  const money=(n:any)=>Number(n).toLocaleString('es-ES',{style:'currency',currency:'EUR'});
  return <main className="min-h-screen space-y-5 bg-white p-6 text-slate-900"><Link className="cursor-pointer rounded p-2 hover:bg-blue-50" href="/dashboard/direccion/tesoreria/prevision-liquidez">Volver a previsión de liquidez</Link><h1 className="text-2xl font-semibold">Cargo previsto {id}</h1>{error&&<p role="alert">{error}</p>}{data&&<><section className="space-y-3 rounded bg-white p-5"><p>{data.tipo_cargo==='otro'?'Otro':data.tipo_cargo==='nomina'?'Nómina':'Proveedor'} · {data.id_agente||data.id_proveedor||'Sin destinatario'} · {data.activo?'Activo':'Inactivo'}</p>{data.programacion.map((p:any,i:number)=><p key={i}>{p.descripcion||'Sin descripción'} · {money(p.total_iva)} · Base: {money(p.base_imponible)} · {data.tipo_programacion==='fechas'?`${p.dia}/${p.mes}/${p.anio||'Cada año'}`:`Cada ${p.cada} ${p.unidad}`}</p>)}<RecurringChargeEnd charge={data} onSaved={()=>setVersion(v=>v+1)}/><div className="flex gap-3"><button className={reviewButton} onClick={()=>setAction('edit')}>Editar</button><button className={reviewButton} onClick={()=>setAction('delete')}>Eliminar</button></div></section><section className="rounded border border-gray-200 bg-white p-5"><h2 className="mb-3 text-lg font-semibold">Cargos planificados</h2><div className="space-y-2">{(data.vencimientos||[]).map((v:any)=><p key={v.id}>{v.fecha.split('-').reverse().join('/')} · {v.descripcion} ? {money(v.importe)}</p>)}{!data.vencimientos?.length&&<p>No hay vencimientos planificados.</p>}</div></section><section className="overflow-x-auto rounded border border-gray-200 bg-white p-5"><h2 className="mb-3 text-lg font-semibold">Movimientos del extracto ya asociados a este cargo recurrente</h2><SortableTable className="w-full text-left"><thead><tr>{['Registro','Banco','Fecha','Concepto','Importe','Revisado'].map(t=><th key={t} className="p-2">{t}</th>)}</tr></thead><tbody>{data.movimientos.map((l:any)=><tr key={l.id_linea_banco} className="cursor-pointer border-t hover:bg-blue-50" onClick={()=>router.push(`/dashboard/direccion/tesoreria/extractos/${l.id_linea_banco}`)}><td className="p-2"><Link className="cursor-pointer hover:underline" href={`/dashboard/direccion/tesoreria/extractos/${l.id_linea_banco}`}>{l.id_linea_banco}</Link></td><td>{l.banco}</td><td>{l.fecha_valor}</td><td>{l.concepto}</td><td>{money(l.importe)}</td><td>{l.estado_revision?'Sí':'No'}</td></tr>)}</tbody></SortableTable>{!data.movimientos.length&&<p>Todavía no se ha asociado ningún movimiento del extracto a este cargo recurrente.</p>}</section></>}{action&&<RecurringChargeManageModal id={id} action={action} onClose={()=>setAction(null)} onSaved={()=>{setAction(null);if(action==='delete')router.push('/dashboard/direccion/tesoreria/prevision-liquidez');else setVersion(v=>v+1);}}/>}</main>;
}
