'use client';
import Link from 'next/link';
import { useState } from 'react';
import { Header, Notice, money, periodLabel, root, useResource } from './ui';
export function EmployeePayrollList({employee,version=0}:{employee?:string;version?:number}) {
  const {data,loading,error}=useResource<any[]>(`nominas-empleados?${new URLSearchParams({...(employee?{empleado:employee}:{}),v:String(version)})}`);
  const [filter,setFilter]=useState('');
  const rows=(data||[]).filter(r=>`${r.id} ${r.empleado}`.toLocaleLowerCase().includes(filter.toLocaleLowerCase()));
  return <section className="laboral-card"><label className="mb-4 block">Buscar empleado o ID<input className="mt-1 block rounded border p-2" value={filter} onChange={e=>setFilter(e.target.value)}/></label><Notice error={error}/><table><thead><tr><th>Nómina</th><th>Cargos recurrentes</th></tr></thead><tbody>{rows.map(r=><tr key={r.id} data-interactive tabIndex={0} onClick={()=>window.location.assign(`${root}/nominas/${r.id}`)} onKeyDown={e=>{if(e.key==='Enter')window.location.assign(`${root}/nominas/${r.id}`);}}><td><Link className="cursor-pointer hover:underline" href={`${root}/nominas/${r.id}`}>Nómina {r.empleado}</Link></td><td>{r.cargos || 'Sin cargo recurrente'}</td></tr>)}</tbody></table>{loading?<p>Cargando nóminas…</p>:!rows.length&&!error&&<p>No hay nóminas registradas.</p>}</section>;
}
export function EmployeePayrollDetail({id}:{id:string}) {
  const {data,loading,error}=useResource<any>(`nominas-empleados/${id}`);
  if(loading)return <p>Cargando nómina…</p>;
  if(error||!data)return <Notice error={error||'Nómina no encontrada.'}/>;
  return <><Header title={`Nómina ${data.empleado}`} back={`${root}/nominas`}/><section className="laboral-card mb-5"><h2 className="mb-3 text-lg font-semibold">Nómina pactada · Cargos recurrentes</h2>{!data.cargos.length && <p>Histórico de nómina sin cargo recurrente. No se generan previsiones futuras.</p>}{data.cargos.map((c:any)=><div key={c.id_cargo_recurrente} className="mb-3 rounded border p-4"><p>Cargo {c.id_cargo_recurrente} · {c.activo?'Activo':'Inactivo'}</p>{c.programacion.map((r:any,i:number)=><p key={i}>{r.descripcion} · {money(r.total_iva)} · {c.tipo_programacion==='fechas'?`${r.dia}/${r.mes}/${r.anio||'Cada año'}`:`Cada ${r.cada} ${r.unidad}`}</p>)}<Link className="inline-block cursor-pointer rounded p-2 text-blue-900 hover:bg-blue-50 hover:underline" href={`/dashboard/direccion/tesoreria/cargos-recurrentes/${c.id_cargo_recurrente}`}>Ver y modificar cargo previsto</Link></div>)}</section>
    <section className="laboral-card mb-5"><h2 className="mb-3 text-lg font-semibold">Registros bancarios asociados</h2><div className="overflow-x-auto"><table><thead><tr><th>Registro</th><th>Fecha</th><th>Concepto</th><th>Importe</th><th>Tipo</th><th>Cargo recurrente</th></tr></thead><tbody>{data.movimientos.map((r:any)=><tr key={r.id_linea_banco}><td><Link className="cursor-pointer text-blue-900 hover:underline" href={`/dashboard/direccion/tesoreria/extractos/revision/${r.id_linea_banco}`}>{r.id_linea_banco}</Link></td><td>{r.fecha_valor}</td><td>{r.concepto}</td><td>{money(r.importe)}</td><td>{r.id_anticipo?<Link className="cursor-pointer text-blue-900 hover:underline" href={`${root}/anticipos/${r.id_anticipo}`}>Anticipo</Link>:r.tipo_nomina==='otros'?'Otros':r.tipo_nomina==='adicional'?'Importe adicional':'Nómina'}</td><td>{r.id_cargo_recurrente || 'Sin cargo recurrente'}</td></tr>)}</tbody></table></div>{!data.movimientos.length&&<p>Todavía no hay movimientos asociados.</p>}</section>
    <section className="laboral-card mb-5"><h2 className="mb-3 text-lg font-semibold">Anticipos del empleado</h2><table><thead><tr><th>Anticipo</th><th>Periodo</th><th>Importe</th><th>Estado</th><th>Registro bancario</th></tr></thead><tbody>{data.anticipos.map((a:any)=><tr key={a.id}><td><Link className="cursor-pointer text-blue-900 hover:underline" href={`${root}/anticipos/${a.id}`}>{a.id}</Link></td><td>{periodLabel(a.mes,a.anio)}</td><td>{money(a.importe_neto)}</td><td>{a.estado}</td><td>{a.id_transferencia&&<Link className="cursor-pointer text-blue-900 hover:underline" href={`/dashboard/direccion/tesoreria/extractos/revision/${a.id_transferencia}`}>{a.id_transferencia}</Link>}</td></tr>)}</tbody></table>{!data.anticipos.length&&<p>No hay anticipos registrados.</p>}</section>
    <section className="laboral-card"><h2 className="mb-3 text-lg font-semibold">Liquidaciones mensuales y anticipos</h2>{data.periodos.map((p:any)=><p key={p.id}><Link className="cursor-pointer text-blue-900 hover:underline" href={`${root}/nominas/${p.id}`}>{periodLabel(p.mes,p.anio)} · {money(p.importe_neto)} · {p.estado}</Link></p>)}{!data.periodos.length&&<p>No hay liquidaciones mensuales confirmadas.</p>}</section></>;
}
