'use client';

import Link from 'next/link';
import { useRouter } from 'next/navigation';
import { useState } from 'react';
import { DateFields, DeleteButton, Documents, Field, Form, Header, Modal, Notice, YearField, dateLabel, isoDate, request, useResource } from './ui';

type Employee = { id_agente: string; nombre?: string; nombre_agente: string; apellidos_agente: string; nombre_completo_agente: string; email_agente: string; dni_agente: string; rol_agente: string; estado_agente: string; is_empleado_account: boolean };
type Absence = { id: string; tipo: string; inicio: string; fin: string; comentarios: string };
type EmployeeData = { agente: Employee; anio: number; libres: Array<{ numero: number; fecha: string }>; ausencias: Absence[]; comentarios: Array<{ id: string; comentario: string; created_at: string }> };
const name = (e: Employee) => e.nombre || e.nombre_completo_agente || `${e.nombre_agente} ${e.apellidos_agente}`.trim() || e.id_agente;

export function EmployeeList({ activeOnly = false }: { activeOnly?: boolean }) {
  const router = useRouter(), { data, loading, error } = useResource<Employee[]>('empleados'), [query,setQuery] = useState('');
  const filtered = data?.filter(e => (!activeOnly || e.estado_agente?.trim().toLowerCase() === 'activo') && `${name(e)} ${e.email_agente}`.toLowerCase().includes(query.toLowerCase())) || [];
  return <><Header title="Asuntos empleados" /><section className="laboral-card"><div className="mb-4 max-w-md"><Field label="Buscar empleado"><input value={query} onChange={e => setQuery(e.target.value)} /></Field></div><Notice error={error} /><div className="overflow-x-auto"><table><thead><tr><th>Empleado</th><th>Email</th><th>Rol</th>{!activeOnly && <th>Estado</th>}</tr></thead><tbody>{filtered.map(e => <tr key={e.id_agente} data-interactive tabIndex={0} onClick={() => router.push(`/dashboard/operaciones/agentes/asuntos/${e.id_agente}`)} onKeyDown={event => { if (event.key === 'Enter') router.push(`/dashboard/operaciones/agentes/asuntos/${e.id_agente}`); }}><td><Link className="rounded text-blue-900 hover:underline" href={`/dashboard/operaciones/agentes/asuntos/${e.id_agente}`}>{name(e)}</Link></td><td>{e.email_agente || '—'}</td><td>{e.rol_agente}</td>{!activeOnly && <td>{e.estado_agente}</td>}</tr>)}</tbody></table></div>{loading ? <p className="p-4">Cargando empleados…</p> : !filtered.length && !error && <p className="p-4 text-slate-500">No hay cuentas de empleado que coincidan.</p>}</section></>;
}

export function EmployeeDetail({ id }: { id: string }) {
  const [year,setYear] = useState(new Date().getFullYear()), [draftYear,setDraftYear] = useState(year);
  const { data, loading, error, reload } = useResource<EmployeeData>(`empleados/${id}?anio=${year}`);
  const [absence,setAbsence] = useState<Partial<Absence> | null>(null), [comment,setComment] = useState('');
  return <><Header title={data ? name(data.agente) : 'Ficha del empleado'} back="/dashboard/operaciones/agentes?tab=asuntos"><form className="flex items-end gap-2" onSubmit={e => { e.preventDefault(); setYear(draftYear); }}><div className="w-28"><YearField value={draftYear} onChange={setDraftYear} /></div><button type="submit" className="laboral-secondary">Consultar año</button></form></Header><Notice error={error} />{loading && <p>Cargando ficha…</p>}{data && !loading && !error && <div className="space-y-5"><section className="laboral-card"><h2 className="mb-4 text-lg font-semibold text-blue-950">Datos de agente</h2><dl className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[['Identificador',data.agente.id_agente],['Nombre',data.agente.nombre_agente],['Apellidos',data.agente.apellidos_agente],['Nombre completo',data.agente.nombre_completo_agente],['Email',data.agente.email_agente],['DNI',data.agente.dni_agente],['Rol',data.agente.rol_agente],['Estado',data.agente.estado_agente],['Cuenta de empleado',data.agente.is_empleado_account ? 'Sí' : 'No']].map(([label,value]) => <div key={label}><dt className="text-xs uppercase text-slate-500">{label}</dt><dd className="mt-1 break-words">{value || '—'}</dd></div>)}</dl><Link href={`/dashboard/operaciones/agentes/${id}`} className="mt-4 inline-block rounded p-2 text-blue-900 hover:bg-blue-50">Abrir ficha de agente →</Link></section>
    <section className="laboral-card"><h2 className="text-lg font-semibold text-blue-950">Libre disposición · {year}</h2><p className="mb-4 mt-1 text-slate-500">3 días al año · {data.libres.length} usados · {3 - data.libres.length} disponibles</p><FreeDays key={`${year}-${JSON.stringify(data.libres)}`} id={id} year={year} days={data.libres} onSaved={reload} /></section>
    <Documents kind="empleados" id={id} />
    <section className="laboral-card"><div className="mb-4 flex flex-wrap items-center justify-between gap-3"><h2 className="text-lg font-semibold text-blue-950">Ausencias · {year}</h2><button className="laboral-button" onClick={() => setAbsence({ inicio: `${year}-01-01`,fin: `${year}-01-01` })}>Agregar ausencia</button></div><div className="overflow-x-auto"><table><thead><tr><th>Tipo / motivo</th><th>Desde</th><th>Hasta</th><th>Comentarios</th><th>Acciones</th></tr></thead><tbody>{data.ausencias.map(a => <tr key={a.id}><td>{a.tipo}</td><td>{dateLabel(a.inicio)}</td><td>{dateLabel(a.fin)}</td><td className="max-w-md whitespace-pre-wrap">{a.comentarios || '—'}</td><td><div className="flex gap-2"><button className="laboral-secondary" onClick={() => setAbsence(a)}>Editar</button><DeleteButton path={`empleados/${id}/ausencias/${a.id}`} onDeleted={reload} /></div></td></tr>)}</tbody></table></div>{!data.ausencias.length && <p className="mt-3 text-slate-500">Sin ausencias registradas en este año.</p>}</section>
    <section className="laboral-card"><h2 className="mb-4 text-lg font-semibold text-blue-950">Comentarios</h2><Form label="Agregar comentario" onSave={async () => { await request(`empleados/${id}/comentarios`,'POST',{ comentario: comment }); setComment(''); reload(); }}><Field label="Nuevo comentario"><textarea required value={comment} onChange={e => setComment(e.target.value)} /></Field></Form><div className="mt-5 space-y-3">{data.comentarios.map(c => <article key={c.id} className="rounded border border-slate-200 p-3"><div className="mb-2 flex justify-between gap-3"><span className="text-xs text-slate-500">{dateLabel(c.created_at)}</span><DeleteButton path={`empleados/${id}/comentarios/${c.id}`} onDeleted={reload} /></div><p className="whitespace-pre-wrap">{c.comentario}</p></article>)}</div>{!data.comentarios.length && <p className="mt-3 text-slate-500">Sin comentarios.</p>}</section>
  </div>}{absence && <Modal title={absence.id ? 'Editar ausencia' : 'Agregar ausencia'} onClose={() => setAbsence(null)}><AbsenceForm id={id} initial={absence} onSaved={() => { setAbsence(null); reload(); }} /></Modal>}</>;
}

function FreeDays({ id, year, days, onSaved }: { id: string; year: number; days: EmployeeData['libres']; onSaved: () => void }) {
  const [values,setValues] = useState(Array.from({ length: 3 },(_,i) => ({ numero: i + 1, used: days.some(d => d.numero === i + 1), fecha: days.find(d => d.numero === i + 1)?.fecha || '' })));
  return <Form onSave={async () => { await request(`empleados/${id}/libres`,'PUT',{ anio: year,fechas: values.filter(v => v.used).map(v => ({ numero: v.numero,fecha: isoDate(v.fecha) })) }); onSaved(); }}><div className="grid gap-4 lg:grid-cols-3">{values.map((v,i) => <div key={v.numero} className="rounded border border-slate-200 p-3"><label className="mb-3 flex cursor-pointer items-center gap-2 rounded p-1 hover:bg-blue-50"><input type="checkbox" checked={v.used} onChange={e => setValues(current => current.map((d,index) => index === i ? { ...d,used: e.target.checked } : d))} />Día {v.numero}: {v.used ? 'usado' : 'sin usar'}</label>{v.used && <DateFields label={`Fecha del día ${v.numero}`} value={v.fecha} onChange={fecha => setValues(current => current.map((d,index) => index === i ? { ...d,fecha } : d))} />}</div>)}</div></Form>;
}
function AbsenceForm({ id, initial, onSaved }: { id: string; initial: Partial<Absence>; onSaved: () => void }) {
  const [form,setForm] = useState({ tipo: initial.tipo || '',inicio: initial.inicio || '',fin: initial.fin || '',comentarios: initial.comentarios || '' });
  return <Form onSave={async () => { await request(`empleados/${id}/ausencias${initial.id ? `/${initial.id}` : ''}`,initial.id ? 'PUT' : 'POST',{ ...form,inicio: isoDate(form.inicio),fin: isoDate(form.fin) }); onSaved(); }}><Field label="Tipo / motivo"><input required maxLength={200} value={form.tipo} onChange={e => setForm({ ...form,tipo: e.target.value })} /></Field><div className="grid gap-4 sm:grid-cols-2"><DateFields label="Desde" value={form.inicio} onChange={inicio => setForm({ ...form,inicio })} /><DateFields label="Hasta" value={form.fin} onChange={fin => setForm({ ...form,fin })} /></div><Field label="Comentarios"><textarea value={form.comentarios} onChange={e => setForm({ ...form,comentarios: e.target.value })} /></Field></Form>;
}
