'use client';

import Link from 'next/link';
import { useRouter } from 'next/navigation';
import { useState } from 'react';
import { DeleteButton, Field, Form, Header, Modal, Notice, dateLabel, request, root, useResource } from './ui';

const states = ['pendiente llamada','rechazado en llamada','pendiente reunión presencial','rechazado en reunión presencial','elegido','reserva'];
type Candidate = { id: string; nombre: string; resumen_cv: string; comentarios: string; estado: string };
type Process = { id: string; nombre: string; oferta_condiciones: string; mensaje_pre_llamada: string; mensaje_post_llamada: string; mensaje_rechazo: string; created_at: string };

export function HiringList() {
  const router = useRouter(), { data, loading, error } = useResource<Array<Process & { candidatos: number }>>('procesos'), [adding,setAdding] = useState(false), [name,setName] = useState('');
  return <><Header title="Contratación"><button className="laboral-button" onClick={() => setAdding(true)}>Agregar proceso</button></Header><section className="laboral-card"><Notice error={error} /><table><thead><tr><th>Proceso</th><th>Candidatos</th><th>Creado</th></tr></thead><tbody>{data?.map(p => <tr key={p.id} data-interactive tabIndex={0} onClick={() => router.push(`${root}/contratacion/${p.id}`)} onKeyDown={e => { if (e.key === 'Enter') router.push(`${root}/contratacion/${p.id}`); }}><td><Link href={`${root}/contratacion/${p.id}`} className="rounded text-blue-900 hover:underline">{p.nombre}</Link></td><td>{p.candidatos}</td><td>{dateLabel(p.created_at)}</td></tr>)}</tbody></table>{loading ? <p className="p-4">Cargando procesos…</p> : !data?.length && !error && <p className="p-4 text-slate-500">No hay procesos de contratación.</p>}</section>{adding && <Modal title="Agregar proceso de contratación" onClose={() => setAdding(false)}><Form label="Crear proceso" onSave={async () => { const result = await request<{ id: string }>('procesos','POST',{ nombre: name }); router.push(`${root}/contratacion/${result.id}`); }}><Field label="Nombre del proceso / puesto"><input required maxLength={300} value={name} onChange={e => setName(e.target.value)} /></Field></Form></Modal>}</>;
}

export function HiringDetail({ id }: { id: string }) {
  const { data, loading, error, reload } = useResource<Process & { candidatos: Candidate[] }>(`procesos/${id}`);
  const [editing,setEditing] = useState<Partial<Candidate> | null>(null), [state,setState] = useState('');
  return <><Header title={data?.nombre || 'Proceso de contratación'} back={`${root}/contratacion`} /><Notice error={error} />{loading && <p>Cargando proceso…</p>}{data && !loading && !error && <div className="space-y-5"><section className="laboral-card"><ProcessForm initial={data} onSaved={reload} /></section><section className="laboral-card"><div className="mb-4 flex flex-wrap items-center justify-between gap-3"><h2 className="text-lg font-semibold text-blue-950">Candidatos</h2><button className="laboral-button" onClick={() => setEditing({})}>Agregar candidato</button></div><div className="mb-4 max-w-sm"><Field label="Filtrar por estado"><select value={state} onChange={e => setState(e.target.value)}><option value="">Todos</option>{states.map(s => <option key={s}>{s}</option>)}</select></Field></div><div className="overflow-x-auto"><table><thead><tr><th>Nombre</th><th>Resumen CV</th><th>Comentarios</th><th>Estado</th><th>Acciones</th></tr></thead><tbody>{data.candidatos.filter(c => !state || c.estado === state).map(c => <tr key={c.id}><td>{c.nombre}</td><td className="max-w-md whitespace-pre-wrap">{c.resumen_cv || '—'}</td><td className="max-w-md whitespace-pre-wrap">{c.comentarios || '—'}</td><td><span className={`rounded px-2 py-1 ${c.estado === 'elegido' ? 'bg-green-100 text-green-900' : c.estado.startsWith('rechazado') ? 'bg-red-50 text-red-800' : 'bg-blue-50 text-blue-900'}`}>{c.estado}</span></td><td><div className="flex gap-2"><button className="laboral-secondary" onClick={() => setEditing(c)}>Editar</button><DeleteButton path={`procesos/${id}/candidatos/${c.id}`} onDeleted={reload} /></div></td></tr>)}</tbody></table></div>{!data.candidatos.filter(c => !state || c.estado === state).length && <p className="mt-3 text-slate-500">Sin candidatos en esta vista.</p>}</section></div>}{editing && <Modal title={editing.id ? 'Editar candidato' : 'Agregar candidato'} onClose={() => setEditing(null)}><CandidateForm processId={id} initial={editing} onSaved={() => { setEditing(null); reload(); }} /></Modal>}</>;
}

function ProcessForm({ initial, onSaved }: { initial: Process; onSaved: () => void }) {
  const [form,setForm] = useState({ nombre: initial.nombre,oferta_condiciones: initial.oferta_condiciones,mensaje_pre_llamada: initial.mensaje_pre_llamada,mensaje_post_llamada: initial.mensaje_post_llamada,mensaje_rechazo: initial.mensaje_rechazo });
  return <Form onSave={async () => { await request(`procesos/${initial.id}`,'PUT',form); onSaved(); }}><Field label="Nombre del proceso"><input required maxLength={300} value={form.nombre} onChange={e => setForm({ ...form,nombre: e.target.value })} /></Field><div className="grid gap-4 lg:grid-cols-2">{([['oferta_condiciones','Oferta y condiciones'],['mensaje_pre_llamada','Mensaje pre-llamada'],['mensaje_post_llamada','Mensaje post-llamada'],['mensaje_rechazo','Mensaje de rechazo']] as const).map(([key,label]) => <Field key={key} label={label}><textarea rows={6} value={form[key]} onChange={e => setForm({ ...form,[key]: e.target.value })} /></Field>)}</div></Form>;
}
function CandidateForm({ processId, initial, onSaved }: { processId: string; initial: Partial<Candidate>; onSaved: () => void }) {
  const [form,setForm] = useState({ nombre: initial.nombre || '',resumen_cv: initial.resumen_cv || '',comentarios: initial.comentarios || '',estado: initial.estado || states[0] });
  return <Form onSave={async () => { await request(`procesos/${processId}/candidatos${initial.id ? `/${initial.id}` : ''}`,initial.id ? 'PUT' : 'POST',form); onSaved(); }}><Field label="Nombre"><input required maxLength={300} value={form.nombre} onChange={e => setForm({ ...form,nombre: e.target.value })} /></Field><Field label="Resumen CV"><textarea value={form.resumen_cv} onChange={e => setForm({ ...form,resumen_cv: e.target.value })} /></Field><Field label="Comentarios"><textarea value={form.comentarios} onChange={e => setForm({ ...form,comentarios: e.target.value })} /></Field><Field label="Estado"><select value={form.estado} onChange={e => setForm({ ...form,estado: e.target.value })}>{states.map(s => <option key={s}>{s}</option>)}</select></Field></Form>;
}
